// Code generated by ent, DO NOT EDIT.

package roundsnapshot

import (
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLTE(FieldID, id))
}

// RaceName applies equality check predicate on the "race_name" field. It's identical to RaceNameEQ.
func RaceName(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldRaceName, v))
}

// RaceDate applies equality check predicate on the "race_date" field. It's identical to RaceDateEQ.
func RaceDate(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldRaceDate, v))
}

// Round applies equality check predicate on the "round" field. It's identical to RoundEQ.
func Round(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldRound, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// SeasonID applies equality check predicate on the "season_id" field. It's identical to SeasonIDEQ.
func SeasonID(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldSeasonID, v))
}

// RaceNameEQ applies the EQ predicate on the "race_name" field.
func RaceNameEQ(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldRaceName, v))
}

// RaceNameNEQ applies the NEQ predicate on the "race_name" field.
func RaceNameNEQ(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNEQ(FieldRaceName, v))
}

// RaceNameIn applies the In predicate on the "race_name" field.
func RaceNameIn(vs ...string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldIn(FieldRaceName, vs...))
}

// RaceNameNotIn applies the NotIn predicate on the "race_name" field.
func RaceNameNotIn(vs ...string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNotIn(FieldRaceName, vs...))
}

// RaceNameGT applies the GT predicate on the "race_name" field.
func RaceNameGT(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGT(FieldRaceName, v))
}

// RaceNameGTE applies the GTE predicate on the "race_name" field.
func RaceNameGTE(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGTE(FieldRaceName, v))
}

// RaceNameLT applies the LT predicate on the "race_name" field.
func RaceNameLT(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLT(FieldRaceName, v))
}

// RaceNameLTE applies the LTE predicate on the "race_name" field.
func RaceNameLTE(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLTE(FieldRaceName, v))
}

// RaceNameContains applies the Contains predicate on the "race_name" field.
func RaceNameContains(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldContains(FieldRaceName, v))
}

// RaceNameHasPrefix applies the HasPrefix predicate on the "race_name" field.
func RaceNameHasPrefix(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldHasPrefix(FieldRaceName, v))
}

// RaceNameHasSuffix applies the HasSuffix predicate on the "race_name" field.
func RaceNameHasSuffix(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldHasSuffix(FieldRaceName, v))
}

// RaceNameEqualFold applies the EqualFold predicate on the "race_name" field.
func RaceNameEqualFold(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEqualFold(FieldRaceName, v))
}

// RaceNameContainsFold applies the ContainsFold predicate on the "race_name" field.
func RaceNameContainsFold(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldContainsFold(FieldRaceName, v))
}

// RaceDateEQ applies the EQ predicate on the "race_date" field.
func RaceDateEQ(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldRaceDate, v))
}

// RaceDateNEQ applies the NEQ predicate on the "race_date" field.
func RaceDateNEQ(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNEQ(FieldRaceDate, v))
}

// RaceDateIn applies the In predicate on the "race_date" field.
func RaceDateIn(vs ...string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldIn(FieldRaceDate, vs...))
}

// RaceDateNotIn applies the NotIn predicate on the "race_date" field.
func RaceDateNotIn(vs ...string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNotIn(FieldRaceDate, vs...))
}

// RaceDateGT applies the GT predicate on the "race_date" field.
func RaceDateGT(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGT(FieldRaceDate, v))
}

// RaceDateGTE applies the GTE predicate on the "race_date" field.
func RaceDateGTE(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGTE(FieldRaceDate, v))
}

// RaceDateLT applies the LT predicate on the "race_date" field.
func RaceDateLT(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLT(FieldRaceDate, v))
}

// RaceDateLTE applies the LTE predicate on the "race_date" field.
func RaceDateLTE(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLTE(FieldRaceDate, v))
}

// RaceDateContains applies the Contains predicate on the "race_date" field.
func RaceDateContains(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldContains(FieldRaceDate, v))
}

// RaceDateHasPrefix applies the HasPrefix predicate on the "race_date" field.
func RaceDateHasPrefix(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldHasPrefix(FieldRaceDate, v))
}

// RaceDateHasSuffix applies the HasSuffix predicate on the "race_date" field.
func RaceDateHasSuffix(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldHasSuffix(FieldRaceDate, v))
}

// RaceDateEqualFold applies the EqualFold predicate on the "race_date" field.
func RaceDateEqualFold(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEqualFold(FieldRaceDate, v))
}

// RaceDateContainsFold applies the ContainsFold predicate on the "race_date" field.
func RaceDateContainsFold(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldContainsFold(FieldRaceDate, v))
}

// RoundEQ applies the EQ predicate on the "round" field.
func RoundEQ(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldRound, v))
}

// RoundNEQ applies the NEQ predicate on the "round" field.
func RoundNEQ(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNEQ(FieldRound, v))
}

// RoundIn applies the In predicate on the "round" field.
func RoundIn(vs ...int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldIn(FieldRound, vs...))
}

// RoundNotIn applies the NotIn predicate on the "round" field.
func RoundNotIn(vs ...int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNotIn(FieldRound, vs...))
}

// RoundGT applies the GT predicate on the "round" field.
func RoundGT(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGT(FieldRound, v))
}

// RoundGTE applies the GTE predicate on the "round" field.
func RoundGTE(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGTE(FieldRound, v))
}

// RoundLT applies the LT predicate on the "round" field.
func RoundLT(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLT(FieldRound, v))
}

// RoundLTE applies the LTE predicate on the "round" field.
func RoundLTE(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLTE(FieldRound, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldContainsFold(FieldCreatedAt, v))
}

// SeasonIDEQ applies the EQ predicate on the "season_id" field.
func SeasonIDEQ(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldEQ(FieldSeasonID, v))
}

// SeasonIDNEQ applies the NEQ predicate on the "season_id" field.
func SeasonIDNEQ(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNEQ(FieldSeasonID, v))
}

// SeasonIDIn applies the In predicate on the "season_id" field.
func SeasonIDIn(vs ...int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldIn(FieldSeasonID, vs...))
}

// SeasonIDNotIn applies the NotIn predicate on the "season_id" field.
func SeasonIDNotIn(vs ...int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNotIn(FieldSeasonID, vs...))
}

// SeasonIDGT applies the GT predicate on the "season_id" field.
func SeasonIDGT(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGT(FieldSeasonID, v))
}

// SeasonIDGTE applies the GTE predicate on the "season_id" field.
func SeasonIDGTE(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldGTE(FieldSeasonID, v))
}

// SeasonIDLT applies the LT predicate on the "season_id" field.
func SeasonIDLT(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLT(FieldSeasonID, v))
}

// SeasonIDLTE applies the LTE predicate on the "season_id" field.
func SeasonIDLTE(v int) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldLTE(FieldSeasonID, v))
}

// SeasonIDIsNil applies the IsNil predicate on the "season_id" field.
func SeasonIDIsNil() predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldIsNull(FieldSeasonID))
}

// SeasonIDNotNil applies the NotNil predicate on the "season_id" field.
func SeasonIDNotNil() predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.FieldNotNull(FieldSeasonID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoundSnapshot) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoundSnapshot) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoundSnapshot) predicate.RoundSnapshot {
	return predicate.RoundSnapshot(sql.NotPredicates(p))
}
