// Code generated by ent, DO NOT EDIT.

package racerstats

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the racerstats type in the database.
	Label = "racer_stats"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldRaces holds the string denoting the races field in the database.
	FieldRaces = "races"
	// FieldWins holds the string denoting the wins field in the database.
	FieldWins = "wins"
	// FieldGold holds the string denoting the gold field in the database.
	FieldGold = "gold"
	// FieldSilver holds the string denoting the silver field in the database.
	FieldSilver = "silver"
	// FieldBronze holds the string denoting the bronze field in the database.
	FieldBronze = "bronze"
	// FieldFastestLaps holds the string denoting the fastest_laps field in the database.
	FieldFastestLaps = "fastest_laps"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldDnf holds the string denoting the dnf field in the database.
	FieldDnf = "dnf"
	// FieldDNS holds the string denoting the dns field in the database.
	FieldDNS = "dns"
	// Table holds the table name of the racerstats in the database.
	Table = "racer_stats"
)

// Columns holds all SQL columns for racerstats fields.
var Columns = []string{
	FieldID,
	FieldRacerID,
	FieldRaces,
	FieldWins,
	FieldGold,
	FieldSilver,
	FieldBronze,
	FieldFastestLaps,
	FieldPoints,
	FieldDnf,
	FieldDNS,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRaces holds the default value on creation for the "races" field.
	DefaultRaces int
	// DefaultWins holds the default value on creation for the "wins" field.
	DefaultWins int
	// DefaultGold holds the default value on creation for the "gold" field.
	DefaultGold int
	// DefaultSilver holds the default value on creation for the "silver" field.
	DefaultSilver int
	// DefaultBronze holds the default value on creation for the "bronze" field.
	DefaultBronze int
	// DefaultFastestLaps holds the default value on creation for the "fastest_laps" field.
	DefaultFastestLaps int
	// DefaultPoints holds the default value on creation for the "points" field.
	DefaultPoints int
	// DefaultDnf holds the default value on creation for the "dnf" field.
	DefaultDnf int
	// DefaultDNS holds the default value on creation for the "dns" field.
	DefaultDNS int
)

// OrderOption defines the ordering options for the RacerStats queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// ByRaces orders the results by the races field.
func ByRaces(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaces, opts...).ToFunc()
}

// ByWins orders the results by the wins field.
func ByWins(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWins, opts...).ToFunc()
}

// ByGold orders the results by the gold field.
func ByGold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGold, opts...).ToFunc()
}

// BySilver orders the results by the silver field.
func BySilver(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSilver, opts...).ToFunc()
}

// ByBronze orders the results by the bronze field.
func ByBronze(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBronze, opts...).ToFunc()
}

// ByFastestLaps orders the results by the fastest_laps field.
func ByFastestLaps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFastestLaps, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByDnf orders the results by the dnf field.
func ByDnf(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDnf, opts...).ToFunc()
}

// ByDNS orders the results by the dns field.
func ByDNS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDNS, opts...).ToFunc()
}
