// Code generated by ent, DO NOT EDIT.

package gearshift

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gearshift type in the database.
	Label = "gear_shift"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldRaceID holds the string denoting the race_id field in the database.
	FieldRaceID = "race_id"
	// FieldLap holds the string denoting the lap field in the database.
	FieldLap = "lap"
	// FieldGear holds the string denoting the gear field in the database.
	FieldGear = "gear"
	// FieldStress holds the string denoting the stress field in the database.
	FieldStress = "stress"
	// Table holds the table name of the gearshift in the database.
	Table = "gear_shifts"
)

// Columns holds all SQL columns for gearshift fields.
var Columns = []string{
	FieldID,
	FieldRacerID,
	FieldRaceID,
	FieldLap,
	FieldGear,
	FieldStress,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLap holds the default value on creation for the "lap" field.
	DefaultLap int
	// DefaultGear holds the default value on creation for the "gear" field.
	DefaultGear int
	// DefaultStress holds the default value on creation for the "stress" field.
	DefaultStress int
)

// OrderOption defines the ordering options for the GearShift queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// ByRaceID orders the results by the race_id field.
func ByRaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaceID, opts...).ToFunc()
}

// ByLap orders the results by the lap field.
func ByLap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLap, opts...).ToFunc()
}

// ByGear orders the results by the gear field.
func ByGear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGear, opts...).ToFunc()
}

// ByStress orders the results by the stress field.
func ByStress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStress, opts...).ToFunc()
}
