// Code generated by ent, DO NOT EDIT.

package raceresult

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the raceresult type in the database.
	Label = "race_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRaceID holds the string denoting the race_id field in the database.
	FieldRaceID = "race_id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldRacerName holds the string denoting the racer_name field in the database.
	FieldRacerName = "racer_name"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldFastestLap holds the string denoting the fastest_lap field in the database.
	FieldFastestLap = "fastest_lap"
	// FieldFinished holds the string denoting the finished field in the database.
	FieldFinished = "finished"
	// Table holds the table name of the raceresult in the database.
	Table = "race_results"
)

// Columns holds all SQL columns for raceresult fields.
var Columns = []string{
	FieldID,
	FieldRaceID,
	FieldRacerID,
	FieldRacerName,
	FieldPosition,
	FieldPoints,
	FieldFastestLap,
	FieldFinished,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFastestLap holds the default value on creation for the "fastest_lap" field.
	DefaultFastestLap int
	// DefaultFinished holds the default value on creation for the "finished" field.
	DefaultFinished int
)

// OrderOption defines the ordering options for the RaceResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRaceID orders the results by the race_id field.
func ByRaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaceID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// ByRacerName orders the results by the racer_name field.
func ByRacerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerName, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByFastestLap orders the results by the fastest_lap field.
func ByFastestLap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFastestLap, opts...).ToFunc()
}

// ByFinished orders the results by the finished field.
func ByFinished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinished, opts...).ToFunc()
}
