// Code generated by ent, DO NOT EDIT.

package roundsnapshotscore

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the roundsnapshotscore type in the database.
	Label = "round_snapshot_score"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSnapshotID holds the string denoting the snapshot_id field in the database.
	FieldSnapshotID = "snapshot_id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldRacerName holds the string denoting the racer_name field in the database.
	FieldRacerName = "racer_name"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldDnf holds the string denoting the dnf field in the database.
	FieldDnf = "dnf"
	// FieldDNS holds the string denoting the dns field in the database.
	FieldDNS = "dns"
	// FieldSpins holds the string denoting the spins field in the database.
	FieldSpins = "spins"
	// Table holds the table name of the roundsnapshotscore in the database.
	Table = "round_snapshot_scores"
)

// Columns holds all SQL columns for roundsnapshotscore fields.
var Columns = []string{
	FieldID,
	FieldSnapshotID,
	FieldRacerID,
	FieldRacerName,
	FieldPoints,
	FieldPosition,
	FieldDnf,
	FieldDNS,
	FieldSpins,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPoints holds the default value on creation for the "points" field.
	DefaultPoints int
	// DefaultPosition holds the default value on creation for the "position" field.
	DefaultPosition int
	// DefaultDnf holds the default value on creation for the "dnf" field.
	DefaultDnf bool
	// DefaultDNS holds the default value on creation for the "dns" field.
	DefaultDNS bool
	// DefaultSpins holds the default value on creation for the "spins" field.
	DefaultSpins int
)

// OrderOption defines the ordering options for the RoundSnapshotScore queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySnapshotID orders the results by the snapshot_id field.
func BySnapshotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// ByRacerName orders the results by the racer_name field.
func ByRacerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerName, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByDnf orders the results by the dnf field.
func ByDnf(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDnf, opts...).ToFunc()
}

// ByDNS orders the results by the dns field.
func ByDNS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDNS, opts...).ToFunc()
}

// BySpins orders the results by the spins field.
func BySpins(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpins, opts...).ToFunc()
}
