// Code generated by ent, DO NOT EDIT.

package roundsnapshotscore

import (
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLTE(FieldID, id))
}

// SnapshotID applies equality check predicate on the "snapshot_id" field. It's identical to SnapshotIDEQ.
func SnapshotID(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldSnapshotID, v))
}

// RacerID applies equality check predicate on the "racer_id" field. It's identical to RacerIDEQ.
func RacerID(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldRacerID, v))
}

// RacerName applies equality check predicate on the "racer_name" field. It's identical to RacerNameEQ.
func RacerName(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldRacerName, v))
}

// Points applies equality check predicate on the "points" field. It's identical to PointsEQ.
func Points(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldPoints, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldPosition, v))
}

// SnapshotIDEQ applies the EQ predicate on the "snapshot_id" field.
func SnapshotIDEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldSnapshotID, v))
}

// SnapshotIDNEQ applies the NEQ predicate on the "snapshot_id" field.
func SnapshotIDNEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNEQ(FieldSnapshotID, v))
}

// SnapshotIDIn applies the In predicate on the "snapshot_id" field.
func SnapshotIDIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldIn(FieldSnapshotID, vs...))
}

// SnapshotIDNotIn applies the NotIn predicate on the "snapshot_id" field.
func SnapshotIDNotIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNotIn(FieldSnapshotID, vs...))
}

// SnapshotIDGT applies the GT predicate on the "snapshot_id" field.
func SnapshotIDGT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGT(FieldSnapshotID, v))
}

// SnapshotIDGTE applies the GTE predicate on the "snapshot_id" field.
func SnapshotIDGTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGTE(FieldSnapshotID, v))
}

// SnapshotIDLT applies the LT predicate on the "snapshot_id" field.
func SnapshotIDLT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLT(FieldSnapshotID, v))
}

// SnapshotIDLTE applies the LTE predicate on the "snapshot_id" field.
func SnapshotIDLTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLTE(FieldSnapshotID, v))
}

// RacerIDEQ applies the EQ predicate on the "racer_id" field.
func RacerIDEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldRacerID, v))
}

// RacerIDNEQ applies the NEQ predicate on the "racer_id" field.
func RacerIDNEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNEQ(FieldRacerID, v))
}

// RacerIDIn applies the In predicate on the "racer_id" field.
func RacerIDIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldIn(FieldRacerID, vs...))
}

// RacerIDNotIn applies the NotIn predicate on the "racer_id" field.
func RacerIDNotIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNotIn(FieldRacerID, vs...))
}

// RacerIDGT applies the GT predicate on the "racer_id" field.
func RacerIDGT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGT(FieldRacerID, v))
}

// RacerIDGTE applies the GTE predicate on the "racer_id" field.
func RacerIDGTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGTE(FieldRacerID, v))
}

// RacerIDLT applies the LT predicate on the "racer_id" field.
func RacerIDLT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLT(FieldRacerID, v))
}

// RacerIDLTE applies the LTE predicate on the "racer_id" field.
func RacerIDLTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLTE(FieldRacerID, v))
}

// RacerNameEQ applies the EQ predicate on the "racer_name" field.
func RacerNameEQ(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldRacerName, v))
}

// RacerNameNEQ applies the NEQ predicate on the "racer_name" field.
func RacerNameNEQ(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNEQ(FieldRacerName, v))
}

// RacerNameIn applies the In predicate on the "racer_name" field.
func RacerNameIn(vs ...string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldIn(FieldRacerName, vs...))
}

// RacerNameNotIn applies the NotIn predicate on the "racer_name" field.
func RacerNameNotIn(vs ...string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNotIn(FieldRacerName, vs...))
}

// RacerNameGT applies the GT predicate on the "racer_name" field.
func RacerNameGT(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGT(FieldRacerName, v))
}

// RacerNameGTE applies the GTE predicate on the "racer_name" field.
func RacerNameGTE(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGTE(FieldRacerName, v))
}

// RacerNameLT applies the LT predicate on the "racer_name" field.
func RacerNameLT(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLT(FieldRacerName, v))
}

// RacerNameLTE applies the LTE predicate on the "racer_name" field.
func RacerNameLTE(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLTE(FieldRacerName, v))
}

// RacerNameContains applies the Contains predicate on the "racer_name" field.
func RacerNameContains(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldContains(FieldRacerName, v))
}

// RacerNameHasPrefix applies the HasPrefix predicate on the "racer_name" field.
func RacerNameHasPrefix(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldHasPrefix(FieldRacerName, v))
}

// RacerNameHasSuffix applies the HasSuffix predicate on the "racer_name" field.
func RacerNameHasSuffix(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldHasSuffix(FieldRacerName, v))
}

// RacerNameEqualFold applies the EqualFold predicate on the "racer_name" field.
func RacerNameEqualFold(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEqualFold(FieldRacerName, v))
}

// RacerNameContainsFold applies the ContainsFold predicate on the "racer_name" field.
func RacerNameContainsFold(v string) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldContainsFold(FieldRacerName, v))
}

// PointsEQ applies the EQ predicate on the "points" field.
func PointsEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldPoints, v))
}

// PointsNEQ applies the NEQ predicate on the "points" field.
func PointsNEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNEQ(FieldPoints, v))
}

// PointsIn applies the In predicate on the "points" field.
func PointsIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldIn(FieldPoints, vs...))
}

// PointsNotIn applies the NotIn predicate on the "points" field.
func PointsNotIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNotIn(FieldPoints, vs...))
}

// PointsGT applies the GT predicate on the "points" field.
func PointsGT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGT(FieldPoints, v))
}

// PointsGTE applies the GTE predicate on the "points" field.
func PointsGTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGTE(FieldPoints, v))
}

// PointsLT applies the LT predicate on the "points" field.
func PointsLT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLT(FieldPoints, v))
}

// PointsLTE applies the LTE predicate on the "points" field.
func PointsLTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLTE(FieldPoints, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.FieldLTE(FieldPosition, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoundSnapshotScore) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoundSnapshotScore) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoundSnapshotScore) predicate.RoundSnapshotScore {
	return predicate.RoundSnapshotScore(sql.NotPredicates(p))
}
