// Code generated by ent, DO NOT EDIT.

package laprecord

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the laprecord type in the database.
	Label = "lap_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRaceID holds the string denoting the race_id field in the database.
	FieldRaceID = "race_id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldLapNumber holds the string denoting the lap_number field in the database.
	FieldLapNumber = "lap_number"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldGearUsed holds the string denoting the gear_used field in the database.
	FieldGearUsed = "gear_used"
	// FieldHeatGenerated holds the string denoting the heat_generated field in the database.
	FieldHeatGenerated = "heat_generated"
	// FieldTurboUsed holds the string denoting the turbo_used field in the database.
	FieldTurboUsed = "turbo_used"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// Table holds the table name of the laprecord in the database.
	Table = "lap_records"
)

// Columns holds all SQL columns for laprecord fields.
var Columns = []string{
	FieldID,
	FieldRaceID,
	FieldRacerID,
	FieldLapNumber,
	FieldPosition,
	FieldGearUsed,
	FieldHeatGenerated,
	FieldTurboUsed,
	FieldTimestamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRaceID holds the default value on creation for the "race_id" field.
	DefaultRaceID int
	// DefaultGearUsed holds the default value on creation for the "gear_used" field.
	DefaultGearUsed int
	// DefaultHeatGenerated holds the default value on creation for the "heat_generated" field.
	DefaultHeatGenerated int
	// DefaultTurboUsed holds the default value on creation for the "turbo_used" field.
	DefaultTurboUsed int
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp string
)

// OrderOption defines the ordering options for the LapRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRaceID orders the results by the race_id field.
func ByRaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaceID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// ByLapNumber orders the results by the lap_number field.
func ByLapNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLapNumber, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByGearUsed orders the results by the gear_used field.
func ByGearUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGearUsed, opts...).ToFunc()
}

// ByHeatGenerated orders the results by the heat_generated field.
func ByHeatGenerated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeatGenerated, opts...).ToFunc()
}

// ByTurboUsed orders the results by the turbo_used field.
func ByTurboUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurboUsed, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}
