// Code generated by ent, DO NOT EDIT.

package emailsetting

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the emailsetting type in the database.
	Label = "email_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSMTPHost holds the string denoting the smtp_host field in the database.
	FieldSMTPHost = "smtp_host"
	// FieldSMTPPort holds the string denoting the smtp_port field in the database.
	FieldSMTPPort = "smtp_port"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldFromAddr holds the string denoting the from_addr field in the database.
	FieldFromAddr = "from_addr"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// Table holds the table name of the emailsetting in the database.
	Table = "email_settings"
)

// Columns holds all SQL columns for emailsetting fields.
var Columns = []string{
	FieldID,
	FieldSMTPHost,
	FieldSMTPPort,
	FieldUsername,
	FieldPassword,
	FieldFromAddr,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSMTPPort holds the default value on creation for the "smtp_port" field.
	DefaultSMTPPort int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled int
)

// OrderOption defines the ordering options for the EmailSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySMTPHost orders the results by the smtp_host field.
func BySMTPHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPHost, opts...).ToFunc()
}

// BySMTPPort orders the results by the smtp_port field.
func BySMTPPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPPort, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByFromAddr orders the results by the from_addr field.
func ByFromAddr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAddr, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
