// Code generated by ent, DO NOT EDIT.

package upgradecard

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upgradecard type in the database.
	Label = "upgrade_card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCardType holds the string denoting the card_type field in the database.
	FieldCardType = "card_type"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldEffects holds the string denoting the effects field in the database.
	FieldEffects = "effects"
	// Table holds the table name of the upgradecard in the database.
	Table = "upgrade_cards"
)

// Columns holds all SQL columns for upgradecard fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldCardType,
	FieldCost,
	FieldEffects,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCardType holds the default value on creation for the "card_type" field.
	DefaultCardType string
	// DefaultCost holds the default value on creation for the "cost" field.
	DefaultCost int
	// DefaultEffects holds the default value on creation for the "effects" field.
	DefaultEffects string
)

// OrderOption defines the ordering options for the UpgradeCard queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCardType orders the results by the card_type field.
func ByCardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardType, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByEffects orders the results by the effects field.
func ByEffects(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffects, opts...).ToFunc()
}
