// Code generated by ent, DO NOT EDIT.

package legendability

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the legendability type in the database.
	Label = "legend_ability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAbilityType holds the string denoting the ability_type field in the database.
	FieldAbilityType = "ability_type"
	// FieldRacerName holds the string denoting the racer_name field in the database.
	FieldRacerName = "racer_name"
	// FieldExtensionID holds the string denoting the extension_id field in the database.
	FieldExtensionID = "extension_id"
	// Table holds the table name of the legendability in the database.
	Table = "legend_abilities"
)

// Columns holds all SQL columns for legendability fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldAbilityType,
	FieldRacerName,
	FieldExtensionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultExtensionID holds the default value on creation for the "extension_id" field.
	DefaultExtensionID int
)

// OrderOption defines the ordering options for the LegendAbility queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAbilityType orders the results by the ability_type field.
func ByAbilityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbilityType, opts...).ToFunc()
}

// ByRacerName orders the results by the racer_name field.
func ByRacerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerName, opts...).ToFunc()
}

// ByExtensionID orders the results by the extension_id field.
func ByExtensionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtensionID, opts...).ToFunc()
}
