// Code generated by ent, DO NOT EDIT.

package aisetting

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aisetting type in the database.
	Label = "ai_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrackExtractURL holds the string denoting the track_extract_url field in the database.
	FieldTrackExtractURL = "track_extract_url"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldDifficulty holds the string denoting the difficulty field in the database.
	FieldDifficulty = "difficulty"
	// FieldAggression holds the string denoting the aggression field in the database.
	FieldAggression = "aggression"
	// FieldErrorRate holds the string denoting the error_rate field in the database.
	FieldErrorRate = "error_rate"
	// FieldConsistency holds the string denoting the consistency field in the database.
	FieldConsistency = "consistency"
	// Table holds the table name of the aisetting in the database.
	Table = "ai_settings"
)

// Columns holds all SQL columns for aisetting fields.
var Columns = []string{
	FieldID,
	FieldTrackExtractURL,
	FieldAPIKey,
	FieldEnabled,
	FieldDifficulty,
	FieldAggression,
	FieldErrorRate,
	FieldConsistency,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled int
	// DefaultDifficulty holds the default value on creation for the "difficulty" field.
	DefaultDifficulty string
	// DefaultAggression holds the default value on creation for the "aggression" field.
	DefaultAggression int
	// DefaultErrorRate holds the default value on creation for the "error_rate" field.
	DefaultErrorRate int
	// DefaultConsistency holds the default value on creation for the "consistency" field.
	DefaultConsistency int
)

// OrderOption defines the ordering options for the AISetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrackExtractURL orders the results by the track_extract_url field.
func ByTrackExtractURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackExtractURL, opts...).ToFunc()
}

// ByAPIKey orders the results by the api_key field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByDifficulty orders the results by the difficulty field.
func ByDifficulty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDifficulty, opts...).ToFunc()
}

// ByAggression orders the results by the aggression field.
func ByAggression(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggression, opts...).ToFunc()
}

// ByErrorRate orders the results by the error_rate field.
func ByErrorRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorRate, opts...).ToFunc()
}

// ByConsistency orders the results by the consistency field.
func ByConsistency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsistency, opts...).ToFunc()
}
