// Code generated by ent, DO NOT EDIT.

package racersector

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the racersector type in the database.
	Label = "racer_sector"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRaceID holds the string denoting the race_id field in the database.
	FieldRaceID = "race_id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldSectorID holds the string denoting the sector_id field in the database.
	FieldSectorID = "sector_id"
	// FieldLap holds the string denoting the lap field in the database.
	FieldLap = "lap"
	// FieldEntryTime holds the string denoting the entry_time field in the database.
	FieldEntryTime = "entry_time"
	// FieldExitTime holds the string denoting the exit_time field in the database.
	FieldExitTime = "exit_time"
	// Table holds the table name of the racersector in the database.
	Table = "racer_sectors"
)

// Columns holds all SQL columns for racersector fields.
var Columns = []string{
	FieldID,
	FieldRaceID,
	FieldRacerID,
	FieldSectorID,
	FieldLap,
	FieldEntryTime,
	FieldExitTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRaceID holds the default value on creation for the "race_id" field.
	DefaultRaceID int
	// DefaultLap holds the default value on creation for the "lap" field.
	DefaultLap int
	// DefaultEntryTime holds the default value on creation for the "entry_time" field.
	DefaultEntryTime string
	// DefaultExitTime holds the default value on creation for the "exit_time" field.
	DefaultExitTime string
)

// OrderOption defines the ordering options for the RacerSector queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRaceID orders the results by the race_id field.
func ByRaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaceID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// BySectorID orders the results by the sector_id field.
func BySectorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSectorID, opts...).ToFunc()
}

// ByLap orders the results by the lap field.
func ByLap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLap, opts...).ToFunc()
}

// ByEntryTime orders the results by the entry_time field.
func ByEntryTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryTime, opts...).ToFunc()
}

// ByExitTime orders the results by the exit_time field.
func ByExitTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExitTime, opts...).ToFunc()
}
