// Code generated by ent, DO NOT EDIT.

package turbolog

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the turbolog type in the database.
	Label = "turbo_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldRaceID holds the string denoting the race_id field in the database.
	FieldRaceID = "race_id"
	// FieldLap holds the string denoting the lap field in the database.
	FieldLap = "lap"
	// FieldTimesUsed holds the string denoting the times_used field in the database.
	FieldTimesUsed = "times_used"
	// Table holds the table name of the turbolog in the database.
	Table = "turbo_logs"
)

// Columns holds all SQL columns for turbolog fields.
var Columns = []string{
	FieldID,
	FieldRacerID,
	FieldRaceID,
	FieldLap,
	FieldTimesUsed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRaceID holds the default value on creation for the "race_id" field.
	DefaultRaceID int
	// DefaultLap holds the default value on creation for the "lap" field.
	DefaultLap int
	// DefaultTimesUsed holds the default value on creation for the "times_used" field.
	DefaultTimesUsed int
)

// OrderOption defines the ordering options for the TurboLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// ByRaceID orders the results by the race_id field.
func ByRaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaceID, opts...).ToFunc()
}

// ByLap orders the results by the lap field.
func ByLap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLap, opts...).ToFunc()
}

// ByTimesUsed orders the results by the times_used field.
func ByTimesUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimesUsed, opts...).ToFunc()
}
