// Code generated by ent, DO NOT EDIT.

package turbolog

import (
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLTE(FieldID, id))
}

// RacerID applies equality check predicate on the "racer_id" field. It's identical to RacerIDEQ.
func RacerID(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldRacerID, v))
}

// RaceID applies equality check predicate on the "race_id" field. It's identical to RaceIDEQ.
func RaceID(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldRaceID, v))
}

// Lap applies equality check predicate on the "lap" field. It's identical to LapEQ.
func Lap(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldLap, v))
}

// TimesUsed applies equality check predicate on the "times_used" field. It's identical to TimesUsedEQ.
func TimesUsed(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldTimesUsed, v))
}

// RacerIDEQ applies the EQ predicate on the "racer_id" field.
func RacerIDEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldRacerID, v))
}

// RacerIDNEQ applies the NEQ predicate on the "racer_id" field.
func RacerIDNEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNEQ(FieldRacerID, v))
}

// RacerIDIn applies the In predicate on the "racer_id" field.
func RacerIDIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldIn(FieldRacerID, vs...))
}

// RacerIDNotIn applies the NotIn predicate on the "racer_id" field.
func RacerIDNotIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNotIn(FieldRacerID, vs...))
}

// RacerIDGT applies the GT predicate on the "racer_id" field.
func RacerIDGT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGT(FieldRacerID, v))
}

// RacerIDGTE applies the GTE predicate on the "racer_id" field.
func RacerIDGTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGTE(FieldRacerID, v))
}

// RacerIDLT applies the LT predicate on the "racer_id" field.
func RacerIDLT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLT(FieldRacerID, v))
}

// RacerIDLTE applies the LTE predicate on the "racer_id" field.
func RacerIDLTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLTE(FieldRacerID, v))
}

// RaceIDEQ applies the EQ predicate on the "race_id" field.
func RaceIDEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldRaceID, v))
}

// RaceIDNEQ applies the NEQ predicate on the "race_id" field.
func RaceIDNEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNEQ(FieldRaceID, v))
}

// RaceIDIn applies the In predicate on the "race_id" field.
func RaceIDIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldIn(FieldRaceID, vs...))
}

// RaceIDNotIn applies the NotIn predicate on the "race_id" field.
func RaceIDNotIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNotIn(FieldRaceID, vs...))
}

// RaceIDGT applies the GT predicate on the "race_id" field.
func RaceIDGT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGT(FieldRaceID, v))
}

// RaceIDGTE applies the GTE predicate on the "race_id" field.
func RaceIDGTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGTE(FieldRaceID, v))
}

// RaceIDLT applies the LT predicate on the "race_id" field.
func RaceIDLT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLT(FieldRaceID, v))
}

// RaceIDLTE applies the LTE predicate on the "race_id" field.
func RaceIDLTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLTE(FieldRaceID, v))
}

// LapEQ applies the EQ predicate on the "lap" field.
func LapEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldLap, v))
}

// LapNEQ applies the NEQ predicate on the "lap" field.
func LapNEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNEQ(FieldLap, v))
}

// LapIn applies the In predicate on the "lap" field.
func LapIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldIn(FieldLap, vs...))
}

// LapNotIn applies the NotIn predicate on the "lap" field.
func LapNotIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNotIn(FieldLap, vs...))
}

// LapGT applies the GT predicate on the "lap" field.
func LapGT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGT(FieldLap, v))
}

// LapGTE applies the GTE predicate on the "lap" field.
func LapGTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGTE(FieldLap, v))
}

// LapLT applies the LT predicate on the "lap" field.
func LapLT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLT(FieldLap, v))
}

// LapLTE applies the LTE predicate on the "lap" field.
func LapLTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLTE(FieldLap, v))
}

// TimesUsedEQ applies the EQ predicate on the "times_used" field.
func TimesUsedEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldEQ(FieldTimesUsed, v))
}

// TimesUsedNEQ applies the NEQ predicate on the "times_used" field.
func TimesUsedNEQ(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNEQ(FieldTimesUsed, v))
}

// TimesUsedIn applies the In predicate on the "times_used" field.
func TimesUsedIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldIn(FieldTimesUsed, vs...))
}

// TimesUsedNotIn applies the NotIn predicate on the "times_used" field.
func TimesUsedNotIn(vs ...int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldNotIn(FieldTimesUsed, vs...))
}

// TimesUsedGT applies the GT predicate on the "times_used" field.
func TimesUsedGT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGT(FieldTimesUsed, v))
}

// TimesUsedGTE applies the GTE predicate on the "times_used" field.
func TimesUsedGTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldGTE(FieldTimesUsed, v))
}

// TimesUsedLT applies the LT predicate on the "times_used" field.
func TimesUsedLT(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLT(FieldTimesUsed, v))
}

// TimesUsedLTE applies the LTE predicate on the "times_used" field.
func TimesUsedLTE(v int) predicate.TurboLog {
	return predicate.TurboLog(sql.FieldLTE(FieldTimesUsed, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TurboLog) predicate.TurboLog {
	return predicate.TurboLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TurboLog) predicate.TurboLog {
	return predicate.TurboLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TurboLog) predicate.TurboLog {
	return predicate.TurboLog(sql.NotPredicates(p))
}
