// Code generated by ent, DO NOT EDIT.

package heatcard

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the heatcard type in the database.
	Label = "heat_card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRacerID holds the string denoting the racer_id field in the database.
	FieldRacerID = "racer_id"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldCardType holds the string denoting the card_type field in the database.
	FieldCardType = "card_type"
	// FieldLapAdded holds the string denoting the lap_added field in the database.
	FieldLapAdded = "lap_added"
	// Table holds the table name of the heatcard in the database.
	Table = "heat_cards"
)

// Columns holds all SQL columns for heatcard fields.
var Columns = []string{
	FieldID,
	FieldRacerID,
	FieldLocation,
	FieldCardType,
	FieldLapAdded,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLocation holds the default value on creation for the "location" field.
	DefaultLocation string
	// DefaultCardType holds the default value on creation for the "card_type" field.
	DefaultCardType string
	// DefaultLapAdded holds the default value on creation for the "lap_added" field.
	DefaultLapAdded int
)

// OrderOption defines the ordering options for the HeatCard queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRacerID orders the results by the racer_id field.
func ByRacerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRacerID, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByCardType orders the results by the card_type field.
func ByCardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardType, opts...).ToFunc()
}

// ByLapAdded orders the results by the lap_added field.
func ByLapAdded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLapAdded, opts...).ToFunc()
}
