// Code generated by ent, DO NOT EDIT.

package heatcard

import (
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLTE(FieldID, id))
}

// RacerID applies equality check predicate on the "racer_id" field. It's identical to RacerIDEQ.
func RacerID(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldRacerID, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldLocation, v))
}

// CardType applies equality check predicate on the "card_type" field. It's identical to CardTypeEQ.
func CardType(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldCardType, v))
}

// LapAdded applies equality check predicate on the "lap_added" field. It's identical to LapAddedEQ.
func LapAdded(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldLapAdded, v))
}

// RacerIDEQ applies the EQ predicate on the "racer_id" field.
func RacerIDEQ(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldRacerID, v))
}

// RacerIDNEQ applies the NEQ predicate on the "racer_id" field.
func RacerIDNEQ(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNEQ(FieldRacerID, v))
}

// RacerIDIn applies the In predicate on the "racer_id" field.
func RacerIDIn(vs ...int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldIn(FieldRacerID, vs...))
}

// RacerIDNotIn applies the NotIn predicate on the "racer_id" field.
func RacerIDNotIn(vs ...int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNotIn(FieldRacerID, vs...))
}

// RacerIDGT applies the GT predicate on the "racer_id" field.
func RacerIDGT(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGT(FieldRacerID, v))
}

// RacerIDGTE applies the GTE predicate on the "racer_id" field.
func RacerIDGTE(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGTE(FieldRacerID, v))
}

// RacerIDLT applies the LT predicate on the "racer_id" field.
func RacerIDLT(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLT(FieldRacerID, v))
}

// RacerIDLTE applies the LTE predicate on the "racer_id" field.
func RacerIDLTE(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLTE(FieldRacerID, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldContainsFold(FieldLocation, v))
}

// CardTypeEQ applies the EQ predicate on the "card_type" field.
func CardTypeEQ(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldCardType, v))
}

// CardTypeNEQ applies the NEQ predicate on the "card_type" field.
func CardTypeNEQ(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNEQ(FieldCardType, v))
}

// CardTypeIn applies the In predicate on the "card_type" field.
func CardTypeIn(vs ...string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldIn(FieldCardType, vs...))
}

// CardTypeNotIn applies the NotIn predicate on the "card_type" field.
func CardTypeNotIn(vs ...string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNotIn(FieldCardType, vs...))
}

// CardTypeGT applies the GT predicate on the "card_type" field.
func CardTypeGT(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGT(FieldCardType, v))
}

// CardTypeGTE applies the GTE predicate on the "card_type" field.
func CardTypeGTE(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGTE(FieldCardType, v))
}

// CardTypeLT applies the LT predicate on the "card_type" field.
func CardTypeLT(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLT(FieldCardType, v))
}

// CardTypeLTE applies the LTE predicate on the "card_type" field.
func CardTypeLTE(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLTE(FieldCardType, v))
}

// CardTypeContains applies the Contains predicate on the "card_type" field.
func CardTypeContains(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldContains(FieldCardType, v))
}

// CardTypeHasPrefix applies the HasPrefix predicate on the "card_type" field.
func CardTypeHasPrefix(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldHasPrefix(FieldCardType, v))
}

// CardTypeHasSuffix applies the HasSuffix predicate on the "card_type" field.
func CardTypeHasSuffix(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldHasSuffix(FieldCardType, v))
}

// CardTypeEqualFold applies the EqualFold predicate on the "card_type" field.
func CardTypeEqualFold(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEqualFold(FieldCardType, v))
}

// CardTypeContainsFold applies the ContainsFold predicate on the "card_type" field.
func CardTypeContainsFold(v string) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldContainsFold(FieldCardType, v))
}

// LapAddedEQ applies the EQ predicate on the "lap_added" field.
func LapAddedEQ(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldEQ(FieldLapAdded, v))
}

// LapAddedNEQ applies the NEQ predicate on the "lap_added" field.
func LapAddedNEQ(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNEQ(FieldLapAdded, v))
}

// LapAddedIn applies the In predicate on the "lap_added" field.
func LapAddedIn(vs ...int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldIn(FieldLapAdded, vs...))
}

// LapAddedNotIn applies the NotIn predicate on the "lap_added" field.
func LapAddedNotIn(vs ...int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldNotIn(FieldLapAdded, vs...))
}

// LapAddedGT applies the GT predicate on the "lap_added" field.
func LapAddedGT(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGT(FieldLapAdded, v))
}

// LapAddedGTE applies the GTE predicate on the "lap_added" field.
func LapAddedGTE(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldGTE(FieldLapAdded, v))
}

// LapAddedLT applies the LT predicate on the "lap_added" field.
func LapAddedLT(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLT(FieldLapAdded, v))
}

// LapAddedLTE applies the LTE predicate on the "lap_added" field.
func LapAddedLTE(v int) predicate.HeatCard {
	return predicate.HeatCard(sql.FieldLTE(FieldLapAdded, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HeatCard) predicate.HeatCard {
	return predicate.HeatCard(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HeatCard) predicate.HeatCard {
	return predicate.HeatCard(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HeatCard) predicate.HeatCard {
	return predicate.HeatCard(sql.NotPredicates(p))
}
