package db

import (
	"log"

	"heat/models"
)

func SeedUpgrades() {
	var count int
	srv.DB.QueryRow("SELECT COUNT(*) FROM upgrade_cards").Scan(&count)
	if count > 0 {
		return
	}
	upgrades := []models.UpgradeCard{
		{Name: "Racing Gearbox", Description: "Shift one gear higher without adding heat", CardType: "upgrade", Cost: 3, Effects: "{\"gear_bonus\":1}"},
		{Name: "Lightweight Chassis", Description: "Reduce heat generated by 1 per corner", CardType: "upgrade", Cost: 4, Effects: "{\"heat_reduction\":1}"},
		{Name: "High-RPM Engine", Description: "+1 speed on straights", CardType: "upgrade", Cost: 5, Effects: "{\"straight_speed\":1}"},
		{Name: "Cooling System", Description: "Discard 1 extra heat card per cooldown", CardType: "upgrade", Cost: 3, Effects: "{\"cooldown_bonus\":1}"},
		{Name: "Reinforced Brakes", Description: "Reduce stress from braking by 1", CardType: "upgrade", Cost: 2, Effects: "{\"brake_stress_reduction\":1}"},
		{Name: "Aerodynamic Kit", Description: "Better cornering, add +1 to corner speed", CardType: "upgrade", Cost: 4, Effects: "{\"corner_speed\":1}"},
		{Name: "Quick Shifter", Description: "Once per race, shift without adding stress", CardType: "upgrade", Cost: 3, Effects: "{\"free_shift\":1}"},
		{Name: "Turbo Charger", Description: "Extra turbo boost per race", CardType: "upgrade", Cost: 5, Effects: "{\"extra_turbo\":1}"},
	}
	for _, u := range upgrades {
		srv.DB.Exec("INSERT INTO upgrade_cards (name, description, card_type, cost, effects, extension_id) VALUES (?, ?, ?, ?, ?, 1)",
			u.Name, u.Description, u.CardType, u.Cost, u.Effects)
	}
	log.Printf("[DB] Seeded %d upgrade cards", len(upgrades))
}

func SeedLegendAbilities() {
	var count int
	srv.DB.QueryRow("SELECT COUNT(*) FROM legend_abilities").Scan(&count)
	if count > 0 {
		return
	}
	abilities := []models.LegendAbility{
		{Name: "Perfect Start", Description: "Gain +1 position on the first lap", AbilityType: "start", RacerName: "A. PROST"},
		{Name: "Rain Master", Description: "No speed penalty in wet conditions", AbilityType: "weather", RacerName: "M. SCHUMACHER"},
		{Name: "Aggressive Overtake", Description: "+1 overtake attempt per race", AbilityType: "overtake", RacerName: "A. SENNA"},
		{Name: "Consistent Performer", Description: "Reduce stress accumulation by 1 each lap", AbilityType: "consistency", RacerName: "N. LAUDA"},
		{Name: "Smooth Operator", Description: "Generate 1 less heat per gear shift", AbilityType: "smoothness", RacerName: "J. STEWART"},
	}
	for _, a := range abilities {
		srv.DB.Exec("INSERT INTO legend_abilities (name, description, ability_type, racer_name, extension_id) VALUES (?, ?, ?, ?, 1)",
			a.Name, a.Description, a.AbilityType, a.RacerName)
	}
	log.Printf("[DB] Seeded %d legend abilities", len(abilities))
}

func SeedSectors() {
	var count int
	srv.DB.QueryRow("SELECT COUNT(*) FROM sectors").Scan(&count)
	if count > 0 {
		return
	}
	trackSectors := map[string][]string{
		"monza":       {"Start/Finish", "Lesmo 1", "Lesmo 2", "Ascari", "Parabolica"},
		"spa":         {"Start/Finish", "Eau Rouge", "Raidillon", "Les Combes", "Pouhon", "Stavelot", "Blanchimont"},
		"silverstone": {"Start/Finish", "Copse", "Maggots-Becketts", "Stowe", "Village", "Club"},
		"monaco":      {"Start/Finish", "Casino", "Mirabeau", "Loews", "Portier", "Tunnel", "Nouvelle", "Rascasse"},
		"interlagos":  {"Start/Finish", "Senna S", "Descida", "Curva do Lago", "Ferradura", "Juncao"},
	}
	for trackID, sectors := range trackSectors {
		for i, name := range sectors {
			srv.DB.Exec("INSERT INTO sectors (name, track_id, \"order\") VALUES (?, ?, ?)",
				name, trackID, i+1)
		}
	}
	log.Printf("[DB] Seeded sectors")
}
