// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/aisetting"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AISetting is the model entity for the AISetting schema.
type AISetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TrackExtractURL holds the value of the "track_extract_url" field.
	TrackExtractURL string `json:"track_extract_url,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey string `json:"api_key,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled int `json:"enabled,omitempty"`
	// Difficulty holds the value of the "difficulty" field.
	Difficulty string `json:"difficulty,omitempty"`
	// Aggression holds the value of the "aggression" field.
	Aggression int `json:"aggression,omitempty"`
	// ErrorRate holds the value of the "error_rate" field.
	ErrorRate int `json:"error_rate,omitempty"`
	// Consistency holds the value of the "consistency" field.
	Consistency  int `json:"consistency,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AISetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aisetting.FieldID, aisetting.FieldEnabled, aisetting.FieldAggression, aisetting.FieldErrorRate, aisetting.FieldConsistency:
			values[i] = new(sql.NullInt64)
		case aisetting.FieldTrackExtractURL, aisetting.FieldAPIKey, aisetting.FieldDifficulty:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AISetting fields.
func (_m *AISetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aisetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aisetting.FieldTrackExtractURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field track_extract_url", values[i])
			} else if value.Valid {
				_m.TrackExtractURL = value.String
			}
		case aisetting.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				_m.APIKey = value.String
			}
		case aisetting.FieldEnabled:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = int(value.Int64)
			}
		case aisetting.FieldDifficulty:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field difficulty", values[i])
			} else if value.Valid {
				_m.Difficulty = value.String
			}
		case aisetting.FieldAggression:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field aggression", values[i])
			} else if value.Valid {
				_m.Aggression = int(value.Int64)
			}
		case aisetting.FieldErrorRate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_rate", values[i])
			} else if value.Valid {
				_m.ErrorRate = int(value.Int64)
			}
		case aisetting.FieldConsistency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consistency", values[i])
			} else if value.Valid {
				_m.Consistency = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AISetting.
// This includes values selected through modifiers, order, etc.
func (_m *AISetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AISetting.
// Note that you need to call AISetting.Unwrap() before calling this method if this AISetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AISetting) Update() *AISettingUpdateOne {
	return NewAISettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AISetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AISetting) Unwrap() *AISetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AISetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AISetting) String() string {
	var builder strings.Builder
	builder.WriteString("AISetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("track_extract_url=")
	builder.WriteString(_m.TrackExtractURL)
	builder.WriteString(", ")
	builder.WriteString("api_key=")
	builder.WriteString(_m.APIKey)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("difficulty=")
	builder.WriteString(_m.Difficulty)
	builder.WriteString(", ")
	builder.WriteString("aggression=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aggression))
	builder.WriteString(", ")
	builder.WriteString("error_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorRate))
	builder.WriteString(", ")
	builder.WriteString("consistency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Consistency))
	builder.WriteByte(')')
	return builder.String()
}

// AISettings is a parsable slice of AISetting.
type AISettings []*AISetting
