// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/emailsetting"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailSettingCreate is the builder for creating a EmailSetting entity.
type EmailSettingCreate struct {
	config
	mutation *EmailSettingMutation
	hooks    []Hook
}

// SetSMTPHost sets the "smtp_host" field.
func (_c *EmailSettingCreate) SetSMTPHost(v string) *EmailSettingCreate {
	_c.mutation.SetSMTPHost(v)
	return _c
}

// SetNillableSMTPHost sets the "smtp_host" field if the given value is not nil.
func (_c *EmailSettingCreate) SetNillableSMTPHost(v *string) *EmailSettingCreate {
	if v != nil {
		_c.SetSMTPHost(*v)
	}
	return _c
}

// SetSMTPPort sets the "smtp_port" field.
func (_c *EmailSettingCreate) SetSMTPPort(v int) *EmailSettingCreate {
	_c.mutation.SetSMTPPort(v)
	return _c
}

// SetNillableSMTPPort sets the "smtp_port" field if the given value is not nil.
func (_c *EmailSettingCreate) SetNillableSMTPPort(v *int) *EmailSettingCreate {
	if v != nil {
		_c.SetSMTPPort(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *EmailSettingCreate) SetUsername(v string) *EmailSettingCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *EmailSettingCreate) SetNillableUsername(v *string) *EmailSettingCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *EmailSettingCreate) SetPassword(v string) *EmailSettingCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *EmailSettingCreate) SetNillablePassword(v *string) *EmailSettingCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetFromAddr sets the "from_addr" field.
func (_c *EmailSettingCreate) SetFromAddr(v string) *EmailSettingCreate {
	_c.mutation.SetFromAddr(v)
	return _c
}

// SetNillableFromAddr sets the "from_addr" field if the given value is not nil.
func (_c *EmailSettingCreate) SetNillableFromAddr(v *string) *EmailSettingCreate {
	if v != nil {
		_c.SetFromAddr(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *EmailSettingCreate) SetEnabled(v int) *EmailSettingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *EmailSettingCreate) SetNillableEnabled(v *int) *EmailSettingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EmailSettingCreate) SetID(v int) *EmailSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EmailSettingMutation object of the builder.
func (_c *EmailSettingCreate) Mutation() *EmailSettingMutation {
	return _c.mutation
}

// Save creates the EmailSetting in the database.
func (_c *EmailSettingCreate) Save(ctx context.Context) (*EmailSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailSettingCreate) SaveX(ctx context.Context) *EmailSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailSettingCreate) defaults() {
	if _, ok := _c.mutation.SMTPPort(); !ok {
		v := emailsetting.DefaultSMTPPort
		_c.mutation.SetSMTPPort(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := emailsetting.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailSettingCreate) check() error {
	if _, ok := _c.mutation.SMTPPort(); !ok {
		return &ValidationError{Name: "smtp_port", err: errors.New(`ent: missing required field "EmailSetting.smtp_port"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "EmailSetting.enabled"`)}
	}
	return nil
}

func (_c *EmailSettingCreate) sqlSave(ctx context.Context) (*EmailSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailSettingCreate) createSpec() (*EmailSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailsetting.Table, sqlgraph.NewFieldSpec(emailsetting.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SMTPHost(); ok {
		_spec.SetField(emailsetting.FieldSMTPHost, field.TypeString, value)
		_node.SMTPHost = value
	}
	if value, ok := _c.mutation.SMTPPort(); ok {
		_spec.SetField(emailsetting.FieldSMTPPort, field.TypeInt, value)
		_node.SMTPPort = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(emailsetting.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(emailsetting.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.FromAddr(); ok {
		_spec.SetField(emailsetting.FieldFromAddr, field.TypeString, value)
		_node.FromAddr = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(emailsetting.FieldEnabled, field.TypeInt, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// EmailSettingCreateBulk is the builder for creating many EmailSetting entities in bulk.
type EmailSettingCreateBulk struct {
	config
	err      error
	builders []*EmailSettingCreate
}

// Save creates the EmailSetting entities in the database.
func (_c *EmailSettingCreateBulk) Save(ctx context.Context) ([]*EmailSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailSettingCreateBulk) SaveX(ctx context.Context) []*EmailSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
