// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/emailsetting"
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailSettingUpdate is the builder for updating EmailSetting entities.
type EmailSettingUpdate struct {
	config
	hooks    []Hook
	mutation *EmailSettingMutation
}

// Where appends a list predicates to the EmailSettingUpdate builder.
func (_u *EmailSettingUpdate) Where(ps ...predicate.EmailSetting) *EmailSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSMTPHost sets the "smtp_host" field.
func (_u *EmailSettingUpdate) SetSMTPHost(v string) *EmailSettingUpdate {
	_u.mutation.SetSMTPHost(v)
	return _u
}

// SetNillableSMTPHost sets the "smtp_host" field if the given value is not nil.
func (_u *EmailSettingUpdate) SetNillableSMTPHost(v *string) *EmailSettingUpdate {
	if v != nil {
		_u.SetSMTPHost(*v)
	}
	return _u
}

// ClearSMTPHost clears the value of the "smtp_host" field.
func (_u *EmailSettingUpdate) ClearSMTPHost() *EmailSettingUpdate {
	_u.mutation.ClearSMTPHost()
	return _u
}

// SetSMTPPort sets the "smtp_port" field.
func (_u *EmailSettingUpdate) SetSMTPPort(v int) *EmailSettingUpdate {
	_u.mutation.ResetSMTPPort()
	_u.mutation.SetSMTPPort(v)
	return _u
}

// SetNillableSMTPPort sets the "smtp_port" field if the given value is not nil.
func (_u *EmailSettingUpdate) SetNillableSMTPPort(v *int) *EmailSettingUpdate {
	if v != nil {
		_u.SetSMTPPort(*v)
	}
	return _u
}

// AddSMTPPort adds value to the "smtp_port" field.
func (_u *EmailSettingUpdate) AddSMTPPort(v int) *EmailSettingUpdate {
	_u.mutation.AddSMTPPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *EmailSettingUpdate) SetUsername(v string) *EmailSettingUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *EmailSettingUpdate) SetNillableUsername(v *string) *EmailSettingUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *EmailSettingUpdate) ClearUsername() *EmailSettingUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *EmailSettingUpdate) SetPassword(v string) *EmailSettingUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *EmailSettingUpdate) SetNillablePassword(v *string) *EmailSettingUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *EmailSettingUpdate) ClearPassword() *EmailSettingUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetFromAddr sets the "from_addr" field.
func (_u *EmailSettingUpdate) SetFromAddr(v string) *EmailSettingUpdate {
	_u.mutation.SetFromAddr(v)
	return _u
}

// SetNillableFromAddr sets the "from_addr" field if the given value is not nil.
func (_u *EmailSettingUpdate) SetNillableFromAddr(v *string) *EmailSettingUpdate {
	if v != nil {
		_u.SetFromAddr(*v)
	}
	return _u
}

// ClearFromAddr clears the value of the "from_addr" field.
func (_u *EmailSettingUpdate) ClearFromAddr() *EmailSettingUpdate {
	_u.mutation.ClearFromAddr()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EmailSettingUpdate) SetEnabled(v int) *EmailSettingUpdate {
	_u.mutation.ResetEnabled()
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EmailSettingUpdate) SetNillableEnabled(v *int) *EmailSettingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddEnabled adds value to the "enabled" field.
func (_u *EmailSettingUpdate) AddEnabled(v int) *EmailSettingUpdate {
	_u.mutation.AddEnabled(v)
	return _u
}

// Mutation returns the EmailSettingMutation object of the builder.
func (_u *EmailSettingUpdate) Mutation() *EmailSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmailSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(emailsetting.Table, emailsetting.Columns, sqlgraph.NewFieldSpec(emailsetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SMTPHost(); ok {
		_spec.SetField(emailsetting.FieldSMTPHost, field.TypeString, value)
	}
	if _u.mutation.SMTPHostCleared() {
		_spec.ClearField(emailsetting.FieldSMTPHost, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPPort(); ok {
		_spec.SetField(emailsetting.FieldSMTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSMTPPort(); ok {
		_spec.AddField(emailsetting.FieldSMTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(emailsetting.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(emailsetting.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(emailsetting.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(emailsetting.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.FromAddr(); ok {
		_spec.SetField(emailsetting.FieldFromAddr, field.TypeString, value)
	}
	if _u.mutation.FromAddrCleared() {
		_spec.ClearField(emailsetting.FieldFromAddr, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(emailsetting.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnabled(); ok {
		_spec.AddField(emailsetting.FieldEnabled, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailSettingUpdateOne is the builder for updating a single EmailSetting entity.
type EmailSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailSettingMutation
}

// SetSMTPHost sets the "smtp_host" field.
func (_u *EmailSettingUpdateOne) SetSMTPHost(v string) *EmailSettingUpdateOne {
	_u.mutation.SetSMTPHost(v)
	return _u
}

// SetNillableSMTPHost sets the "smtp_host" field if the given value is not nil.
func (_u *EmailSettingUpdateOne) SetNillableSMTPHost(v *string) *EmailSettingUpdateOne {
	if v != nil {
		_u.SetSMTPHost(*v)
	}
	return _u
}

// ClearSMTPHost clears the value of the "smtp_host" field.
func (_u *EmailSettingUpdateOne) ClearSMTPHost() *EmailSettingUpdateOne {
	_u.mutation.ClearSMTPHost()
	return _u
}

// SetSMTPPort sets the "smtp_port" field.
func (_u *EmailSettingUpdateOne) SetSMTPPort(v int) *EmailSettingUpdateOne {
	_u.mutation.ResetSMTPPort()
	_u.mutation.SetSMTPPort(v)
	return _u
}

// SetNillableSMTPPort sets the "smtp_port" field if the given value is not nil.
func (_u *EmailSettingUpdateOne) SetNillableSMTPPort(v *int) *EmailSettingUpdateOne {
	if v != nil {
		_u.SetSMTPPort(*v)
	}
	return _u
}

// AddSMTPPort adds value to the "smtp_port" field.
func (_u *EmailSettingUpdateOne) AddSMTPPort(v int) *EmailSettingUpdateOne {
	_u.mutation.AddSMTPPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *EmailSettingUpdateOne) SetUsername(v string) *EmailSettingUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *EmailSettingUpdateOne) SetNillableUsername(v *string) *EmailSettingUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *EmailSettingUpdateOne) ClearUsername() *EmailSettingUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *EmailSettingUpdateOne) SetPassword(v string) *EmailSettingUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *EmailSettingUpdateOne) SetNillablePassword(v *string) *EmailSettingUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *EmailSettingUpdateOne) ClearPassword() *EmailSettingUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetFromAddr sets the "from_addr" field.
func (_u *EmailSettingUpdateOne) SetFromAddr(v string) *EmailSettingUpdateOne {
	_u.mutation.SetFromAddr(v)
	return _u
}

// SetNillableFromAddr sets the "from_addr" field if the given value is not nil.
func (_u *EmailSettingUpdateOne) SetNillableFromAddr(v *string) *EmailSettingUpdateOne {
	if v != nil {
		_u.SetFromAddr(*v)
	}
	return _u
}

// ClearFromAddr clears the value of the "from_addr" field.
func (_u *EmailSettingUpdateOne) ClearFromAddr() *EmailSettingUpdateOne {
	_u.mutation.ClearFromAddr()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EmailSettingUpdateOne) SetEnabled(v int) *EmailSettingUpdateOne {
	_u.mutation.ResetEnabled()
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EmailSettingUpdateOne) SetNillableEnabled(v *int) *EmailSettingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddEnabled adds value to the "enabled" field.
func (_u *EmailSettingUpdateOne) AddEnabled(v int) *EmailSettingUpdateOne {
	_u.mutation.AddEnabled(v)
	return _u
}

// Mutation returns the EmailSettingMutation object of the builder.
func (_u *EmailSettingUpdateOne) Mutation() *EmailSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailSettingUpdate builder.
func (_u *EmailSettingUpdateOne) Where(ps ...predicate.EmailSetting) *EmailSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailSettingUpdateOne) Select(field string, fields ...string) *EmailSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailSetting entity.
func (_u *EmailSettingUpdateOne) Save(ctx context.Context) (*EmailSetting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSettingUpdateOne) SaveX(ctx context.Context) *EmailSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmailSettingUpdateOne) sqlSave(ctx context.Context) (_node *EmailSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(emailsetting.Table, emailsetting.Columns, sqlgraph.NewFieldSpec(emailsetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailsetting.FieldID)
		for _, f := range fields {
			if !emailsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SMTPHost(); ok {
		_spec.SetField(emailsetting.FieldSMTPHost, field.TypeString, value)
	}
	if _u.mutation.SMTPHostCleared() {
		_spec.ClearField(emailsetting.FieldSMTPHost, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPPort(); ok {
		_spec.SetField(emailsetting.FieldSMTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSMTPPort(); ok {
		_spec.AddField(emailsetting.FieldSMTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(emailsetting.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(emailsetting.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(emailsetting.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(emailsetting.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.FromAddr(); ok {
		_spec.SetField(emailsetting.FieldFromAddr, field.TypeString, value)
	}
	if _u.mutation.FromAddrCleared() {
		_spec.ClearField(emailsetting.FieldFromAddr, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(emailsetting.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnabled(); ok {
		_spec.AddField(emailsetting.FieldEnabled, field.TypeInt, value)
	}
	_node = &EmailSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
