// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/gearshift"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GearShift is the model entity for the GearShift schema.
type GearShift struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RacerID holds the value of the "racer_id" field.
	RacerID int `json:"racer_id,omitempty"`
	// RaceID holds the value of the "race_id" field.
	RaceID int `json:"race_id,omitempty"`
	// Lap holds the value of the "lap" field.
	Lap int `json:"lap,omitempty"`
	// Gear holds the value of the "gear" field.
	Gear int `json:"gear,omitempty"`
	// Stress holds the value of the "stress" field.
	Stress       int `json:"stress,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GearShift) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gearshift.FieldID, gearshift.FieldRacerID, gearshift.FieldRaceID, gearshift.FieldLap, gearshift.FieldGear, gearshift.FieldStress:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GearShift fields.
func (_m *GearShift) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gearshift.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gearshift.FieldRacerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field racer_id", values[i])
			} else if value.Valid {
				_m.RacerID = int(value.Int64)
			}
		case gearshift.FieldRaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field race_id", values[i])
			} else if value.Valid {
				_m.RaceID = int(value.Int64)
			}
		case gearshift.FieldLap:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lap", values[i])
			} else if value.Valid {
				_m.Lap = int(value.Int64)
			}
		case gearshift.FieldGear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gear", values[i])
			} else if value.Valid {
				_m.Gear = int(value.Int64)
			}
		case gearshift.FieldStress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stress", values[i])
			} else if value.Valid {
				_m.Stress = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GearShift.
// This includes values selected through modifiers, order, etc.
func (_m *GearShift) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GearShift.
// Note that you need to call GearShift.Unwrap() before calling this method if this GearShift
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GearShift) Update() *GearShiftUpdateOne {
	return NewGearShiftClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GearShift entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GearShift) Unwrap() *GearShift {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GearShift is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GearShift) String() string {
	var builder strings.Builder
	builder.WriteString("GearShift(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("racer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RacerID))
	builder.WriteString(", ")
	builder.WriteString("race_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RaceID))
	builder.WriteString(", ")
	builder.WriteString("lap=")
	builder.WriteString(fmt.Sprintf("%v", _m.Lap))
	builder.WriteString(", ")
	builder.WriteString("gear=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gear))
	builder.WriteString(", ")
	builder.WriteString("stress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stress))
	builder.WriteByte(')')
	return builder.String()
}

// GearShifts is a parsable slice of GearShift.
type GearShifts []*GearShift
