// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/gearshift"
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GearShiftUpdate is the builder for updating GearShift entities.
type GearShiftUpdate struct {
	config
	hooks    []Hook
	mutation *GearShiftMutation
}

// Where appends a list predicates to the GearShiftUpdate builder.
func (_u *GearShiftUpdate) Where(ps ...predicate.GearShift) *GearShiftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRacerID sets the "racer_id" field.
func (_u *GearShiftUpdate) SetRacerID(v int) *GearShiftUpdate {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *GearShiftUpdate) SetNillableRacerID(v *int) *GearShiftUpdate {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *GearShiftUpdate) AddRacerID(v int) *GearShiftUpdate {
	_u.mutation.AddRacerID(v)
	return _u
}

// SetRaceID sets the "race_id" field.
func (_u *GearShiftUpdate) SetRaceID(v int) *GearShiftUpdate {
	_u.mutation.ResetRaceID()
	_u.mutation.SetRaceID(v)
	return _u
}

// SetNillableRaceID sets the "race_id" field if the given value is not nil.
func (_u *GearShiftUpdate) SetNillableRaceID(v *int) *GearShiftUpdate {
	if v != nil {
		_u.SetRaceID(*v)
	}
	return _u
}

// AddRaceID adds value to the "race_id" field.
func (_u *GearShiftUpdate) AddRaceID(v int) *GearShiftUpdate {
	_u.mutation.AddRaceID(v)
	return _u
}

// SetLap sets the "lap" field.
func (_u *GearShiftUpdate) SetLap(v int) *GearShiftUpdate {
	_u.mutation.ResetLap()
	_u.mutation.SetLap(v)
	return _u
}

// SetNillableLap sets the "lap" field if the given value is not nil.
func (_u *GearShiftUpdate) SetNillableLap(v *int) *GearShiftUpdate {
	if v != nil {
		_u.SetLap(*v)
	}
	return _u
}

// AddLap adds value to the "lap" field.
func (_u *GearShiftUpdate) AddLap(v int) *GearShiftUpdate {
	_u.mutation.AddLap(v)
	return _u
}

// SetGear sets the "gear" field.
func (_u *GearShiftUpdate) SetGear(v int) *GearShiftUpdate {
	_u.mutation.ResetGear()
	_u.mutation.SetGear(v)
	return _u
}

// SetNillableGear sets the "gear" field if the given value is not nil.
func (_u *GearShiftUpdate) SetNillableGear(v *int) *GearShiftUpdate {
	if v != nil {
		_u.SetGear(*v)
	}
	return _u
}

// AddGear adds value to the "gear" field.
func (_u *GearShiftUpdate) AddGear(v int) *GearShiftUpdate {
	_u.mutation.AddGear(v)
	return _u
}

// SetStress sets the "stress" field.
func (_u *GearShiftUpdate) SetStress(v int) *GearShiftUpdate {
	_u.mutation.ResetStress()
	_u.mutation.SetStress(v)
	return _u
}

// SetNillableStress sets the "stress" field if the given value is not nil.
func (_u *GearShiftUpdate) SetNillableStress(v *int) *GearShiftUpdate {
	if v != nil {
		_u.SetStress(*v)
	}
	return _u
}

// AddStress adds value to the "stress" field.
func (_u *GearShiftUpdate) AddStress(v int) *GearShiftUpdate {
	_u.mutation.AddStress(v)
	return _u
}

// Mutation returns the GearShiftMutation object of the builder.
func (_u *GearShiftUpdate) Mutation() *GearShiftMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GearShiftUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GearShiftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GearShiftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GearShiftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GearShiftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gearshift.Table, gearshift.Columns, sqlgraph.NewFieldSpec(gearshift.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(gearshift.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(gearshift.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RaceID(); ok {
		_spec.SetField(gearshift.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRaceID(); ok {
		_spec.AddField(gearshift.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Lap(); ok {
		_spec.SetField(gearshift.FieldLap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLap(); ok {
		_spec.AddField(gearshift.FieldLap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Gear(); ok {
		_spec.SetField(gearshift.FieldGear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGear(); ok {
		_spec.AddField(gearshift.FieldGear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stress(); ok {
		_spec.SetField(gearshift.FieldStress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStress(); ok {
		_spec.AddField(gearshift.FieldStress, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gearshift.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GearShiftUpdateOne is the builder for updating a single GearShift entity.
type GearShiftUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GearShiftMutation
}

// SetRacerID sets the "racer_id" field.
func (_u *GearShiftUpdateOne) SetRacerID(v int) *GearShiftUpdateOne {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *GearShiftUpdateOne) SetNillableRacerID(v *int) *GearShiftUpdateOne {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *GearShiftUpdateOne) AddRacerID(v int) *GearShiftUpdateOne {
	_u.mutation.AddRacerID(v)
	return _u
}

// SetRaceID sets the "race_id" field.
func (_u *GearShiftUpdateOne) SetRaceID(v int) *GearShiftUpdateOne {
	_u.mutation.ResetRaceID()
	_u.mutation.SetRaceID(v)
	return _u
}

// SetNillableRaceID sets the "race_id" field if the given value is not nil.
func (_u *GearShiftUpdateOne) SetNillableRaceID(v *int) *GearShiftUpdateOne {
	if v != nil {
		_u.SetRaceID(*v)
	}
	return _u
}

// AddRaceID adds value to the "race_id" field.
func (_u *GearShiftUpdateOne) AddRaceID(v int) *GearShiftUpdateOne {
	_u.mutation.AddRaceID(v)
	return _u
}

// SetLap sets the "lap" field.
func (_u *GearShiftUpdateOne) SetLap(v int) *GearShiftUpdateOne {
	_u.mutation.ResetLap()
	_u.mutation.SetLap(v)
	return _u
}

// SetNillableLap sets the "lap" field if the given value is not nil.
func (_u *GearShiftUpdateOne) SetNillableLap(v *int) *GearShiftUpdateOne {
	if v != nil {
		_u.SetLap(*v)
	}
	return _u
}

// AddLap adds value to the "lap" field.
func (_u *GearShiftUpdateOne) AddLap(v int) *GearShiftUpdateOne {
	_u.mutation.AddLap(v)
	return _u
}

// SetGear sets the "gear" field.
func (_u *GearShiftUpdateOne) SetGear(v int) *GearShiftUpdateOne {
	_u.mutation.ResetGear()
	_u.mutation.SetGear(v)
	return _u
}

// SetNillableGear sets the "gear" field if the given value is not nil.
func (_u *GearShiftUpdateOne) SetNillableGear(v *int) *GearShiftUpdateOne {
	if v != nil {
		_u.SetGear(*v)
	}
	return _u
}

// AddGear adds value to the "gear" field.
func (_u *GearShiftUpdateOne) AddGear(v int) *GearShiftUpdateOne {
	_u.mutation.AddGear(v)
	return _u
}

// SetStress sets the "stress" field.
func (_u *GearShiftUpdateOne) SetStress(v int) *GearShiftUpdateOne {
	_u.mutation.ResetStress()
	_u.mutation.SetStress(v)
	return _u
}

// SetNillableStress sets the "stress" field if the given value is not nil.
func (_u *GearShiftUpdateOne) SetNillableStress(v *int) *GearShiftUpdateOne {
	if v != nil {
		_u.SetStress(*v)
	}
	return _u
}

// AddStress adds value to the "stress" field.
func (_u *GearShiftUpdateOne) AddStress(v int) *GearShiftUpdateOne {
	_u.mutation.AddStress(v)
	return _u
}

// Mutation returns the GearShiftMutation object of the builder.
func (_u *GearShiftUpdateOne) Mutation() *GearShiftMutation {
	return _u.mutation
}

// Where appends a list predicates to the GearShiftUpdate builder.
func (_u *GearShiftUpdateOne) Where(ps ...predicate.GearShift) *GearShiftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GearShiftUpdateOne) Select(field string, fields ...string) *GearShiftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GearShift entity.
func (_u *GearShiftUpdateOne) Save(ctx context.Context) (*GearShift, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GearShiftUpdateOne) SaveX(ctx context.Context) *GearShift {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GearShiftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GearShiftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GearShiftUpdateOne) sqlSave(ctx context.Context) (_node *GearShift, err error) {
	_spec := sqlgraph.NewUpdateSpec(gearshift.Table, gearshift.Columns, sqlgraph.NewFieldSpec(gearshift.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GearShift.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gearshift.FieldID)
		for _, f := range fields {
			if !gearshift.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gearshift.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(gearshift.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(gearshift.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RaceID(); ok {
		_spec.SetField(gearshift.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRaceID(); ok {
		_spec.AddField(gearshift.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Lap(); ok {
		_spec.SetField(gearshift.FieldLap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLap(); ok {
		_spec.AddField(gearshift.FieldLap, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Gear(); ok {
		_spec.SetField(gearshift.FieldGear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGear(); ok {
		_spec.AddField(gearshift.FieldGear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stress(); ok {
		_spec.SetField(gearshift.FieldStress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStress(); ok {
		_spec.AddField(gearshift.FieldStress, field.TypeInt, value)
	}
	_node = &GearShift{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gearshift.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
