// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/heatcard"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// HeatCard is the model entity for the HeatCard schema.
type HeatCard struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RacerID holds the value of the "racer_id" field.
	RacerID int `json:"racer_id,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// CardType holds the value of the "card_type" field.
	CardType string `json:"card_type,omitempty"`
	// LapAdded holds the value of the "lap_added" field.
	LapAdded     int `json:"lap_added,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HeatCard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case heatcard.FieldID, heatcard.FieldRacerID, heatcard.FieldLapAdded:
			values[i] = new(sql.NullInt64)
		case heatcard.FieldLocation, heatcard.FieldCardType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HeatCard fields.
func (_m *HeatCard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case heatcard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case heatcard.FieldRacerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field racer_id", values[i])
			} else if value.Valid {
				_m.RacerID = int(value.Int64)
			}
		case heatcard.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = value.String
			}
		case heatcard.FieldCardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field card_type", values[i])
			} else if value.Valid {
				_m.CardType = value.String
			}
		case heatcard.FieldLapAdded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lap_added", values[i])
			} else if value.Valid {
				_m.LapAdded = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HeatCard.
// This includes values selected through modifiers, order, etc.
func (_m *HeatCard) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this HeatCard.
// Note that you need to call HeatCard.Unwrap() before calling this method if this HeatCard
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HeatCard) Update() *HeatCardUpdateOne {
	return NewHeatCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HeatCard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HeatCard) Unwrap() *HeatCard {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HeatCard is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HeatCard) String() string {
	var builder strings.Builder
	builder.WriteString("HeatCard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("racer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RacerID))
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(_m.Location)
	builder.WriteString(", ")
	builder.WriteString("card_type=")
	builder.WriteString(_m.CardType)
	builder.WriteString(", ")
	builder.WriteString("lap_added=")
	builder.WriteString(fmt.Sprintf("%v", _m.LapAdded))
	builder.WriteByte(')')
	return builder.String()
}

// HeatCards is a parsable slice of HeatCard.
type HeatCards []*HeatCard
