// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/heatcard"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HeatCardCreate is the builder for creating a HeatCard entity.
type HeatCardCreate struct {
	config
	mutation *HeatCardMutation
	hooks    []Hook
}

// SetRacerID sets the "racer_id" field.
func (_c *HeatCardCreate) SetRacerID(v int) *HeatCardCreate {
	_c.mutation.SetRacerID(v)
	return _c
}

// SetLocation sets the "location" field.
func (_c *HeatCardCreate) SetLocation(v string) *HeatCardCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *HeatCardCreate) SetNillableLocation(v *string) *HeatCardCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetCardType sets the "card_type" field.
func (_c *HeatCardCreate) SetCardType(v string) *HeatCardCreate {
	_c.mutation.SetCardType(v)
	return _c
}

// SetNillableCardType sets the "card_type" field if the given value is not nil.
func (_c *HeatCardCreate) SetNillableCardType(v *string) *HeatCardCreate {
	if v != nil {
		_c.SetCardType(*v)
	}
	return _c
}

// SetLapAdded sets the "lap_added" field.
func (_c *HeatCardCreate) SetLapAdded(v int) *HeatCardCreate {
	_c.mutation.SetLapAdded(v)
	return _c
}

// SetNillableLapAdded sets the "lap_added" field if the given value is not nil.
func (_c *HeatCardCreate) SetNillableLapAdded(v *int) *HeatCardCreate {
	if v != nil {
		_c.SetLapAdded(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HeatCardCreate) SetID(v int) *HeatCardCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the HeatCardMutation object of the builder.
func (_c *HeatCardCreate) Mutation() *HeatCardMutation {
	return _c.mutation
}

// Save creates the HeatCard in the database.
func (_c *HeatCardCreate) Save(ctx context.Context) (*HeatCard, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HeatCardCreate) SaveX(ctx context.Context) *HeatCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HeatCardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HeatCardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HeatCardCreate) defaults() {
	if _, ok := _c.mutation.Location(); !ok {
		v := heatcard.DefaultLocation
		_c.mutation.SetLocation(v)
	}
	if _, ok := _c.mutation.CardType(); !ok {
		v := heatcard.DefaultCardType
		_c.mutation.SetCardType(v)
	}
	if _, ok := _c.mutation.LapAdded(); !ok {
		v := heatcard.DefaultLapAdded
		_c.mutation.SetLapAdded(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HeatCardCreate) check() error {
	if _, ok := _c.mutation.RacerID(); !ok {
		return &ValidationError{Name: "racer_id", err: errors.New(`ent: missing required field "HeatCard.racer_id"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "HeatCard.location"`)}
	}
	if _, ok := _c.mutation.CardType(); !ok {
		return &ValidationError{Name: "card_type", err: errors.New(`ent: missing required field "HeatCard.card_type"`)}
	}
	if _, ok := _c.mutation.LapAdded(); !ok {
		return &ValidationError{Name: "lap_added", err: errors.New(`ent: missing required field "HeatCard.lap_added"`)}
	}
	return nil
}

func (_c *HeatCardCreate) sqlSave(ctx context.Context) (*HeatCard, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HeatCardCreate) createSpec() (*HeatCard, *sqlgraph.CreateSpec) {
	var (
		_node = &HeatCard{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(heatcard.Table, sqlgraph.NewFieldSpec(heatcard.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RacerID(); ok {
		_spec.SetField(heatcard.FieldRacerID, field.TypeInt, value)
		_node.RacerID = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(heatcard.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.CardType(); ok {
		_spec.SetField(heatcard.FieldCardType, field.TypeString, value)
		_node.CardType = value
	}
	if value, ok := _c.mutation.LapAdded(); ok {
		_spec.SetField(heatcard.FieldLapAdded, field.TypeInt, value)
		_node.LapAdded = value
	}
	return _node, _spec
}

// HeatCardCreateBulk is the builder for creating many HeatCard entities in bulk.
type HeatCardCreateBulk struct {
	config
	err      error
	builders []*HeatCardCreate
}

// Save creates the HeatCard entities in the database.
func (_c *HeatCardCreateBulk) Save(ctx context.Context) ([]*HeatCard, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HeatCard, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HeatCardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HeatCardCreateBulk) SaveX(ctx context.Context) []*HeatCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HeatCardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HeatCardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
