// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/notificationsetting"
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationSettingUpdate is the builder for updating NotificationSetting entities.
type NotificationSettingUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationSettingMutation
}

// Where appends a list predicates to the NotificationSettingUpdate builder.
func (_u *NotificationSettingUpdate) Where(ps ...predicate.NotificationSetting) *NotificationSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGotifyURL sets the "gotify_url" field.
func (_u *NotificationSettingUpdate) SetGotifyURL(v string) *NotificationSettingUpdate {
	_u.mutation.SetGotifyURL(v)
	return _u
}

// SetNillableGotifyURL sets the "gotify_url" field if the given value is not nil.
func (_u *NotificationSettingUpdate) SetNillableGotifyURL(v *string) *NotificationSettingUpdate {
	if v != nil {
		_u.SetGotifyURL(*v)
	}
	return _u
}

// ClearGotifyURL clears the value of the "gotify_url" field.
func (_u *NotificationSettingUpdate) ClearGotifyURL() *NotificationSettingUpdate {
	_u.mutation.ClearGotifyURL()
	return _u
}

// SetGotifyToken sets the "gotify_token" field.
func (_u *NotificationSettingUpdate) SetGotifyToken(v string) *NotificationSettingUpdate {
	_u.mutation.SetGotifyToken(v)
	return _u
}

// SetNillableGotifyToken sets the "gotify_token" field if the given value is not nil.
func (_u *NotificationSettingUpdate) SetNillableGotifyToken(v *string) *NotificationSettingUpdate {
	if v != nil {
		_u.SetGotifyToken(*v)
	}
	return _u
}

// ClearGotifyToken clears the value of the "gotify_token" field.
func (_u *NotificationSettingUpdate) ClearGotifyToken() *NotificationSettingUpdate {
	_u.mutation.ClearGotifyToken()
	return _u
}

// SetNotifyWinner sets the "notify_winner" field.
func (_u *NotificationSettingUpdate) SetNotifyWinner(v int) *NotificationSettingUpdate {
	_u.mutation.ResetNotifyWinner()
	_u.mutation.SetNotifyWinner(v)
	return _u
}

// SetNillableNotifyWinner sets the "notify_winner" field if the given value is not nil.
func (_u *NotificationSettingUpdate) SetNillableNotifyWinner(v *int) *NotificationSettingUpdate {
	if v != nil {
		_u.SetNotifyWinner(*v)
	}
	return _u
}

// AddNotifyWinner adds value to the "notify_winner" field.
func (_u *NotificationSettingUpdate) AddNotifyWinner(v int) *NotificationSettingUpdate {
	_u.mutation.AddNotifyWinner(v)
	return _u
}

// SetNotifyRaceStart sets the "notify_race_start" field.
func (_u *NotificationSettingUpdate) SetNotifyRaceStart(v int) *NotificationSettingUpdate {
	_u.mutation.ResetNotifyRaceStart()
	_u.mutation.SetNotifyRaceStart(v)
	return _u
}

// SetNillableNotifyRaceStart sets the "notify_race_start" field if the given value is not nil.
func (_u *NotificationSettingUpdate) SetNillableNotifyRaceStart(v *int) *NotificationSettingUpdate {
	if v != nil {
		_u.SetNotifyRaceStart(*v)
	}
	return _u
}

// AddNotifyRaceStart adds value to the "notify_race_start" field.
func (_u *NotificationSettingUpdate) AddNotifyRaceStart(v int) *NotificationSettingUpdate {
	_u.mutation.AddNotifyRaceStart(v)
	return _u
}

// SetNotifyPodium sets the "notify_podium" field.
func (_u *NotificationSettingUpdate) SetNotifyPodium(v int) *NotificationSettingUpdate {
	_u.mutation.ResetNotifyPodium()
	_u.mutation.SetNotifyPodium(v)
	return _u
}

// SetNillableNotifyPodium sets the "notify_podium" field if the given value is not nil.
func (_u *NotificationSettingUpdate) SetNillableNotifyPodium(v *int) *NotificationSettingUpdate {
	if v != nil {
		_u.SetNotifyPodium(*v)
	}
	return _u
}

// AddNotifyPodium adds value to the "notify_podium" field.
func (_u *NotificationSettingUpdate) AddNotifyPodium(v int) *NotificationSettingUpdate {
	_u.mutation.AddNotifyPodium(v)
	return _u
}

// Mutation returns the NotificationSettingMutation object of the builder.
func (_u *NotificationSettingUpdate) Mutation() *NotificationSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationsetting.Table, notificationsetting.Columns, sqlgraph.NewFieldSpec(notificationsetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GotifyURL(); ok {
		_spec.SetField(notificationsetting.FieldGotifyURL, field.TypeString, value)
	}
	if _u.mutation.GotifyURLCleared() {
		_spec.ClearField(notificationsetting.FieldGotifyURL, field.TypeString)
	}
	if value, ok := _u.mutation.GotifyToken(); ok {
		_spec.SetField(notificationsetting.FieldGotifyToken, field.TypeString, value)
	}
	if _u.mutation.GotifyTokenCleared() {
		_spec.ClearField(notificationsetting.FieldGotifyToken, field.TypeString)
	}
	if value, ok := _u.mutation.NotifyWinner(); ok {
		_spec.SetField(notificationsetting.FieldNotifyWinner, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotifyWinner(); ok {
		_spec.AddField(notificationsetting.FieldNotifyWinner, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NotifyRaceStart(); ok {
		_spec.SetField(notificationsetting.FieldNotifyRaceStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotifyRaceStart(); ok {
		_spec.AddField(notificationsetting.FieldNotifyRaceStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NotifyPodium(); ok {
		_spec.SetField(notificationsetting.FieldNotifyPodium, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotifyPodium(); ok {
		_spec.AddField(notificationsetting.FieldNotifyPodium, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationSettingUpdateOne is the builder for updating a single NotificationSetting entity.
type NotificationSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationSettingMutation
}

// SetGotifyURL sets the "gotify_url" field.
func (_u *NotificationSettingUpdateOne) SetGotifyURL(v string) *NotificationSettingUpdateOne {
	_u.mutation.SetGotifyURL(v)
	return _u
}

// SetNillableGotifyURL sets the "gotify_url" field if the given value is not nil.
func (_u *NotificationSettingUpdateOne) SetNillableGotifyURL(v *string) *NotificationSettingUpdateOne {
	if v != nil {
		_u.SetGotifyURL(*v)
	}
	return _u
}

// ClearGotifyURL clears the value of the "gotify_url" field.
func (_u *NotificationSettingUpdateOne) ClearGotifyURL() *NotificationSettingUpdateOne {
	_u.mutation.ClearGotifyURL()
	return _u
}

// SetGotifyToken sets the "gotify_token" field.
func (_u *NotificationSettingUpdateOne) SetGotifyToken(v string) *NotificationSettingUpdateOne {
	_u.mutation.SetGotifyToken(v)
	return _u
}

// SetNillableGotifyToken sets the "gotify_token" field if the given value is not nil.
func (_u *NotificationSettingUpdateOne) SetNillableGotifyToken(v *string) *NotificationSettingUpdateOne {
	if v != nil {
		_u.SetGotifyToken(*v)
	}
	return _u
}

// ClearGotifyToken clears the value of the "gotify_token" field.
func (_u *NotificationSettingUpdateOne) ClearGotifyToken() *NotificationSettingUpdateOne {
	_u.mutation.ClearGotifyToken()
	return _u
}

// SetNotifyWinner sets the "notify_winner" field.
func (_u *NotificationSettingUpdateOne) SetNotifyWinner(v int) *NotificationSettingUpdateOne {
	_u.mutation.ResetNotifyWinner()
	_u.mutation.SetNotifyWinner(v)
	return _u
}

// SetNillableNotifyWinner sets the "notify_winner" field if the given value is not nil.
func (_u *NotificationSettingUpdateOne) SetNillableNotifyWinner(v *int) *NotificationSettingUpdateOne {
	if v != nil {
		_u.SetNotifyWinner(*v)
	}
	return _u
}

// AddNotifyWinner adds value to the "notify_winner" field.
func (_u *NotificationSettingUpdateOne) AddNotifyWinner(v int) *NotificationSettingUpdateOne {
	_u.mutation.AddNotifyWinner(v)
	return _u
}

// SetNotifyRaceStart sets the "notify_race_start" field.
func (_u *NotificationSettingUpdateOne) SetNotifyRaceStart(v int) *NotificationSettingUpdateOne {
	_u.mutation.ResetNotifyRaceStart()
	_u.mutation.SetNotifyRaceStart(v)
	return _u
}

// SetNillableNotifyRaceStart sets the "notify_race_start" field if the given value is not nil.
func (_u *NotificationSettingUpdateOne) SetNillableNotifyRaceStart(v *int) *NotificationSettingUpdateOne {
	if v != nil {
		_u.SetNotifyRaceStart(*v)
	}
	return _u
}

// AddNotifyRaceStart adds value to the "notify_race_start" field.
func (_u *NotificationSettingUpdateOne) AddNotifyRaceStart(v int) *NotificationSettingUpdateOne {
	_u.mutation.AddNotifyRaceStart(v)
	return _u
}

// SetNotifyPodium sets the "notify_podium" field.
func (_u *NotificationSettingUpdateOne) SetNotifyPodium(v int) *NotificationSettingUpdateOne {
	_u.mutation.ResetNotifyPodium()
	_u.mutation.SetNotifyPodium(v)
	return _u
}

// SetNillableNotifyPodium sets the "notify_podium" field if the given value is not nil.
func (_u *NotificationSettingUpdateOne) SetNillableNotifyPodium(v *int) *NotificationSettingUpdateOne {
	if v != nil {
		_u.SetNotifyPodium(*v)
	}
	return _u
}

// AddNotifyPodium adds value to the "notify_podium" field.
func (_u *NotificationSettingUpdateOne) AddNotifyPodium(v int) *NotificationSettingUpdateOne {
	_u.mutation.AddNotifyPodium(v)
	return _u
}

// Mutation returns the NotificationSettingMutation object of the builder.
func (_u *NotificationSettingUpdateOne) Mutation() *NotificationSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationSettingUpdate builder.
func (_u *NotificationSettingUpdateOne) Where(ps ...predicate.NotificationSetting) *NotificationSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationSettingUpdateOne) Select(field string, fields ...string) *NotificationSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationSetting entity.
func (_u *NotificationSettingUpdateOne) Save(ctx context.Context) (*NotificationSetting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationSettingUpdateOne) SaveX(ctx context.Context) *NotificationSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationSettingUpdateOne) sqlSave(ctx context.Context) (_node *NotificationSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationsetting.Table, notificationsetting.Columns, sqlgraph.NewFieldSpec(notificationsetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationsetting.FieldID)
		for _, f := range fields {
			if !notificationsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GotifyURL(); ok {
		_spec.SetField(notificationsetting.FieldGotifyURL, field.TypeString, value)
	}
	if _u.mutation.GotifyURLCleared() {
		_spec.ClearField(notificationsetting.FieldGotifyURL, field.TypeString)
	}
	if value, ok := _u.mutation.GotifyToken(); ok {
		_spec.SetField(notificationsetting.FieldGotifyToken, field.TypeString, value)
	}
	if _u.mutation.GotifyTokenCleared() {
		_spec.ClearField(notificationsetting.FieldGotifyToken, field.TypeString)
	}
	if value, ok := _u.mutation.NotifyWinner(); ok {
		_spec.SetField(notificationsetting.FieldNotifyWinner, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotifyWinner(); ok {
		_spec.AddField(notificationsetting.FieldNotifyWinner, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NotifyRaceStart(); ok {
		_spec.SetField(notificationsetting.FieldNotifyRaceStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotifyRaceStart(); ok {
		_spec.AddField(notificationsetting.FieldNotifyRaceStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NotifyPodium(); ok {
		_spec.SetField(notificationsetting.FieldNotifyPodium, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotifyPodium(); ok {
		_spec.AddField(notificationsetting.FieldNotifyPodium, field.TypeInt, value)
	}
	_node = &NotificationSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
