// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/otelsetting"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OTelSettingCreate is the builder for creating a OTelSetting entity.
type OTelSettingCreate struct {
	config
	mutation *OTelSettingMutation
	hooks    []Hook
}

// SetEndpoint sets the "endpoint" field.
func (_c *OTelSettingCreate) SetEndpoint(v string) *OTelSettingCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *OTelSettingCreate) SetNillableEndpoint(v *string) *OTelSettingCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetTracesEnabled sets the "traces_enabled" field.
func (_c *OTelSettingCreate) SetTracesEnabled(v int) *OTelSettingCreate {
	_c.mutation.SetTracesEnabled(v)
	return _c
}

// SetNillableTracesEnabled sets the "traces_enabled" field if the given value is not nil.
func (_c *OTelSettingCreate) SetNillableTracesEnabled(v *int) *OTelSettingCreate {
	if v != nil {
		_c.SetTracesEnabled(*v)
	}
	return _c
}

// SetMetricsEnabled sets the "metrics_enabled" field.
func (_c *OTelSettingCreate) SetMetricsEnabled(v int) *OTelSettingCreate {
	_c.mutation.SetMetricsEnabled(v)
	return _c
}

// SetNillableMetricsEnabled sets the "metrics_enabled" field if the given value is not nil.
func (_c *OTelSettingCreate) SetNillableMetricsEnabled(v *int) *OTelSettingCreate {
	if v != nil {
		_c.SetMetricsEnabled(*v)
	}
	return _c
}

// SetLogsEnabled sets the "logs_enabled" field.
func (_c *OTelSettingCreate) SetLogsEnabled(v int) *OTelSettingCreate {
	_c.mutation.SetLogsEnabled(v)
	return _c
}

// SetNillableLogsEnabled sets the "logs_enabled" field if the given value is not nil.
func (_c *OTelSettingCreate) SetNillableLogsEnabled(v *int) *OTelSettingCreate {
	if v != nil {
		_c.SetLogsEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OTelSettingCreate) SetID(v int) *OTelSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OTelSettingMutation object of the builder.
func (_c *OTelSettingCreate) Mutation() *OTelSettingMutation {
	return _c.mutation
}

// Save creates the OTelSetting in the database.
func (_c *OTelSettingCreate) Save(ctx context.Context) (*OTelSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OTelSettingCreate) SaveX(ctx context.Context) *OTelSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OTelSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OTelSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OTelSettingCreate) defaults() {
	if _, ok := _c.mutation.TracesEnabled(); !ok {
		v := otelsetting.DefaultTracesEnabled
		_c.mutation.SetTracesEnabled(v)
	}
	if _, ok := _c.mutation.MetricsEnabled(); !ok {
		v := otelsetting.DefaultMetricsEnabled
		_c.mutation.SetMetricsEnabled(v)
	}
	if _, ok := _c.mutation.LogsEnabled(); !ok {
		v := otelsetting.DefaultLogsEnabled
		_c.mutation.SetLogsEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OTelSettingCreate) check() error {
	if _, ok := _c.mutation.TracesEnabled(); !ok {
		return &ValidationError{Name: "traces_enabled", err: errors.New(`ent: missing required field "OTelSetting.traces_enabled"`)}
	}
	if _, ok := _c.mutation.MetricsEnabled(); !ok {
		return &ValidationError{Name: "metrics_enabled", err: errors.New(`ent: missing required field "OTelSetting.metrics_enabled"`)}
	}
	if _, ok := _c.mutation.LogsEnabled(); !ok {
		return &ValidationError{Name: "logs_enabled", err: errors.New(`ent: missing required field "OTelSetting.logs_enabled"`)}
	}
	return nil
}

func (_c *OTelSettingCreate) sqlSave(ctx context.Context) (*OTelSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OTelSettingCreate) createSpec() (*OTelSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &OTelSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(otelsetting.Table, sqlgraph.NewFieldSpec(otelsetting.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(otelsetting.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.TracesEnabled(); ok {
		_spec.SetField(otelsetting.FieldTracesEnabled, field.TypeInt, value)
		_node.TracesEnabled = value
	}
	if value, ok := _c.mutation.MetricsEnabled(); ok {
		_spec.SetField(otelsetting.FieldMetricsEnabled, field.TypeInt, value)
		_node.MetricsEnabled = value
	}
	if value, ok := _c.mutation.LogsEnabled(); ok {
		_spec.SetField(otelsetting.FieldLogsEnabled, field.TypeInt, value)
		_node.LogsEnabled = value
	}
	return _node, _spec
}

// OTelSettingCreateBulk is the builder for creating many OTelSetting entities in bulk.
type OTelSettingCreateBulk struct {
	config
	err      error
	builders []*OTelSettingCreate
}

// Save creates the OTelSetting entities in the database.
func (_c *OTelSettingCreateBulk) Save(ctx context.Context) ([]*OTelSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OTelSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OTelSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OTelSettingCreateBulk) SaveX(ctx context.Context) []*OTelSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OTelSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OTelSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
