// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/otelsetting"
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OTelSettingUpdate is the builder for updating OTelSetting entities.
type OTelSettingUpdate struct {
	config
	hooks    []Hook
	mutation *OTelSettingMutation
}

// Where appends a list predicates to the OTelSettingUpdate builder.
func (_u *OTelSettingUpdate) Where(ps ...predicate.OTelSetting) *OTelSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *OTelSettingUpdate) SetEndpoint(v string) *OTelSettingUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *OTelSettingUpdate) SetNillableEndpoint(v *string) *OTelSettingUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *OTelSettingUpdate) ClearEndpoint() *OTelSettingUpdate {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetTracesEnabled sets the "traces_enabled" field.
func (_u *OTelSettingUpdate) SetTracesEnabled(v int) *OTelSettingUpdate {
	_u.mutation.ResetTracesEnabled()
	_u.mutation.SetTracesEnabled(v)
	return _u
}

// SetNillableTracesEnabled sets the "traces_enabled" field if the given value is not nil.
func (_u *OTelSettingUpdate) SetNillableTracesEnabled(v *int) *OTelSettingUpdate {
	if v != nil {
		_u.SetTracesEnabled(*v)
	}
	return _u
}

// AddTracesEnabled adds value to the "traces_enabled" field.
func (_u *OTelSettingUpdate) AddTracesEnabled(v int) *OTelSettingUpdate {
	_u.mutation.AddTracesEnabled(v)
	return _u
}

// SetMetricsEnabled sets the "metrics_enabled" field.
func (_u *OTelSettingUpdate) SetMetricsEnabled(v int) *OTelSettingUpdate {
	_u.mutation.ResetMetricsEnabled()
	_u.mutation.SetMetricsEnabled(v)
	return _u
}

// SetNillableMetricsEnabled sets the "metrics_enabled" field if the given value is not nil.
func (_u *OTelSettingUpdate) SetNillableMetricsEnabled(v *int) *OTelSettingUpdate {
	if v != nil {
		_u.SetMetricsEnabled(*v)
	}
	return _u
}

// AddMetricsEnabled adds value to the "metrics_enabled" field.
func (_u *OTelSettingUpdate) AddMetricsEnabled(v int) *OTelSettingUpdate {
	_u.mutation.AddMetricsEnabled(v)
	return _u
}

// SetLogsEnabled sets the "logs_enabled" field.
func (_u *OTelSettingUpdate) SetLogsEnabled(v int) *OTelSettingUpdate {
	_u.mutation.ResetLogsEnabled()
	_u.mutation.SetLogsEnabled(v)
	return _u
}

// SetNillableLogsEnabled sets the "logs_enabled" field if the given value is not nil.
func (_u *OTelSettingUpdate) SetNillableLogsEnabled(v *int) *OTelSettingUpdate {
	if v != nil {
		_u.SetLogsEnabled(*v)
	}
	return _u
}

// AddLogsEnabled adds value to the "logs_enabled" field.
func (_u *OTelSettingUpdate) AddLogsEnabled(v int) *OTelSettingUpdate {
	_u.mutation.AddLogsEnabled(v)
	return _u
}

// Mutation returns the OTelSettingMutation object of the builder.
func (_u *OTelSettingUpdate) Mutation() *OTelSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OTelSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OTelSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OTelSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OTelSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OTelSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(otelsetting.Table, otelsetting.Columns, sqlgraph.NewFieldSpec(otelsetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(otelsetting.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(otelsetting.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.TracesEnabled(); ok {
		_spec.SetField(otelsetting.FieldTracesEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTracesEnabled(); ok {
		_spec.AddField(otelsetting.FieldTracesEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetricsEnabled(); ok {
		_spec.SetField(otelsetting.FieldMetricsEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetricsEnabled(); ok {
		_spec.AddField(otelsetting.FieldMetricsEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LogsEnabled(); ok {
		_spec.SetField(otelsetting.FieldLogsEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLogsEnabled(); ok {
		_spec.AddField(otelsetting.FieldLogsEnabled, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otelsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OTelSettingUpdateOne is the builder for updating a single OTelSetting entity.
type OTelSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OTelSettingMutation
}

// SetEndpoint sets the "endpoint" field.
func (_u *OTelSettingUpdateOne) SetEndpoint(v string) *OTelSettingUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *OTelSettingUpdateOne) SetNillableEndpoint(v *string) *OTelSettingUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *OTelSettingUpdateOne) ClearEndpoint() *OTelSettingUpdateOne {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetTracesEnabled sets the "traces_enabled" field.
func (_u *OTelSettingUpdateOne) SetTracesEnabled(v int) *OTelSettingUpdateOne {
	_u.mutation.ResetTracesEnabled()
	_u.mutation.SetTracesEnabled(v)
	return _u
}

// SetNillableTracesEnabled sets the "traces_enabled" field if the given value is not nil.
func (_u *OTelSettingUpdateOne) SetNillableTracesEnabled(v *int) *OTelSettingUpdateOne {
	if v != nil {
		_u.SetTracesEnabled(*v)
	}
	return _u
}

// AddTracesEnabled adds value to the "traces_enabled" field.
func (_u *OTelSettingUpdateOne) AddTracesEnabled(v int) *OTelSettingUpdateOne {
	_u.mutation.AddTracesEnabled(v)
	return _u
}

// SetMetricsEnabled sets the "metrics_enabled" field.
func (_u *OTelSettingUpdateOne) SetMetricsEnabled(v int) *OTelSettingUpdateOne {
	_u.mutation.ResetMetricsEnabled()
	_u.mutation.SetMetricsEnabled(v)
	return _u
}

// SetNillableMetricsEnabled sets the "metrics_enabled" field if the given value is not nil.
func (_u *OTelSettingUpdateOne) SetNillableMetricsEnabled(v *int) *OTelSettingUpdateOne {
	if v != nil {
		_u.SetMetricsEnabled(*v)
	}
	return _u
}

// AddMetricsEnabled adds value to the "metrics_enabled" field.
func (_u *OTelSettingUpdateOne) AddMetricsEnabled(v int) *OTelSettingUpdateOne {
	_u.mutation.AddMetricsEnabled(v)
	return _u
}

// SetLogsEnabled sets the "logs_enabled" field.
func (_u *OTelSettingUpdateOne) SetLogsEnabled(v int) *OTelSettingUpdateOne {
	_u.mutation.ResetLogsEnabled()
	_u.mutation.SetLogsEnabled(v)
	return _u
}

// SetNillableLogsEnabled sets the "logs_enabled" field if the given value is not nil.
func (_u *OTelSettingUpdateOne) SetNillableLogsEnabled(v *int) *OTelSettingUpdateOne {
	if v != nil {
		_u.SetLogsEnabled(*v)
	}
	return _u
}

// AddLogsEnabled adds value to the "logs_enabled" field.
func (_u *OTelSettingUpdateOne) AddLogsEnabled(v int) *OTelSettingUpdateOne {
	_u.mutation.AddLogsEnabled(v)
	return _u
}

// Mutation returns the OTelSettingMutation object of the builder.
func (_u *OTelSettingUpdateOne) Mutation() *OTelSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the OTelSettingUpdate builder.
func (_u *OTelSettingUpdateOne) Where(ps ...predicate.OTelSetting) *OTelSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OTelSettingUpdateOne) Select(field string, fields ...string) *OTelSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OTelSetting entity.
func (_u *OTelSettingUpdateOne) Save(ctx context.Context) (*OTelSetting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OTelSettingUpdateOne) SaveX(ctx context.Context) *OTelSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OTelSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OTelSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OTelSettingUpdateOne) sqlSave(ctx context.Context) (_node *OTelSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(otelsetting.Table, otelsetting.Columns, sqlgraph.NewFieldSpec(otelsetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OTelSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otelsetting.FieldID)
		for _, f := range fields {
			if !otelsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != otelsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(otelsetting.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(otelsetting.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.TracesEnabled(); ok {
		_spec.SetField(otelsetting.FieldTracesEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTracesEnabled(); ok {
		_spec.AddField(otelsetting.FieldTracesEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetricsEnabled(); ok {
		_spec.SetField(otelsetting.FieldMetricsEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetricsEnabled(); ok {
		_spec.AddField(otelsetting.FieldMetricsEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LogsEnabled(); ok {
		_spec.SetField(otelsetting.FieldLogsEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLogsEnabled(); ok {
		_spec.AddField(otelsetting.FieldLogsEnabled, field.TypeInt, value)
	}
	_node = &OTelSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otelsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
