// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/playerupgrade"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PlayerUpgrade is the model entity for the PlayerUpgrade schema.
type PlayerUpgrade struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RacerID holds the value of the "racer_id" field.
	RacerID int `json:"racer_id,omitempty"`
	// UpgradeID holds the value of the "upgrade_id" field.
	UpgradeID int `json:"upgrade_id,omitempty"`
	// SeasonID holds the value of the "season_id" field.
	SeasonID int `json:"season_id,omitempty"`
	// Equipped holds the value of the "equipped" field.
	Equipped int `json:"equipped,omitempty"`
	// RoundBought holds the value of the "round_bought" field.
	RoundBought  int `json:"round_bought,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayerUpgrade) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playerupgrade.FieldID, playerupgrade.FieldRacerID, playerupgrade.FieldUpgradeID, playerupgrade.FieldSeasonID, playerupgrade.FieldEquipped, playerupgrade.FieldRoundBought:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayerUpgrade fields.
func (_m *PlayerUpgrade) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playerupgrade.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case playerupgrade.FieldRacerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field racer_id", values[i])
			} else if value.Valid {
				_m.RacerID = int(value.Int64)
			}
		case playerupgrade.FieldUpgradeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_id", values[i])
			} else if value.Valid {
				_m.UpgradeID = int(value.Int64)
			}
		case playerupgrade.FieldSeasonID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field season_id", values[i])
			} else if value.Valid {
				_m.SeasonID = int(value.Int64)
			}
		case playerupgrade.FieldEquipped:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field equipped", values[i])
			} else if value.Valid {
				_m.Equipped = int(value.Int64)
			}
		case playerupgrade.FieldRoundBought:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field round_bought", values[i])
			} else if value.Valid {
				_m.RoundBought = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayerUpgrade.
// This includes values selected through modifiers, order, etc.
func (_m *PlayerUpgrade) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PlayerUpgrade.
// Note that you need to call PlayerUpgrade.Unwrap() before calling this method if this PlayerUpgrade
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlayerUpgrade) Update() *PlayerUpgradeUpdateOne {
	return NewPlayerUpgradeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlayerUpgrade entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlayerUpgrade) Unwrap() *PlayerUpgrade {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayerUpgrade is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlayerUpgrade) String() string {
	var builder strings.Builder
	builder.WriteString("PlayerUpgrade(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("racer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RacerID))
	builder.WriteString(", ")
	builder.WriteString("upgrade_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpgradeID))
	builder.WriteString(", ")
	builder.WriteString("season_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeasonID))
	builder.WriteString(", ")
	builder.WriteString("equipped=")
	builder.WriteString(fmt.Sprintf("%v", _m.Equipped))
	builder.WriteString(", ")
	builder.WriteString("round_bought=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoundBought))
	builder.WriteByte(')')
	return builder.String()
}

// PlayerUpgrades is a parsable slice of PlayerUpgrade.
type PlayerUpgrades []*PlayerUpgrade
