// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/playersession"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PlayerSession is the model entity for the PlayerSession schema.
type PlayerSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RacerID holds the value of the "racer_id" field.
	RacerID int `json:"racer_id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// DeviceName holds the value of the "device_name" field.
	DeviceName string `json:"device_name,omitempty"`
	// LastSeen holds the value of the "last_seen" field.
	LastSeen string `json:"last_seen,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    string `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayerSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playersession.FieldID, playersession.FieldRacerID:
			values[i] = new(sql.NullInt64)
		case playersession.FieldToken, playersession.FieldDeviceName, playersession.FieldLastSeen, playersession.FieldCreatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayerSession fields.
func (_m *PlayerSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playersession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case playersession.FieldRacerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field racer_id", values[i])
			} else if value.Valid {
				_m.RacerID = int(value.Int64)
			}
		case playersession.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case playersession.FieldDeviceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_name", values[i])
			} else if value.Valid {
				_m.DeviceName = value.String
			}
		case playersession.FieldLastSeen:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = value.String
			}
		case playersession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayerSession.
// This includes values selected through modifiers, order, etc.
func (_m *PlayerSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PlayerSession.
// Note that you need to call PlayerSession.Unwrap() before calling this method if this PlayerSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlayerSession) Update() *PlayerSessionUpdateOne {
	return NewPlayerSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlayerSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlayerSession) Unwrap() *PlayerSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayerSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlayerSession) String() string {
	var builder strings.Builder
	builder.WriteString("PlayerSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("racer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RacerID))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("device_name=")
	builder.WriteString(_m.DeviceName)
	builder.WriteString(", ")
	builder.WriteString("last_seen=")
	builder.WriteString(_m.LastSeen)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// PlayerSessions is a parsable slice of PlayerSession.
type PlayerSessions []*PlayerSession
