// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/playerupgrade"
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlayerUpgradeUpdate is the builder for updating PlayerUpgrade entities.
type PlayerUpgradeUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerUpgradeMutation
}

// Where appends a list predicates to the PlayerUpgradeUpdate builder.
func (_u *PlayerUpgradeUpdate) Where(ps ...predicate.PlayerUpgrade) *PlayerUpgradeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRacerID sets the "racer_id" field.
func (_u *PlayerUpgradeUpdate) SetRacerID(v int) *PlayerUpgradeUpdate {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *PlayerUpgradeUpdate) SetNillableRacerID(v *int) *PlayerUpgradeUpdate {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *PlayerUpgradeUpdate) AddRacerID(v int) *PlayerUpgradeUpdate {
	_u.mutation.AddRacerID(v)
	return _u
}

// SetUpgradeID sets the "upgrade_id" field.
func (_u *PlayerUpgradeUpdate) SetUpgradeID(v int) *PlayerUpgradeUpdate {
	_u.mutation.ResetUpgradeID()
	_u.mutation.SetUpgradeID(v)
	return _u
}

// SetNillableUpgradeID sets the "upgrade_id" field if the given value is not nil.
func (_u *PlayerUpgradeUpdate) SetNillableUpgradeID(v *int) *PlayerUpgradeUpdate {
	if v != nil {
		_u.SetUpgradeID(*v)
	}
	return _u
}

// AddUpgradeID adds value to the "upgrade_id" field.
func (_u *PlayerUpgradeUpdate) AddUpgradeID(v int) *PlayerUpgradeUpdate {
	_u.mutation.AddUpgradeID(v)
	return _u
}

// SetSeasonID sets the "season_id" field.
func (_u *PlayerUpgradeUpdate) SetSeasonID(v int) *PlayerUpgradeUpdate {
	_u.mutation.ResetSeasonID()
	_u.mutation.SetSeasonID(v)
	return _u
}

// SetNillableSeasonID sets the "season_id" field if the given value is not nil.
func (_u *PlayerUpgradeUpdate) SetNillableSeasonID(v *int) *PlayerUpgradeUpdate {
	if v != nil {
		_u.SetSeasonID(*v)
	}
	return _u
}

// AddSeasonID adds value to the "season_id" field.
func (_u *PlayerUpgradeUpdate) AddSeasonID(v int) *PlayerUpgradeUpdate {
	_u.mutation.AddSeasonID(v)
	return _u
}

// SetEquipped sets the "equipped" field.
func (_u *PlayerUpgradeUpdate) SetEquipped(v int) *PlayerUpgradeUpdate {
	_u.mutation.ResetEquipped()
	_u.mutation.SetEquipped(v)
	return _u
}

// SetNillableEquipped sets the "equipped" field if the given value is not nil.
func (_u *PlayerUpgradeUpdate) SetNillableEquipped(v *int) *PlayerUpgradeUpdate {
	if v != nil {
		_u.SetEquipped(*v)
	}
	return _u
}

// AddEquipped adds value to the "equipped" field.
func (_u *PlayerUpgradeUpdate) AddEquipped(v int) *PlayerUpgradeUpdate {
	_u.mutation.AddEquipped(v)
	return _u
}

// SetRoundBought sets the "round_bought" field.
func (_u *PlayerUpgradeUpdate) SetRoundBought(v int) *PlayerUpgradeUpdate {
	_u.mutation.ResetRoundBought()
	_u.mutation.SetRoundBought(v)
	return _u
}

// SetNillableRoundBought sets the "round_bought" field if the given value is not nil.
func (_u *PlayerUpgradeUpdate) SetNillableRoundBought(v *int) *PlayerUpgradeUpdate {
	if v != nil {
		_u.SetRoundBought(*v)
	}
	return _u
}

// AddRoundBought adds value to the "round_bought" field.
func (_u *PlayerUpgradeUpdate) AddRoundBought(v int) *PlayerUpgradeUpdate {
	_u.mutation.AddRoundBought(v)
	return _u
}

// Mutation returns the PlayerUpgradeMutation object of the builder.
func (_u *PlayerUpgradeUpdate) Mutation() *PlayerUpgradeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerUpgradeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpgradeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerUpgradeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpgradeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PlayerUpgradeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(playerupgrade.Table, playerupgrade.Columns, sqlgraph.NewFieldSpec(playerupgrade.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(playerupgrade.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(playerupgrade.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpgradeID(); ok {
		_spec.SetField(playerupgrade.FieldUpgradeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpgradeID(); ok {
		_spec.AddField(playerupgrade.FieldUpgradeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SeasonID(); ok {
		_spec.SetField(playerupgrade.FieldSeasonID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeasonID(); ok {
		_spec.AddField(playerupgrade.FieldSeasonID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Equipped(); ok {
		_spec.SetField(playerupgrade.FieldEquipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEquipped(); ok {
		_spec.AddField(playerupgrade.FieldEquipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RoundBought(); ok {
		_spec.SetField(playerupgrade.FieldRoundBought, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundBought(); ok {
		_spec.AddField(playerupgrade.FieldRoundBought, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerupgrade.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerUpgradeUpdateOne is the builder for updating a single PlayerUpgrade entity.
type PlayerUpgradeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerUpgradeMutation
}

// SetRacerID sets the "racer_id" field.
func (_u *PlayerUpgradeUpdateOne) SetRacerID(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *PlayerUpgradeUpdateOne) SetNillableRacerID(v *int) *PlayerUpgradeUpdateOne {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *PlayerUpgradeUpdateOne) AddRacerID(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.AddRacerID(v)
	return _u
}

// SetUpgradeID sets the "upgrade_id" field.
func (_u *PlayerUpgradeUpdateOne) SetUpgradeID(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.ResetUpgradeID()
	_u.mutation.SetUpgradeID(v)
	return _u
}

// SetNillableUpgradeID sets the "upgrade_id" field if the given value is not nil.
func (_u *PlayerUpgradeUpdateOne) SetNillableUpgradeID(v *int) *PlayerUpgradeUpdateOne {
	if v != nil {
		_u.SetUpgradeID(*v)
	}
	return _u
}

// AddUpgradeID adds value to the "upgrade_id" field.
func (_u *PlayerUpgradeUpdateOne) AddUpgradeID(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.AddUpgradeID(v)
	return _u
}

// SetSeasonID sets the "season_id" field.
func (_u *PlayerUpgradeUpdateOne) SetSeasonID(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.ResetSeasonID()
	_u.mutation.SetSeasonID(v)
	return _u
}

// SetNillableSeasonID sets the "season_id" field if the given value is not nil.
func (_u *PlayerUpgradeUpdateOne) SetNillableSeasonID(v *int) *PlayerUpgradeUpdateOne {
	if v != nil {
		_u.SetSeasonID(*v)
	}
	return _u
}

// AddSeasonID adds value to the "season_id" field.
func (_u *PlayerUpgradeUpdateOne) AddSeasonID(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.AddSeasonID(v)
	return _u
}

// SetEquipped sets the "equipped" field.
func (_u *PlayerUpgradeUpdateOne) SetEquipped(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.ResetEquipped()
	_u.mutation.SetEquipped(v)
	return _u
}

// SetNillableEquipped sets the "equipped" field if the given value is not nil.
func (_u *PlayerUpgradeUpdateOne) SetNillableEquipped(v *int) *PlayerUpgradeUpdateOne {
	if v != nil {
		_u.SetEquipped(*v)
	}
	return _u
}

// AddEquipped adds value to the "equipped" field.
func (_u *PlayerUpgradeUpdateOne) AddEquipped(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.AddEquipped(v)
	return _u
}

// SetRoundBought sets the "round_bought" field.
func (_u *PlayerUpgradeUpdateOne) SetRoundBought(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.ResetRoundBought()
	_u.mutation.SetRoundBought(v)
	return _u
}

// SetNillableRoundBought sets the "round_bought" field if the given value is not nil.
func (_u *PlayerUpgradeUpdateOne) SetNillableRoundBought(v *int) *PlayerUpgradeUpdateOne {
	if v != nil {
		_u.SetRoundBought(*v)
	}
	return _u
}

// AddRoundBought adds value to the "round_bought" field.
func (_u *PlayerUpgradeUpdateOne) AddRoundBought(v int) *PlayerUpgradeUpdateOne {
	_u.mutation.AddRoundBought(v)
	return _u
}

// Mutation returns the PlayerUpgradeMutation object of the builder.
func (_u *PlayerUpgradeUpdateOne) Mutation() *PlayerUpgradeMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlayerUpgradeUpdate builder.
func (_u *PlayerUpgradeUpdateOne) Where(ps ...predicate.PlayerUpgrade) *PlayerUpgradeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerUpgradeUpdateOne) Select(field string, fields ...string) *PlayerUpgradeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlayerUpgrade entity.
func (_u *PlayerUpgradeUpdateOne) Save(ctx context.Context) (*PlayerUpgrade, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpgradeUpdateOne) SaveX(ctx context.Context) *PlayerUpgrade {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerUpgradeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpgradeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PlayerUpgradeUpdateOne) sqlSave(ctx context.Context) (_node *PlayerUpgrade, err error) {
	_spec := sqlgraph.NewUpdateSpec(playerupgrade.Table, playerupgrade.Columns, sqlgraph.NewFieldSpec(playerupgrade.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlayerUpgrade.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playerupgrade.FieldID)
		for _, f := range fields {
			if !playerupgrade.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playerupgrade.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(playerupgrade.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(playerupgrade.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpgradeID(); ok {
		_spec.SetField(playerupgrade.FieldUpgradeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpgradeID(); ok {
		_spec.AddField(playerupgrade.FieldUpgradeID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SeasonID(); ok {
		_spec.SetField(playerupgrade.FieldSeasonID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeasonID(); ok {
		_spec.AddField(playerupgrade.FieldSeasonID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Equipped(); ok {
		_spec.SetField(playerupgrade.FieldEquipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEquipped(); ok {
		_spec.AddField(playerupgrade.FieldEquipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RoundBought(); ok {
		_spec.SetField(playerupgrade.FieldRoundBought, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundBought(); ok {
		_spec.AddField(playerupgrade.FieldRoundBought, field.TypeInt, value)
	}
	_node = &PlayerUpgrade{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerupgrade.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
