// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/quote"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuoteCreate is the builder for creating a Quote entity.
type QuoteCreate struct {
	config
	mutation *QuoteMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (_c *QuoteCreate) SetText(v string) *QuoteCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetAuthor sets the "author" field.
func (_c *QuoteCreate) SetAuthor(v string) *QuoteCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *QuoteCreate) SetNillableAuthor(v *string) *QuoteCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuoteCreate) SetCreatedAt(v string) *QuoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuoteCreate) SetNillableCreatedAt(v *string) *QuoteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuoteCreate) SetID(v int) *QuoteCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the QuoteMutation object of the builder.
func (_c *QuoteCreate) Mutation() *QuoteMutation {
	return _c.mutation
}

// Save creates the Quote in the database.
func (_c *QuoteCreate) Save(ctx context.Context) (*Quote, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuoteCreate) SaveX(ctx context.Context) *Quote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuoteCreate) defaults() {
	if _, ok := _c.mutation.Author(); !ok {
		v := quote.DefaultAuthor
		_c.mutation.SetAuthor(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quote.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuoteCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Quote.text"`)}
	}
	if _, ok := _c.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required field "Quote.author"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Quote.created_at"`)}
	}
	return nil
}

func (_c *QuoteCreate) sqlSave(ctx context.Context) (*Quote, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuoteCreate) createSpec() (*Quote, *sqlgraph.CreateSpec) {
	var (
		_node = &Quote{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quote.Table, sqlgraph.NewFieldSpec(quote.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(quote.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(quote.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quote.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// QuoteCreateBulk is the builder for creating many Quote entities in bulk.
type QuoteCreateBulk struct {
	config
	err      error
	builders []*QuoteCreate
}

// Save creates the Quote entities in the database.
func (_c *QuoteCreateBulk) Save(ctx context.Context) ([]*Quote, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Quote, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuoteCreateBulk) SaveX(ctx context.Context) []*Quote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
