// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/predicate"
	"heat/ent/racehistory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RaceHistoryUpdate is the builder for updating RaceHistory entities.
type RaceHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *RaceHistoryMutation
}

// Where appends a list predicates to the RaceHistoryUpdate builder.
func (_u *RaceHistoryUpdate) Where(ps ...predicate.RaceHistory) *RaceHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RaceHistoryUpdate) SetName(v string) *RaceHistoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RaceHistoryUpdate) SetNillableName(v *string) *RaceHistoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRaceDate sets the "race_date" field.
func (_u *RaceHistoryUpdate) SetRaceDate(v string) *RaceHistoryUpdate {
	_u.mutation.SetRaceDate(v)
	return _u
}

// SetNillableRaceDate sets the "race_date" field if the given value is not nil.
func (_u *RaceHistoryUpdate) SetNillableRaceDate(v *string) *RaceHistoryUpdate {
	if v != nil {
		_u.SetRaceDate(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *RaceHistoryUpdate) SetCountry(v string) *RaceHistoryUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *RaceHistoryUpdate) SetNillableCountry(v *string) *RaceHistoryUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetTrack sets the "track" field.
func (_u *RaceHistoryUpdate) SetTrack(v string) *RaceHistoryUpdate {
	_u.mutation.SetTrack(v)
	return _u
}

// SetNillableTrack sets the "track" field if the given value is not nil.
func (_u *RaceHistoryUpdate) SetNillableTrack(v *string) *RaceHistoryUpdate {
	if v != nil {
		_u.SetTrack(*v)
	}
	return _u
}

// SetTrackID sets the "track_id" field.
func (_u *RaceHistoryUpdate) SetTrackID(v string) *RaceHistoryUpdate {
	_u.mutation.SetTrackID(v)
	return _u
}

// SetNillableTrackID sets the "track_id" field if the given value is not nil.
func (_u *RaceHistoryUpdate) SetNillableTrackID(v *string) *RaceHistoryUpdate {
	if v != nil {
		_u.SetTrackID(*v)
	}
	return _u
}

// SetTotalLaps sets the "total_laps" field.
func (_u *RaceHistoryUpdate) SetTotalLaps(v int) *RaceHistoryUpdate {
	_u.mutation.ResetTotalLaps()
	_u.mutation.SetTotalLaps(v)
	return _u
}

// SetNillableTotalLaps sets the "total_laps" field if the given value is not nil.
func (_u *RaceHistoryUpdate) SetNillableTotalLaps(v *int) *RaceHistoryUpdate {
	if v != nil {
		_u.SetTotalLaps(*v)
	}
	return _u
}

// AddTotalLaps adds value to the "total_laps" field.
func (_u *RaceHistoryUpdate) AddTotalLaps(v int) *RaceHistoryUpdate {
	_u.mutation.AddTotalLaps(v)
	return _u
}

// SetRaceType sets the "race_type" field.
func (_u *RaceHistoryUpdate) SetRaceType(v string) *RaceHistoryUpdate {
	_u.mutation.SetRaceType(v)
	return _u
}

// SetNillableRaceType sets the "race_type" field if the given value is not nil.
func (_u *RaceHistoryUpdate) SetNillableRaceType(v *string) *RaceHistoryUpdate {
	if v != nil {
		_u.SetRaceType(*v)
	}
	return _u
}

// Mutation returns the RaceHistoryMutation object of the builder.
func (_u *RaceHistoryUpdate) Mutation() *RaceHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RaceHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RaceHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RaceHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RaceHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RaceHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(racehistory.Table, racehistory.Columns, sqlgraph.NewFieldSpec(racehistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(racehistory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RaceDate(); ok {
		_spec.SetField(racehistory.FieldRaceDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(racehistory.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Track(); ok {
		_spec.SetField(racehistory.FieldTrack, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackID(); ok {
		_spec.SetField(racehistory.FieldTrackID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalLaps(); ok {
		_spec.SetField(racehistory.FieldTotalLaps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalLaps(); ok {
		_spec.AddField(racehistory.FieldTotalLaps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RaceType(); ok {
		_spec.SetField(racehistory.FieldRaceType, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{racehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RaceHistoryUpdateOne is the builder for updating a single RaceHistory entity.
type RaceHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RaceHistoryMutation
}

// SetName sets the "name" field.
func (_u *RaceHistoryUpdateOne) SetName(v string) *RaceHistoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RaceHistoryUpdateOne) SetNillableName(v *string) *RaceHistoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRaceDate sets the "race_date" field.
func (_u *RaceHistoryUpdateOne) SetRaceDate(v string) *RaceHistoryUpdateOne {
	_u.mutation.SetRaceDate(v)
	return _u
}

// SetNillableRaceDate sets the "race_date" field if the given value is not nil.
func (_u *RaceHistoryUpdateOne) SetNillableRaceDate(v *string) *RaceHistoryUpdateOne {
	if v != nil {
		_u.SetRaceDate(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *RaceHistoryUpdateOne) SetCountry(v string) *RaceHistoryUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *RaceHistoryUpdateOne) SetNillableCountry(v *string) *RaceHistoryUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetTrack sets the "track" field.
func (_u *RaceHistoryUpdateOne) SetTrack(v string) *RaceHistoryUpdateOne {
	_u.mutation.SetTrack(v)
	return _u
}

// SetNillableTrack sets the "track" field if the given value is not nil.
func (_u *RaceHistoryUpdateOne) SetNillableTrack(v *string) *RaceHistoryUpdateOne {
	if v != nil {
		_u.SetTrack(*v)
	}
	return _u
}

// SetTrackID sets the "track_id" field.
func (_u *RaceHistoryUpdateOne) SetTrackID(v string) *RaceHistoryUpdateOne {
	_u.mutation.SetTrackID(v)
	return _u
}

// SetNillableTrackID sets the "track_id" field if the given value is not nil.
func (_u *RaceHistoryUpdateOne) SetNillableTrackID(v *string) *RaceHistoryUpdateOne {
	if v != nil {
		_u.SetTrackID(*v)
	}
	return _u
}

// SetTotalLaps sets the "total_laps" field.
func (_u *RaceHistoryUpdateOne) SetTotalLaps(v int) *RaceHistoryUpdateOne {
	_u.mutation.ResetTotalLaps()
	_u.mutation.SetTotalLaps(v)
	return _u
}

// SetNillableTotalLaps sets the "total_laps" field if the given value is not nil.
func (_u *RaceHistoryUpdateOne) SetNillableTotalLaps(v *int) *RaceHistoryUpdateOne {
	if v != nil {
		_u.SetTotalLaps(*v)
	}
	return _u
}

// AddTotalLaps adds value to the "total_laps" field.
func (_u *RaceHistoryUpdateOne) AddTotalLaps(v int) *RaceHistoryUpdateOne {
	_u.mutation.AddTotalLaps(v)
	return _u
}

// SetRaceType sets the "race_type" field.
func (_u *RaceHistoryUpdateOne) SetRaceType(v string) *RaceHistoryUpdateOne {
	_u.mutation.SetRaceType(v)
	return _u
}

// SetNillableRaceType sets the "race_type" field if the given value is not nil.
func (_u *RaceHistoryUpdateOne) SetNillableRaceType(v *string) *RaceHistoryUpdateOne {
	if v != nil {
		_u.SetRaceType(*v)
	}
	return _u
}

// Mutation returns the RaceHistoryMutation object of the builder.
func (_u *RaceHistoryUpdateOne) Mutation() *RaceHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the RaceHistoryUpdate builder.
func (_u *RaceHistoryUpdateOne) Where(ps ...predicate.RaceHistory) *RaceHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RaceHistoryUpdateOne) Select(field string, fields ...string) *RaceHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RaceHistory entity.
func (_u *RaceHistoryUpdateOne) Save(ctx context.Context) (*RaceHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RaceHistoryUpdateOne) SaveX(ctx context.Context) *RaceHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RaceHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RaceHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RaceHistoryUpdateOne) sqlSave(ctx context.Context) (_node *RaceHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(racehistory.Table, racehistory.Columns, sqlgraph.NewFieldSpec(racehistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RaceHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, racehistory.FieldID)
		for _, f := range fields {
			if !racehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != racehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(racehistory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RaceDate(); ok {
		_spec.SetField(racehistory.FieldRaceDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(racehistory.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Track(); ok {
		_spec.SetField(racehistory.FieldTrack, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackID(); ok {
		_spec.SetField(racehistory.FieldTrackID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalLaps(); ok {
		_spec.SetField(racehistory.FieldTotalLaps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalLaps(); ok {
		_spec.AddField(racehistory.FieldTotalLaps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RaceType(); ok {
		_spec.SetField(racehistory.FieldRaceType, field.TypeString, value)
	}
	_node = &RaceHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{racehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
