// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/predicate"
	"heat/ent/raceradio"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RaceRadioUpdate is the builder for updating RaceRadio entities.
type RaceRadioUpdate struct {
	config
	hooks    []Hook
	mutation *RaceRadioMutation
}

// Where appends a list predicates to the RaceRadioUpdate builder.
func (_u *RaceRadioUpdate) Where(ps ...predicate.RaceRadio) *RaceRadioUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRaceID sets the "race_id" field.
func (_u *RaceRadioUpdate) SetRaceID(v int) *RaceRadioUpdate {
	_u.mutation.ResetRaceID()
	_u.mutation.SetRaceID(v)
	return _u
}

// SetNillableRaceID sets the "race_id" field if the given value is not nil.
func (_u *RaceRadioUpdate) SetNillableRaceID(v *int) *RaceRadioUpdate {
	if v != nil {
		_u.SetRaceID(*v)
	}
	return _u
}

// AddRaceID adds value to the "race_id" field.
func (_u *RaceRadioUpdate) AddRaceID(v int) *RaceRadioUpdate {
	_u.mutation.AddRaceID(v)
	return _u
}

// SetRacerID sets the "racer_id" field.
func (_u *RaceRadioUpdate) SetRacerID(v int) *RaceRadioUpdate {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *RaceRadioUpdate) SetNillableRacerID(v *int) *RaceRadioUpdate {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *RaceRadioUpdate) AddRacerID(v int) *RaceRadioUpdate {
	_u.mutation.AddRacerID(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *RaceRadioUpdate) SetMessage(v string) *RaceRadioUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RaceRadioUpdate) SetNillableMessage(v *string) *RaceRadioUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RaceRadioUpdate) SetTimestamp(v string) *RaceRadioUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RaceRadioUpdate) SetNillableTimestamp(v *string) *RaceRadioUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the RaceRadioMutation object of the builder.
func (_u *RaceRadioUpdate) Mutation() *RaceRadioMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RaceRadioUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RaceRadioUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RaceRadioUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RaceRadioUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RaceRadioUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(raceradio.Table, raceradio.Columns, sqlgraph.NewFieldSpec(raceradio.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RaceID(); ok {
		_spec.SetField(raceradio.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRaceID(); ok {
		_spec.AddField(raceradio.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(raceradio.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(raceradio.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(raceradio.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(raceradio.FieldTimestamp, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raceradio.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RaceRadioUpdateOne is the builder for updating a single RaceRadio entity.
type RaceRadioUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RaceRadioMutation
}

// SetRaceID sets the "race_id" field.
func (_u *RaceRadioUpdateOne) SetRaceID(v int) *RaceRadioUpdateOne {
	_u.mutation.ResetRaceID()
	_u.mutation.SetRaceID(v)
	return _u
}

// SetNillableRaceID sets the "race_id" field if the given value is not nil.
func (_u *RaceRadioUpdateOne) SetNillableRaceID(v *int) *RaceRadioUpdateOne {
	if v != nil {
		_u.SetRaceID(*v)
	}
	return _u
}

// AddRaceID adds value to the "race_id" field.
func (_u *RaceRadioUpdateOne) AddRaceID(v int) *RaceRadioUpdateOne {
	_u.mutation.AddRaceID(v)
	return _u
}

// SetRacerID sets the "racer_id" field.
func (_u *RaceRadioUpdateOne) SetRacerID(v int) *RaceRadioUpdateOne {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *RaceRadioUpdateOne) SetNillableRacerID(v *int) *RaceRadioUpdateOne {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *RaceRadioUpdateOne) AddRacerID(v int) *RaceRadioUpdateOne {
	_u.mutation.AddRacerID(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *RaceRadioUpdateOne) SetMessage(v string) *RaceRadioUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *RaceRadioUpdateOne) SetNillableMessage(v *string) *RaceRadioUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RaceRadioUpdateOne) SetTimestamp(v string) *RaceRadioUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RaceRadioUpdateOne) SetNillableTimestamp(v *string) *RaceRadioUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the RaceRadioMutation object of the builder.
func (_u *RaceRadioUpdateOne) Mutation() *RaceRadioMutation {
	return _u.mutation
}

// Where appends a list predicates to the RaceRadioUpdate builder.
func (_u *RaceRadioUpdateOne) Where(ps ...predicate.RaceRadio) *RaceRadioUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RaceRadioUpdateOne) Select(field string, fields ...string) *RaceRadioUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RaceRadio entity.
func (_u *RaceRadioUpdateOne) Save(ctx context.Context) (*RaceRadio, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RaceRadioUpdateOne) SaveX(ctx context.Context) *RaceRadio {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RaceRadioUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RaceRadioUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RaceRadioUpdateOne) sqlSave(ctx context.Context) (_node *RaceRadio, err error) {
	_spec := sqlgraph.NewUpdateSpec(raceradio.Table, raceradio.Columns, sqlgraph.NewFieldSpec(raceradio.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RaceRadio.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, raceradio.FieldID)
		for _, f := range fields {
			if !raceradio.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != raceradio.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RaceID(); ok {
		_spec.SetField(raceradio.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRaceID(); ok {
		_spec.AddField(raceradio.FieldRaceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(raceradio.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(raceradio.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(raceradio.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(raceradio.FieldTimestamp, field.TypeString, value)
	}
	_node = &RaceRadio{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raceradio.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
