// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"heat/ent/predicate"
	"heat/ent/racerstats"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RacerStatsDelete is the builder for deleting a RacerStats entity.
type RacerStatsDelete struct {
	config
	hooks    []Hook
	mutation *RacerStatsMutation
}

// Where appends a list predicates to the RacerStatsDelete builder.
func (_d *RacerStatsDelete) Where(ps ...predicate.RacerStats) *RacerStatsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RacerStatsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RacerStatsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RacerStatsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(racerstats.Table, sqlgraph.NewFieldSpec(racerstats.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RacerStatsDeleteOne is the builder for deleting a single RacerStats entity.
type RacerStatsDeleteOne struct {
	_d *RacerStatsDelete
}

// Where appends a list predicates to the RacerStatsDelete builder.
func (_d *RacerStatsDeleteOne) Where(ps ...predicate.RacerStats) *RacerStatsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RacerStatsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{racerstats.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RacerStatsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
