// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/racerstats"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RacerStats is the model entity for the RacerStats schema.
type RacerStats struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RacerID holds the value of the "racer_id" field.
	RacerID int `json:"racer_id,omitempty"`
	// Races holds the value of the "races" field.
	Races int `json:"races,omitempty"`
	// Wins holds the value of the "wins" field.
	Wins int `json:"wins,omitempty"`
	// Gold holds the value of the "gold" field.
	Gold int `json:"gold,omitempty"`
	// Silver holds the value of the "silver" field.
	Silver int `json:"silver,omitempty"`
	// Bronze holds the value of the "bronze" field.
	Bronze int `json:"bronze,omitempty"`
	// FastestLaps holds the value of the "fastest_laps" field.
	FastestLaps int `json:"fastest_laps,omitempty"`
	// Points holds the value of the "points" field.
	Points int `json:"points,omitempty"`
	// Dnf holds the value of the "dnf" field.
	Dnf int `json:"dnf,omitempty"`
	// DNS holds the value of the "dns" field.
	DNS          int `json:"dns,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RacerStats) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case racerstats.FieldID, racerstats.FieldRacerID, racerstats.FieldRaces, racerstats.FieldWins, racerstats.FieldGold, racerstats.FieldSilver, racerstats.FieldBronze, racerstats.FieldFastestLaps, racerstats.FieldPoints, racerstats.FieldDnf, racerstats.FieldDNS:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RacerStats fields.
func (_m *RacerStats) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case racerstats.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case racerstats.FieldRacerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field racer_id", values[i])
			} else if value.Valid {
				_m.RacerID = int(value.Int64)
			}
		case racerstats.FieldRaces:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field races", values[i])
			} else if value.Valid {
				_m.Races = int(value.Int64)
			}
		case racerstats.FieldWins:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field wins", values[i])
			} else if value.Valid {
				_m.Wins = int(value.Int64)
			}
		case racerstats.FieldGold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gold", values[i])
			} else if value.Valid {
				_m.Gold = int(value.Int64)
			}
		case racerstats.FieldSilver:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field silver", values[i])
			} else if value.Valid {
				_m.Silver = int(value.Int64)
			}
		case racerstats.FieldBronze:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bronze", values[i])
			} else if value.Valid {
				_m.Bronze = int(value.Int64)
			}
		case racerstats.FieldFastestLaps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fastest_laps", values[i])
			} else if value.Valid {
				_m.FastestLaps = int(value.Int64)
			}
		case racerstats.FieldPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				_m.Points = int(value.Int64)
			}
		case racerstats.FieldDnf:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dnf", values[i])
			} else if value.Valid {
				_m.Dnf = int(value.Int64)
			}
		case racerstats.FieldDNS:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dns", values[i])
			} else if value.Valid {
				_m.DNS = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RacerStats.
// This includes values selected through modifiers, order, etc.
func (_m *RacerStats) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RacerStats.
// Note that you need to call RacerStats.Unwrap() before calling this method if this RacerStats
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RacerStats) Update() *RacerStatsUpdateOne {
	return NewRacerStatsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RacerStats entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RacerStats) Unwrap() *RacerStats {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RacerStats is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RacerStats) String() string {
	var builder strings.Builder
	builder.WriteString("RacerStats(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("racer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RacerID))
	builder.WriteString(", ")
	builder.WriteString("races=")
	builder.WriteString(fmt.Sprintf("%v", _m.Races))
	builder.WriteString(", ")
	builder.WriteString("wins=")
	builder.WriteString(fmt.Sprintf("%v", _m.Wins))
	builder.WriteString(", ")
	builder.WriteString("gold=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gold))
	builder.WriteString(", ")
	builder.WriteString("silver=")
	builder.WriteString(fmt.Sprintf("%v", _m.Silver))
	builder.WriteString(", ")
	builder.WriteString("bronze=")
	builder.WriteString(fmt.Sprintf("%v", _m.Bronze))
	builder.WriteString(", ")
	builder.WriteString("fastest_laps=")
	builder.WriteString(fmt.Sprintf("%v", _m.FastestLaps))
	builder.WriteString(", ")
	builder.WriteString("points=")
	builder.WriteString(fmt.Sprintf("%v", _m.Points))
	builder.WriteString(", ")
	builder.WriteString("dnf=")
	builder.WriteString(fmt.Sprintf("%v", _m.Dnf))
	builder.WriteString(", ")
	builder.WriteString("dns=")
	builder.WriteString(fmt.Sprintf("%v", _m.DNS))
	builder.WriteByte(')')
	return builder.String()
}

// RacerStatsSlice is a parsable slice of RacerStats.
type RacerStatsSlice []*RacerStats
