// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/raceevent"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RaceEventCreate is the builder for creating a RaceEvent entity.
type RaceEventCreate struct {
	config
	mutation *RaceEventMutation
	hooks    []Hook
}

// SetRaceID sets the "race_id" field.
func (_c *RaceEventCreate) SetRaceID(v int) *RaceEventCreate {
	_c.mutation.SetRaceID(v)
	return _c
}

// SetNillableRaceID sets the "race_id" field if the given value is not nil.
func (_c *RaceEventCreate) SetNillableRaceID(v *int) *RaceEventCreate {
	if v != nil {
		_c.SetRaceID(*v)
	}
	return _c
}

// SetLap sets the "lap" field.
func (_c *RaceEventCreate) SetLap(v int) *RaceEventCreate {
	_c.mutation.SetLap(v)
	return _c
}

// SetNillableLap sets the "lap" field if the given value is not nil.
func (_c *RaceEventCreate) SetNillableLap(v *int) *RaceEventCreate {
	if v != nil {
		_c.SetLap(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *RaceEventCreate) SetEventType(v string) *RaceEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetRacerID sets the "racer_id" field.
func (_c *RaceEventCreate) SetRacerID(v int) *RaceEventCreate {
	_c.mutation.SetRacerID(v)
	return _c
}

// SetRacerId2 sets the "racer_id2" field.
func (_c *RaceEventCreate) SetRacerId2(v int) *RaceEventCreate {
	_c.mutation.SetRacerId2(v)
	return _c
}

// SetNillableRacerId2 sets the "racer_id2" field if the given value is not nil.
func (_c *RaceEventCreate) SetNillableRacerId2(v *int) *RaceEventCreate {
	if v != nil {
		_c.SetRacerId2(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *RaceEventCreate) SetNote(v string) *RaceEventCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *RaceEventCreate) SetNillableNote(v *string) *RaceEventCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *RaceEventCreate) SetTimestamp(v string) *RaceEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *RaceEventCreate) SetNillableTimestamp(v *string) *RaceEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RaceEventCreate) SetID(v int) *RaceEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RaceEventMutation object of the builder.
func (_c *RaceEventCreate) Mutation() *RaceEventMutation {
	return _c.mutation
}

// Save creates the RaceEvent in the database.
func (_c *RaceEventCreate) Save(ctx context.Context) (*RaceEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RaceEventCreate) SaveX(ctx context.Context) *RaceEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RaceEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RaceEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RaceEventCreate) defaults() {
	if _, ok := _c.mutation.RaceID(); !ok {
		v := raceevent.DefaultRaceID
		_c.mutation.SetRaceID(v)
	}
	if _, ok := _c.mutation.Lap(); !ok {
		v := raceevent.DefaultLap
		_c.mutation.SetLap(v)
	}
	if _, ok := _c.mutation.RacerId2(); !ok {
		v := raceevent.DefaultRacerId2
		_c.mutation.SetRacerId2(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := raceevent.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := raceevent.DefaultTimestamp
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RaceEventCreate) check() error {
	if _, ok := _c.mutation.RaceID(); !ok {
		return &ValidationError{Name: "race_id", err: errors.New(`ent: missing required field "RaceEvent.race_id"`)}
	}
	if _, ok := _c.mutation.Lap(); !ok {
		return &ValidationError{Name: "lap", err: errors.New(`ent: missing required field "RaceEvent.lap"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "RaceEvent.event_type"`)}
	}
	if _, ok := _c.mutation.RacerID(); !ok {
		return &ValidationError{Name: "racer_id", err: errors.New(`ent: missing required field "RaceEvent.racer_id"`)}
	}
	if _, ok := _c.mutation.RacerId2(); !ok {
		return &ValidationError{Name: "racer_id2", err: errors.New(`ent: missing required field "RaceEvent.racer_id2"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "RaceEvent.note"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "RaceEvent.timestamp"`)}
	}
	return nil
}

func (_c *RaceEventCreate) sqlSave(ctx context.Context) (*RaceEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RaceEventCreate) createSpec() (*RaceEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &RaceEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(raceevent.Table, sqlgraph.NewFieldSpec(raceevent.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RaceID(); ok {
		_spec.SetField(raceevent.FieldRaceID, field.TypeInt, value)
		_node.RaceID = value
	}
	if value, ok := _c.mutation.Lap(); ok {
		_spec.SetField(raceevent.FieldLap, field.TypeInt, value)
		_node.Lap = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(raceevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.RacerID(); ok {
		_spec.SetField(raceevent.FieldRacerID, field.TypeInt, value)
		_node.RacerID = value
	}
	if value, ok := _c.mutation.RacerId2(); ok {
		_spec.SetField(raceevent.FieldRacerId2, field.TypeInt, value)
		_node.RacerId2 = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(raceevent.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(raceevent.FieldTimestamp, field.TypeString, value)
		_node.Timestamp = value
	}
	return _node, _spec
}

// RaceEventCreateBulk is the builder for creating many RaceEvent entities in bulk.
type RaceEventCreateBulk struct {
	config
	err      error
	builders []*RaceEventCreate
}

// Save creates the RaceEvent entities in the database.
func (_c *RaceEventCreateBulk) Save(ctx context.Context) ([]*RaceEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RaceEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RaceEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RaceEventCreateBulk) SaveX(ctx context.Context) []*RaceEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RaceEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RaceEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
