// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"heat/ent/predicate"
	"heat/ent/raceinfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RaceInfoDelete is the builder for deleting a RaceInfo entity.
type RaceInfoDelete struct {
	config
	hooks    []Hook
	mutation *RaceInfoMutation
}

// Where appends a list predicates to the RaceInfoDelete builder.
func (_d *RaceInfoDelete) Where(ps ...predicate.RaceInfo) *RaceInfoDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RaceInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RaceInfoDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RaceInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(raceinfo.Table, sqlgraph.NewFieldSpec(raceinfo.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RaceInfoDeleteOne is the builder for deleting a single RaceInfo entity.
type RaceInfoDeleteOne struct {
	_d *RaceInfoDelete
}

// Where appends a list predicates to the RaceInfoDelete builder.
func (_d *RaceInfoDeleteOne) Where(ps ...predicate.RaceInfo) *RaceInfoDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RaceInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{raceinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RaceInfoDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
