// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/predicate"
	"heat/ent/raceremail"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RacerEmailUpdate is the builder for updating RacerEmail entities.
type RacerEmailUpdate struct {
	config
	hooks    []Hook
	mutation *RacerEmailMutation
}

// Where appends a list predicates to the RacerEmailUpdate builder.
func (_u *RacerEmailUpdate) Where(ps ...predicate.RacerEmail) *RacerEmailUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRacerID sets the "racer_id" field.
func (_u *RacerEmailUpdate) SetRacerID(v int) *RacerEmailUpdate {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *RacerEmailUpdate) SetNillableRacerID(v *int) *RacerEmailUpdate {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *RacerEmailUpdate) AddRacerID(v int) *RacerEmailUpdate {
	_u.mutation.AddRacerID(v)
	return _u
}

// ClearRacerID clears the value of the "racer_id" field.
func (_u *RacerEmailUpdate) ClearRacerID() *RacerEmailUpdate {
	_u.mutation.ClearRacerID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *RacerEmailUpdate) SetEmail(v string) *RacerEmailUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *RacerEmailUpdate) SetNillableEmail(v *string) *RacerEmailUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *RacerEmailUpdate) ClearEmail() *RacerEmailUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// Mutation returns the RacerEmailMutation object of the builder.
func (_u *RacerEmailUpdate) Mutation() *RacerEmailMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RacerEmailUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RacerEmailUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RacerEmailUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RacerEmailUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RacerEmailUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(raceremail.Table, raceremail.Columns, sqlgraph.NewFieldSpec(raceremail.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(raceremail.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(raceremail.FieldRacerID, field.TypeInt, value)
	}
	if _u.mutation.RacerIDCleared() {
		_spec.ClearField(raceremail.FieldRacerID, field.TypeInt)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(raceremail.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(raceremail.FieldEmail, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raceremail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RacerEmailUpdateOne is the builder for updating a single RacerEmail entity.
type RacerEmailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RacerEmailMutation
}

// SetRacerID sets the "racer_id" field.
func (_u *RacerEmailUpdateOne) SetRacerID(v int) *RacerEmailUpdateOne {
	_u.mutation.ResetRacerID()
	_u.mutation.SetRacerID(v)
	return _u
}

// SetNillableRacerID sets the "racer_id" field if the given value is not nil.
func (_u *RacerEmailUpdateOne) SetNillableRacerID(v *int) *RacerEmailUpdateOne {
	if v != nil {
		_u.SetRacerID(*v)
	}
	return _u
}

// AddRacerID adds value to the "racer_id" field.
func (_u *RacerEmailUpdateOne) AddRacerID(v int) *RacerEmailUpdateOne {
	_u.mutation.AddRacerID(v)
	return _u
}

// ClearRacerID clears the value of the "racer_id" field.
func (_u *RacerEmailUpdateOne) ClearRacerID() *RacerEmailUpdateOne {
	_u.mutation.ClearRacerID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *RacerEmailUpdateOne) SetEmail(v string) *RacerEmailUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *RacerEmailUpdateOne) SetNillableEmail(v *string) *RacerEmailUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *RacerEmailUpdateOne) ClearEmail() *RacerEmailUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// Mutation returns the RacerEmailMutation object of the builder.
func (_u *RacerEmailUpdateOne) Mutation() *RacerEmailMutation {
	return _u.mutation
}

// Where appends a list predicates to the RacerEmailUpdate builder.
func (_u *RacerEmailUpdateOne) Where(ps ...predicate.RacerEmail) *RacerEmailUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RacerEmailUpdateOne) Select(field string, fields ...string) *RacerEmailUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RacerEmail entity.
func (_u *RacerEmailUpdateOne) Save(ctx context.Context) (*RacerEmail, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RacerEmailUpdateOne) SaveX(ctx context.Context) *RacerEmail {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RacerEmailUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RacerEmailUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RacerEmailUpdateOne) sqlSave(ctx context.Context) (_node *RacerEmail, err error) {
	_spec := sqlgraph.NewUpdateSpec(raceremail.Table, raceremail.Columns, sqlgraph.NewFieldSpec(raceremail.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RacerEmail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, raceremail.FieldID)
		for _, f := range fields {
			if !raceremail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != raceremail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RacerID(); ok {
		_spec.SetField(raceremail.FieldRacerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRacerID(); ok {
		_spec.AddField(raceremail.FieldRacerID, field.TypeInt, value)
	}
	if _u.mutation.RacerIDCleared() {
		_spec.ClearField(raceremail.FieldRacerID, field.TypeInt)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(raceremail.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(raceremail.FieldEmail, field.TypeString)
	}
	_node = &RacerEmail{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raceremail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
