// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/predicate"
	"heat/ent/raceinfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RaceInfoUpdate is the builder for updating RaceInfo entities.
type RaceInfoUpdate struct {
	config
	hooks    []Hook
	mutation *RaceInfoMutation
}

// Where appends a list predicates to the RaceInfoUpdate builder.
func (_u *RaceInfoUpdate) Where(ps ...predicate.RaceInfo) *RaceInfoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCountry sets the "country" field.
func (_u *RaceInfoUpdate) SetCountry(v string) *RaceInfoUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *RaceInfoUpdate) SetNillableCountry(v *string) *RaceInfoUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetTrack sets the "track" field.
func (_u *RaceInfoUpdate) SetTrack(v string) *RaceInfoUpdate {
	_u.mutation.SetTrack(v)
	return _u
}

// SetNillableTrack sets the "track" field if the given value is not nil.
func (_u *RaceInfoUpdate) SetNillableTrack(v *string) *RaceInfoUpdate {
	if v != nil {
		_u.SetTrack(*v)
	}
	return _u
}

// SetTrackID sets the "track_id" field.
func (_u *RaceInfoUpdate) SetTrackID(v string) *RaceInfoUpdate {
	_u.mutation.SetTrackID(v)
	return _u
}

// SetNillableTrackID sets the "track_id" field if the given value is not nil.
func (_u *RaceInfoUpdate) SetNillableTrackID(v *string) *RaceInfoUpdate {
	if v != nil {
		_u.SetTrackID(*v)
	}
	return _u
}

// SetLaps sets the "laps" field.
func (_u *RaceInfoUpdate) SetLaps(v int) *RaceInfoUpdate {
	_u.mutation.ResetLaps()
	_u.mutation.SetLaps(v)
	return _u
}

// SetNillableLaps sets the "laps" field if the given value is not nil.
func (_u *RaceInfoUpdate) SetNillableLaps(v *int) *RaceInfoUpdate {
	if v != nil {
		_u.SetLaps(*v)
	}
	return _u
}

// AddLaps adds value to the "laps" field.
func (_u *RaceInfoUpdate) AddLaps(v int) *RaceInfoUpdate {
	_u.mutation.AddLaps(v)
	return _u
}

// Mutation returns the RaceInfoMutation object of the builder.
func (_u *RaceInfoUpdate) Mutation() *RaceInfoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RaceInfoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RaceInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RaceInfoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RaceInfoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RaceInfoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(raceinfo.Table, raceinfo.Columns, sqlgraph.NewFieldSpec(raceinfo.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(raceinfo.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Track(); ok {
		_spec.SetField(raceinfo.FieldTrack, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackID(); ok {
		_spec.SetField(raceinfo.FieldTrackID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Laps(); ok {
		_spec.SetField(raceinfo.FieldLaps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLaps(); ok {
		_spec.AddField(raceinfo.FieldLaps, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raceinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RaceInfoUpdateOne is the builder for updating a single RaceInfo entity.
type RaceInfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RaceInfoMutation
}

// SetCountry sets the "country" field.
func (_u *RaceInfoUpdateOne) SetCountry(v string) *RaceInfoUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *RaceInfoUpdateOne) SetNillableCountry(v *string) *RaceInfoUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetTrack sets the "track" field.
func (_u *RaceInfoUpdateOne) SetTrack(v string) *RaceInfoUpdateOne {
	_u.mutation.SetTrack(v)
	return _u
}

// SetNillableTrack sets the "track" field if the given value is not nil.
func (_u *RaceInfoUpdateOne) SetNillableTrack(v *string) *RaceInfoUpdateOne {
	if v != nil {
		_u.SetTrack(*v)
	}
	return _u
}

// SetTrackID sets the "track_id" field.
func (_u *RaceInfoUpdateOne) SetTrackID(v string) *RaceInfoUpdateOne {
	_u.mutation.SetTrackID(v)
	return _u
}

// SetNillableTrackID sets the "track_id" field if the given value is not nil.
func (_u *RaceInfoUpdateOne) SetNillableTrackID(v *string) *RaceInfoUpdateOne {
	if v != nil {
		_u.SetTrackID(*v)
	}
	return _u
}

// SetLaps sets the "laps" field.
func (_u *RaceInfoUpdateOne) SetLaps(v int) *RaceInfoUpdateOne {
	_u.mutation.ResetLaps()
	_u.mutation.SetLaps(v)
	return _u
}

// SetNillableLaps sets the "laps" field if the given value is not nil.
func (_u *RaceInfoUpdateOne) SetNillableLaps(v *int) *RaceInfoUpdateOne {
	if v != nil {
		_u.SetLaps(*v)
	}
	return _u
}

// AddLaps adds value to the "laps" field.
func (_u *RaceInfoUpdateOne) AddLaps(v int) *RaceInfoUpdateOne {
	_u.mutation.AddLaps(v)
	return _u
}

// Mutation returns the RaceInfoMutation object of the builder.
func (_u *RaceInfoUpdateOne) Mutation() *RaceInfoMutation {
	return _u.mutation
}

// Where appends a list predicates to the RaceInfoUpdate builder.
func (_u *RaceInfoUpdateOne) Where(ps ...predicate.RaceInfo) *RaceInfoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RaceInfoUpdateOne) Select(field string, fields ...string) *RaceInfoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RaceInfo entity.
func (_u *RaceInfoUpdateOne) Save(ctx context.Context) (*RaceInfo, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RaceInfoUpdateOne) SaveX(ctx context.Context) *RaceInfo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RaceInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RaceInfoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RaceInfoUpdateOne) sqlSave(ctx context.Context) (_node *RaceInfo, err error) {
	_spec := sqlgraph.NewUpdateSpec(raceinfo.Table, raceinfo.Columns, sqlgraph.NewFieldSpec(raceinfo.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RaceInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, raceinfo.FieldID)
		for _, f := range fields {
			if !raceinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != raceinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(raceinfo.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Track(); ok {
		_spec.SetField(raceinfo.FieldTrack, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrackID(); ok {
		_spec.SetField(raceinfo.FieldTrackID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Laps(); ok {
		_spec.SetField(raceinfo.FieldLaps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLaps(); ok {
		_spec.AddField(raceinfo.FieldLaps, field.TypeInt, value)
	}
	_node = &RaceInfo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raceinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
