// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/racehistory"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RaceHistory is the model entity for the RaceHistory schema.
type RaceHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// RaceDate holds the value of the "race_date" field.
	RaceDate string `json:"race_date,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// Track holds the value of the "track" field.
	Track string `json:"track,omitempty"`
	// TrackID holds the value of the "track_id" field.
	TrackID string `json:"track_id,omitempty"`
	// TotalLaps holds the value of the "total_laps" field.
	TotalLaps int `json:"total_laps,omitempty"`
	// RaceType holds the value of the "race_type" field.
	RaceType     string `json:"race_type,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RaceHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case racehistory.FieldID, racehistory.FieldTotalLaps:
			values[i] = new(sql.NullInt64)
		case racehistory.FieldName, racehistory.FieldRaceDate, racehistory.FieldCountry, racehistory.FieldTrack, racehistory.FieldTrackID, racehistory.FieldRaceType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RaceHistory fields.
func (_m *RaceHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case racehistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case racehistory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case racehistory.FieldRaceDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field race_date", values[i])
			} else if value.Valid {
				_m.RaceDate = value.String
			}
		case racehistory.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case racehistory.FieldTrack:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field track", values[i])
			} else if value.Valid {
				_m.Track = value.String
			}
		case racehistory.FieldTrackID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field track_id", values[i])
			} else if value.Valid {
				_m.TrackID = value.String
			}
		case racehistory.FieldTotalLaps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_laps", values[i])
			} else if value.Valid {
				_m.TotalLaps = int(value.Int64)
			}
		case racehistory.FieldRaceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field race_type", values[i])
			} else if value.Valid {
				_m.RaceType = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RaceHistory.
// This includes values selected through modifiers, order, etc.
func (_m *RaceHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RaceHistory.
// Note that you need to call RaceHistory.Unwrap() before calling this method if this RaceHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RaceHistory) Update() *RaceHistoryUpdateOne {
	return NewRaceHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RaceHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RaceHistory) Unwrap() *RaceHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RaceHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RaceHistory) String() string {
	var builder strings.Builder
	builder.WriteString("RaceHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("race_date=")
	builder.WriteString(_m.RaceDate)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("track=")
	builder.WriteString(_m.Track)
	builder.WriteString(", ")
	builder.WriteString("track_id=")
	builder.WriteString(_m.TrackID)
	builder.WriteString(", ")
	builder.WriteString("total_laps=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalLaps))
	builder.WriteString(", ")
	builder.WriteString("race_type=")
	builder.WriteString(_m.RaceType)
	builder.WriteByte(')')
	return builder.String()
}

// RaceHistories is a parsable slice of RaceHistory.
type RaceHistories []*RaceHistory
