// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"heat/ent/predicate"
	"heat/ent/roundsnapshotscore"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoundSnapshotScoreDelete is the builder for deleting a RoundSnapshotScore entity.
type RoundSnapshotScoreDelete struct {
	config
	hooks    []Hook
	mutation *RoundSnapshotScoreMutation
}

// Where appends a list predicates to the RoundSnapshotScoreDelete builder.
func (_d *RoundSnapshotScoreDelete) Where(ps ...predicate.RoundSnapshotScore) *RoundSnapshotScoreDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RoundSnapshotScoreDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoundSnapshotScoreDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RoundSnapshotScoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(roundsnapshotscore.Table, sqlgraph.NewFieldSpec(roundsnapshotscore.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RoundSnapshotScoreDeleteOne is the builder for deleting a single RoundSnapshotScore entity.
type RoundSnapshotScoreDeleteOne struct {
	_d *RoundSnapshotScoreDelete
}

// Where appends a list predicates to the RoundSnapshotScoreDelete builder.
func (_d *RoundSnapshotScoreDeleteOne) Where(ps ...predicate.RoundSnapshotScore) *RoundSnapshotScoreDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RoundSnapshotScoreDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{roundsnapshotscore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoundSnapshotScoreDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
