// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/roundsnapshot"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoundSnapshotCreate is the builder for creating a RoundSnapshot entity.
type RoundSnapshotCreate struct {
	config
	mutation *RoundSnapshotMutation
	hooks    []Hook
}

// SetRaceName sets the "race_name" field.
func (_c *RoundSnapshotCreate) SetRaceName(v string) *RoundSnapshotCreate {
	_c.mutation.SetRaceName(v)
	return _c
}

// SetRaceDate sets the "race_date" field.
func (_c *RoundSnapshotCreate) SetRaceDate(v string) *RoundSnapshotCreate {
	_c.mutation.SetRaceDate(v)
	return _c
}

// SetRound sets the "round" field.
func (_c *RoundSnapshotCreate) SetRound(v int) *RoundSnapshotCreate {
	_c.mutation.SetRound(v)
	return _c
}

// SetNillableRound sets the "round" field if the given value is not nil.
func (_c *RoundSnapshotCreate) SetNillableRound(v *int) *RoundSnapshotCreate {
	if v != nil {
		_c.SetRound(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoundSnapshotCreate) SetCreatedAt(v string) *RoundSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoundSnapshotCreate) SetNillableCreatedAt(v *string) *RoundSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSeasonID sets the "season_id" field.
func (_c *RoundSnapshotCreate) SetSeasonID(v int) *RoundSnapshotCreate {
	_c.mutation.SetSeasonID(v)
	return _c
}

// SetNillableSeasonID sets the "season_id" field if the given value is not nil.
func (_c *RoundSnapshotCreate) SetNillableSeasonID(v *int) *RoundSnapshotCreate {
	if v != nil {
		_c.SetSeasonID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoundSnapshotCreate) SetID(v int) *RoundSnapshotCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RoundSnapshotMutation object of the builder.
func (_c *RoundSnapshotCreate) Mutation() *RoundSnapshotMutation {
	return _c.mutation
}

// Save creates the RoundSnapshot in the database.
func (_c *RoundSnapshotCreate) Save(ctx context.Context) (*RoundSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoundSnapshotCreate) SaveX(ctx context.Context) *RoundSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoundSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoundSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoundSnapshotCreate) defaults() {
	if _, ok := _c.mutation.Round(); !ok {
		v := roundsnapshot.DefaultRound
		_c.mutation.SetRound(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := roundsnapshot.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.SeasonID(); !ok {
		v := roundsnapshot.DefaultSeasonID
		_c.mutation.SetSeasonID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoundSnapshotCreate) check() error {
	if _, ok := _c.mutation.RaceName(); !ok {
		return &ValidationError{Name: "race_name", err: errors.New(`ent: missing required field "RoundSnapshot.race_name"`)}
	}
	if _, ok := _c.mutation.RaceDate(); !ok {
		return &ValidationError{Name: "race_date", err: errors.New(`ent: missing required field "RoundSnapshot.race_date"`)}
	}
	if _, ok := _c.mutation.Round(); !ok {
		return &ValidationError{Name: "round", err: errors.New(`ent: missing required field "RoundSnapshot.round"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RoundSnapshot.created_at"`)}
	}
	return nil
}

func (_c *RoundSnapshotCreate) sqlSave(ctx context.Context) (*RoundSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoundSnapshotCreate) createSpec() (*RoundSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &RoundSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(roundsnapshot.Table, sqlgraph.NewFieldSpec(roundsnapshot.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RaceName(); ok {
		_spec.SetField(roundsnapshot.FieldRaceName, field.TypeString, value)
		_node.RaceName = value
	}
	if value, ok := _c.mutation.RaceDate(); ok {
		_spec.SetField(roundsnapshot.FieldRaceDate, field.TypeString, value)
		_node.RaceDate = value
	}
	if value, ok := _c.mutation.Round(); ok {
		_spec.SetField(roundsnapshot.FieldRound, field.TypeInt, value)
		_node.Round = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(roundsnapshot.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.SeasonID(); ok {
		_spec.SetField(roundsnapshot.FieldSeasonID, field.TypeInt, value)
		_node.SeasonID = value
	}
	return _node, _spec
}

// RoundSnapshotCreateBulk is the builder for creating many RoundSnapshot entities in bulk.
type RoundSnapshotCreateBulk struct {
	config
	err      error
	builders []*RoundSnapshotCreate
}

// Save creates the RoundSnapshot entities in the database.
func (_c *RoundSnapshotCreateBulk) Save(ctx context.Context) ([]*RoundSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoundSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoundSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoundSnapshotCreateBulk) SaveX(ctx context.Context) []*RoundSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoundSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoundSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
