// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// AISetting is the client for interacting with the AISetting builders.
	AISetting *AISettingClient
	// AdminUser is the client for interacting with the AdminUser builders.
	AdminUser *AdminUserClient
	// BackupSetting is the client for interacting with the BackupSetting builders.
	BackupSetting *BackupSettingClient
	// DriverShare is the client for interacting with the DriverShare builders.
	DriverShare *DriverShareClient
	// EmailSetting is the client for interacting with the EmailSetting builders.
	EmailSetting *EmailSettingClient
	// GearShift is the client for interacting with the GearShift builders.
	GearShift *GearShiftClient
	// HeatCard is the client for interacting with the HeatCard builders.
	HeatCard *HeatCardClient
	// LapRecord is the client for interacting with the LapRecord builders.
	LapRecord *LapRecordClient
	// LegendAbility is the client for interacting with the LegendAbility builders.
	LegendAbility *LegendAbilityClient
	// NotificationSetting is the client for interacting with the NotificationSetting builders.
	NotificationSetting *NotificationSettingClient
	// OTelSetting is the client for interacting with the OTelSetting builders.
	OTelSetting *OTelSettingClient
	// PlayerSession is the client for interacting with the PlayerSession builders.
	PlayerSession *PlayerSessionClient
	// PlayerUpgrade is the client for interacting with the PlayerUpgrade builders.
	PlayerUpgrade *PlayerUpgradeClient
	// Quote is the client for interacting with the Quote builders.
	Quote *QuoteClient
	// RaceEvent is the client for interacting with the RaceEvent builders.
	RaceEvent *RaceEventClient
	// RaceHistory is the client for interacting with the RaceHistory builders.
	RaceHistory *RaceHistoryClient
	// RaceInfo is the client for interacting with the RaceInfo builders.
	RaceInfo *RaceInfoClient
	// RaceRadio is the client for interacting with the RaceRadio builders.
	RaceRadio *RaceRadioClient
	// RaceResult is the client for interacting with the RaceResult builders.
	RaceResult *RaceResultClient
	// Racer is the client for interacting with the Racer builders.
	Racer *RacerClient
	// RacerEmail is the client for interacting with the RacerEmail builders.
	RacerEmail *RacerEmailClient
	// RacerLegendAbility is the client for interacting with the RacerLegendAbility builders.
	RacerLegendAbility *RacerLegendAbilityClient
	// RacerSector is the client for interacting with the RacerSector builders.
	RacerSector *RacerSectorClient
	// RacerStats is the client for interacting with the RacerStats builders.
	RacerStats *RacerStatsClient
	// RoundSnapshot is the client for interacting with the RoundSnapshot builders.
	RoundSnapshot *RoundSnapshotClient
	// RoundSnapshotScore is the client for interacting with the RoundSnapshotScore builders.
	RoundSnapshotScore *RoundSnapshotScoreClient
	// Season is the client for interacting with the Season builders.
	Season *SeasonClient
	// Sector is the client for interacting with the Sector builders.
	Sector *SectorClient
	// Team is the client for interacting with the Team builders.
	Team *TeamClient
	// Track is the client for interacting with the Track builders.
	Track *TrackClient
	// TurboLog is the client for interacting with the TurboLog builders.
	TurboLog *TurboLogClient
	// UmamiSetting is the client for interacting with the UmamiSetting builders.
	UmamiSetting *UmamiSettingClient
	// UpgradeCard is the client for interacting with the UpgradeCard builders.
	UpgradeCard *UpgradeCardClient
	// Upload is the client for interacting with the Upload builders.
	Upload *UploadClient
	// WeatherCondition is the client for interacting with the WeatherCondition builders.
	WeatherCondition *WeatherConditionClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.AISetting = NewAISettingClient(tx.config)
	tx.AdminUser = NewAdminUserClient(tx.config)
	tx.BackupSetting = NewBackupSettingClient(tx.config)
	tx.DriverShare = NewDriverShareClient(tx.config)
	tx.EmailSetting = NewEmailSettingClient(tx.config)
	tx.GearShift = NewGearShiftClient(tx.config)
	tx.HeatCard = NewHeatCardClient(tx.config)
	tx.LapRecord = NewLapRecordClient(tx.config)
	tx.LegendAbility = NewLegendAbilityClient(tx.config)
	tx.NotificationSetting = NewNotificationSettingClient(tx.config)
	tx.OTelSetting = NewOTelSettingClient(tx.config)
	tx.PlayerSession = NewPlayerSessionClient(tx.config)
	tx.PlayerUpgrade = NewPlayerUpgradeClient(tx.config)
	tx.Quote = NewQuoteClient(tx.config)
	tx.RaceEvent = NewRaceEventClient(tx.config)
	tx.RaceHistory = NewRaceHistoryClient(tx.config)
	tx.RaceInfo = NewRaceInfoClient(tx.config)
	tx.RaceRadio = NewRaceRadioClient(tx.config)
	tx.RaceResult = NewRaceResultClient(tx.config)
	tx.Racer = NewRacerClient(tx.config)
	tx.RacerEmail = NewRacerEmailClient(tx.config)
	tx.RacerLegendAbility = NewRacerLegendAbilityClient(tx.config)
	tx.RacerSector = NewRacerSectorClient(tx.config)
	tx.RacerStats = NewRacerStatsClient(tx.config)
	tx.RoundSnapshot = NewRoundSnapshotClient(tx.config)
	tx.RoundSnapshotScore = NewRoundSnapshotScoreClient(tx.config)
	tx.Season = NewSeasonClient(tx.config)
	tx.Sector = NewSectorClient(tx.config)
	tx.Team = NewTeamClient(tx.config)
	tx.Track = NewTrackClient(tx.config)
	tx.TurboLog = NewTurboLogClient(tx.config)
	tx.UmamiSetting = NewUmamiSettingClient(tx.config)
	tx.UpgradeCard = NewUpgradeCardClient(tx.config)
	tx.Upload = NewUploadClient(tx.config)
	tx.WeatherCondition = NewWeatherConditionClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: AISetting.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)
