// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"heat/ent/predicate"
	"heat/ent/umamisetting"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UmamiSettingDelete is the builder for deleting a UmamiSetting entity.
type UmamiSettingDelete struct {
	config
	hooks    []Hook
	mutation *UmamiSettingMutation
}

// Where appends a list predicates to the UmamiSettingDelete builder.
func (_d *UmamiSettingDelete) Where(ps ...predicate.UmamiSetting) *UmamiSettingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UmamiSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UmamiSettingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UmamiSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(umamisetting.Table, sqlgraph.NewFieldSpec(umamisetting.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UmamiSettingDeleteOne is the builder for deleting a single UmamiSetting entity.
type UmamiSettingDeleteOne struct {
	_d *UmamiSettingDelete
}

// Where appends a list predicates to the UmamiSettingDelete builder.
func (_d *UmamiSettingDeleteOne) Where(ps ...predicate.UmamiSetting) *UmamiSettingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UmamiSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{umamisetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UmamiSettingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
