// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/umamisetting"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UmamiSettingCreate is the builder for creating a UmamiSetting entity.
type UmamiSettingCreate struct {
	config
	mutation *UmamiSettingMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (_c *UmamiSettingCreate) SetURL(v string) *UmamiSettingCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *UmamiSettingCreate) SetNillableURL(v *string) *UmamiSettingCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetWebsiteID sets the "website_id" field.
func (_c *UmamiSettingCreate) SetWebsiteID(v string) *UmamiSettingCreate {
	_c.mutation.SetWebsiteID(v)
	return _c
}

// SetNillableWebsiteID sets the "website_id" field if the given value is not nil.
func (_c *UmamiSettingCreate) SetNillableWebsiteID(v *string) *UmamiSettingCreate {
	if v != nil {
		_c.SetWebsiteID(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UmamiSettingCreate) SetEnabled(v int) *UmamiSettingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UmamiSettingCreate) SetNillableEnabled(v *int) *UmamiSettingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UmamiSettingCreate) SetID(v int) *UmamiSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UmamiSettingMutation object of the builder.
func (_c *UmamiSettingCreate) Mutation() *UmamiSettingMutation {
	return _c.mutation
}

// Save creates the UmamiSetting in the database.
func (_c *UmamiSettingCreate) Save(ctx context.Context) (*UmamiSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UmamiSettingCreate) SaveX(ctx context.Context) *UmamiSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UmamiSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UmamiSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UmamiSettingCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := umamisetting.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UmamiSettingCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UmamiSetting.enabled"`)}
	}
	return nil
}

func (_c *UmamiSettingCreate) sqlSave(ctx context.Context) (*UmamiSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UmamiSettingCreate) createSpec() (*UmamiSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &UmamiSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(umamisetting.Table, sqlgraph.NewFieldSpec(umamisetting.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(umamisetting.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.WebsiteID(); ok {
		_spec.SetField(umamisetting.FieldWebsiteID, field.TypeString, value)
		_node.WebsiteID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(umamisetting.FieldEnabled, field.TypeInt, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// UmamiSettingCreateBulk is the builder for creating many UmamiSetting entities in bulk.
type UmamiSettingCreateBulk struct {
	config
	err      error
	builders []*UmamiSettingCreate
}

// Save creates the UmamiSetting entities in the database.
func (_c *UmamiSettingCreateBulk) Save(ctx context.Context) ([]*UmamiSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UmamiSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UmamiSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UmamiSettingCreateBulk) SaveX(ctx context.Context) []*UmamiSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UmamiSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UmamiSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
