// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/upgradecard"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeCardCreate is the builder for creating a UpgradeCard entity.
type UpgradeCardCreate struct {
	config
	mutation *UpgradeCardMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *UpgradeCardCreate) SetName(v string) *UpgradeCardCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *UpgradeCardCreate) SetDescription(v string) *UpgradeCardCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetCardType sets the "card_type" field.
func (_c *UpgradeCardCreate) SetCardType(v string) *UpgradeCardCreate {
	_c.mutation.SetCardType(v)
	return _c
}

// SetNillableCardType sets the "card_type" field if the given value is not nil.
func (_c *UpgradeCardCreate) SetNillableCardType(v *string) *UpgradeCardCreate {
	if v != nil {
		_c.SetCardType(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *UpgradeCardCreate) SetCost(v int) *UpgradeCardCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *UpgradeCardCreate) SetNillableCost(v *int) *UpgradeCardCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetEffects sets the "effects" field.
func (_c *UpgradeCardCreate) SetEffects(v string) *UpgradeCardCreate {
	_c.mutation.SetEffects(v)
	return _c
}

// SetNillableEffects sets the "effects" field if the given value is not nil.
func (_c *UpgradeCardCreate) SetNillableEffects(v *string) *UpgradeCardCreate {
	if v != nil {
		_c.SetEffects(*v)
	}
	return _c
}

// SetExtensionID sets the "extension_id" field.
func (_c *UpgradeCardCreate) SetExtensionID(v int) *UpgradeCardCreate {
	_c.mutation.SetExtensionID(v)
	return _c
}

// SetNillableExtensionID sets the "extension_id" field if the given value is not nil.
func (_c *UpgradeCardCreate) SetNillableExtensionID(v *int) *UpgradeCardCreate {
	if v != nil {
		_c.SetExtensionID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UpgradeCardCreate) SetID(v int) *UpgradeCardCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UpgradeCardMutation object of the builder.
func (_c *UpgradeCardCreate) Mutation() *UpgradeCardMutation {
	return _c.mutation
}

// Save creates the UpgradeCard in the database.
func (_c *UpgradeCardCreate) Save(ctx context.Context) (*UpgradeCard, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpgradeCardCreate) SaveX(ctx context.Context) *UpgradeCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpgradeCardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpgradeCardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpgradeCardCreate) defaults() {
	if _, ok := _c.mutation.CardType(); !ok {
		v := upgradecard.DefaultCardType
		_c.mutation.SetCardType(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := upgradecard.DefaultCost
		_c.mutation.SetCost(v)
	}
	if _, ok := _c.mutation.Effects(); !ok {
		v := upgradecard.DefaultEffects
		_c.mutation.SetEffects(v)
	}
	if _, ok := _c.mutation.ExtensionID(); !ok {
		v := upgradecard.DefaultExtensionID
		_c.mutation.SetExtensionID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpgradeCardCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpgradeCard.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "UpgradeCard.description"`)}
	}
	if _, ok := _c.mutation.CardType(); !ok {
		return &ValidationError{Name: "card_type", err: errors.New(`ent: missing required field "UpgradeCard.card_type"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "UpgradeCard.cost"`)}
	}
	if _, ok := _c.mutation.Effects(); !ok {
		return &ValidationError{Name: "effects", err: errors.New(`ent: missing required field "UpgradeCard.effects"`)}
	}
	if _, ok := _c.mutation.ExtensionID(); !ok {
		return &ValidationError{Name: "extension_id", err: errors.New(`ent: missing required field "UpgradeCard.extension_id"`)}
	}
	return nil
}

func (_c *UpgradeCardCreate) sqlSave(ctx context.Context) (*UpgradeCard, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpgradeCardCreate) createSpec() (*UpgradeCard, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeCard{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upgradecard.Table, sqlgraph.NewFieldSpec(upgradecard.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upgradecard.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(upgradecard.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CardType(); ok {
		_spec.SetField(upgradecard.FieldCardType, field.TypeString, value)
		_node.CardType = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(upgradecard.FieldCost, field.TypeInt, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Effects(); ok {
		_spec.SetField(upgradecard.FieldEffects, field.TypeString, value)
		_node.Effects = value
	}
	if value, ok := _c.mutation.ExtensionID(); ok {
		_spec.SetField(upgradecard.FieldExtensionID, field.TypeInt, value)
		_node.ExtensionID = value
	}
	return _node, _spec
}

// UpgradeCardCreateBulk is the builder for creating many UpgradeCard entities in bulk.
type UpgradeCardCreateBulk struct {
	config
	err      error
	builders []*UpgradeCardCreate
}

// Save creates the UpgradeCard entities in the database.
func (_c *UpgradeCardCreateBulk) Save(ctx context.Context) ([]*UpgradeCard, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpgradeCard, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeCardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpgradeCardCreateBulk) SaveX(ctx context.Context) []*UpgradeCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpgradeCardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpgradeCardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
