// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"heat/ent/upload"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Upload is the model entity for the Upload schema.
type Upload struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash string `json:"hash,omitempty"`
	// Ext holds the value of the "ext" field.
	Ext string `json:"ext,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// ResizedURL holds the value of the "resized_url" field.
	ResizedURL string `json:"resized_url,omitempty"`
	// ThumbnailURL holds the value of the "thumbnail_url" field.
	ThumbnailURL string `json:"thumbnail_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    string `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Upload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upload.FieldID:
			values[i] = new(sql.NullInt64)
		case upload.FieldHash, upload.FieldExt, upload.FieldURL, upload.FieldResizedURL, upload.FieldThumbnailURL, upload.FieldCreatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Upload fields.
func (_m *Upload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upload.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case upload.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = value.String
			}
		case upload.FieldExt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ext", values[i])
			} else if value.Valid {
				_m.Ext = value.String
			}
		case upload.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case upload.FieldResizedURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resized_url", values[i])
			} else if value.Valid {
				_m.ResizedURL = value.String
			}
		case upload.FieldThumbnailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_url", values[i])
			} else if value.Valid {
				_m.ThumbnailURL = value.String
			}
		case upload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Upload.
// This includes values selected through modifiers, order, etc.
func (_m *Upload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Upload.
// Note that you need to call Upload.Unwrap() before calling this method if this Upload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Upload) Update() *UploadUpdateOne {
	return NewUploadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Upload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Upload) Unwrap() *Upload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Upload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Upload) String() string {
	var builder strings.Builder
	builder.WriteString("Upload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("hash=")
	builder.WriteString(_m.Hash)
	builder.WriteString(", ")
	builder.WriteString("ext=")
	builder.WriteString(_m.Ext)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("resized_url=")
	builder.WriteString(_m.ResizedURL)
	builder.WriteString(", ")
	builder.WriteString("thumbnail_url=")
	builder.WriteString(_m.ThumbnailURL)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// Uploads is a parsable slice of Upload.
type Uploads []*Upload
