// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/weathercondition"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WeatherConditionCreate is the builder for creating a WeatherCondition entity.
type WeatherConditionCreate struct {
	config
	mutation *WeatherConditionMutation
	hooks    []Hook
}

// SetRaceID sets the "race_id" field.
func (_c *WeatherConditionCreate) SetRaceID(v int) *WeatherConditionCreate {
	_c.mutation.SetRaceID(v)
	return _c
}

// SetNillableRaceID sets the "race_id" field if the given value is not nil.
func (_c *WeatherConditionCreate) SetNillableRaceID(v *int) *WeatherConditionCreate {
	if v != nil {
		_c.SetRaceID(*v)
	}
	return _c
}

// SetCondition sets the "condition" field.
func (_c *WeatherConditionCreate) SetCondition(v string) *WeatherConditionCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_c *WeatherConditionCreate) SetNillableCondition(v *string) *WeatherConditionCreate {
	if v != nil {
		_c.SetCondition(*v)
	}
	return _c
}

// SetLapStart sets the "lap_start" field.
func (_c *WeatherConditionCreate) SetLapStart(v int) *WeatherConditionCreate {
	_c.mutation.SetLapStart(v)
	return _c
}

// SetNillableLapStart sets the "lap_start" field if the given value is not nil.
func (_c *WeatherConditionCreate) SetNillableLapStart(v *int) *WeatherConditionCreate {
	if v != nil {
		_c.SetLapStart(*v)
	}
	return _c
}

// SetLapEnd sets the "lap_end" field.
func (_c *WeatherConditionCreate) SetLapEnd(v int) *WeatherConditionCreate {
	_c.mutation.SetLapEnd(v)
	return _c
}

// SetNillableLapEnd sets the "lap_end" field if the given value is not nil.
func (_c *WeatherConditionCreate) SetNillableLapEnd(v *int) *WeatherConditionCreate {
	if v != nil {
		_c.SetLapEnd(*v)
	}
	return _c
}

// SetGripModifier sets the "grip_modifier" field.
func (_c *WeatherConditionCreate) SetGripModifier(v float64) *WeatherConditionCreate {
	_c.mutation.SetGripModifier(v)
	return _c
}

// SetNillableGripModifier sets the "grip_modifier" field if the given value is not nil.
func (_c *WeatherConditionCreate) SetNillableGripModifier(v *float64) *WeatherConditionCreate {
	if v != nil {
		_c.SetGripModifier(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WeatherConditionCreate) SetID(v int) *WeatherConditionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the WeatherConditionMutation object of the builder.
func (_c *WeatherConditionCreate) Mutation() *WeatherConditionMutation {
	return _c.mutation
}

// Save creates the WeatherCondition in the database.
func (_c *WeatherConditionCreate) Save(ctx context.Context) (*WeatherCondition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WeatherConditionCreate) SaveX(ctx context.Context) *WeatherCondition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WeatherConditionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WeatherConditionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WeatherConditionCreate) defaults() {
	if _, ok := _c.mutation.RaceID(); !ok {
		v := weathercondition.DefaultRaceID
		_c.mutation.SetRaceID(v)
	}
	if _, ok := _c.mutation.Condition(); !ok {
		v := weathercondition.DefaultCondition
		_c.mutation.SetCondition(v)
	}
	if _, ok := _c.mutation.LapStart(); !ok {
		v := weathercondition.DefaultLapStart
		_c.mutation.SetLapStart(v)
	}
	if _, ok := _c.mutation.LapEnd(); !ok {
		v := weathercondition.DefaultLapEnd
		_c.mutation.SetLapEnd(v)
	}
	if _, ok := _c.mutation.GripModifier(); !ok {
		v := weathercondition.DefaultGripModifier
		_c.mutation.SetGripModifier(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WeatherConditionCreate) check() error {
	if _, ok := _c.mutation.RaceID(); !ok {
		return &ValidationError{Name: "race_id", err: errors.New(`ent: missing required field "WeatherCondition.race_id"`)}
	}
	if _, ok := _c.mutation.Condition(); !ok {
		return &ValidationError{Name: "condition", err: errors.New(`ent: missing required field "WeatherCondition.condition"`)}
	}
	if _, ok := _c.mutation.LapStart(); !ok {
		return &ValidationError{Name: "lap_start", err: errors.New(`ent: missing required field "WeatherCondition.lap_start"`)}
	}
	if _, ok := _c.mutation.LapEnd(); !ok {
		return &ValidationError{Name: "lap_end", err: errors.New(`ent: missing required field "WeatherCondition.lap_end"`)}
	}
	if _, ok := _c.mutation.GripModifier(); !ok {
		return &ValidationError{Name: "grip_modifier", err: errors.New(`ent: missing required field "WeatherCondition.grip_modifier"`)}
	}
	return nil
}

func (_c *WeatherConditionCreate) sqlSave(ctx context.Context) (*WeatherCondition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WeatherConditionCreate) createSpec() (*WeatherCondition, *sqlgraph.CreateSpec) {
	var (
		_node = &WeatherCondition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(weathercondition.Table, sqlgraph.NewFieldSpec(weathercondition.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RaceID(); ok {
		_spec.SetField(weathercondition.FieldRaceID, field.TypeInt, value)
		_node.RaceID = value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(weathercondition.FieldCondition, field.TypeString, value)
		_node.Condition = value
	}
	if value, ok := _c.mutation.LapStart(); ok {
		_spec.SetField(weathercondition.FieldLapStart, field.TypeInt, value)
		_node.LapStart = value
	}
	if value, ok := _c.mutation.LapEnd(); ok {
		_spec.SetField(weathercondition.FieldLapEnd, field.TypeInt, value)
		_node.LapEnd = value
	}
	if value, ok := _c.mutation.GripModifier(); ok {
		_spec.SetField(weathercondition.FieldGripModifier, field.TypeFloat64, value)
		_node.GripModifier = value
	}
	return _node, _spec
}

// WeatherConditionCreateBulk is the builder for creating many WeatherCondition entities in bulk.
type WeatherConditionCreateBulk struct {
	config
	err      error
	builders []*WeatherConditionCreate
}

// Save creates the WeatherCondition entities in the database.
func (_c *WeatherConditionCreateBulk) Save(ctx context.Context) ([]*WeatherCondition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WeatherCondition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WeatherConditionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WeatherConditionCreateBulk) SaveX(ctx context.Context) []*WeatherCondition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WeatherConditionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WeatherConditionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
