// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/predicate"
	"heat/ent/wledsetting"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WLEDSettingUpdate is the builder for updating WLEDSetting entities.
type WLEDSettingUpdate struct {
	config
	hooks    []Hook
	mutation *WLEDSettingMutation
}

// Where appends a list predicates to the WLEDSettingUpdate builder.
func (_u *WLEDSettingUpdate) Where(ps ...predicate.WLEDSetting) *WLEDSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetURL sets the "url" field.
func (_u *WLEDSettingUpdate) SetURL(v string) *WLEDSettingUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *WLEDSettingUpdate) SetNillableURL(v *string) *WLEDSettingUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *WLEDSettingUpdate) ClearURL() *WLEDSettingUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WLEDSettingUpdate) SetEnabled(v int) *WLEDSettingUpdate {
	_u.mutation.ResetEnabled()
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WLEDSettingUpdate) SetNillableEnabled(v *int) *WLEDSettingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddEnabled adds value to the "enabled" field.
func (_u *WLEDSettingUpdate) AddEnabled(v int) *WLEDSettingUpdate {
	_u.mutation.AddEnabled(v)
	return _u
}

// SetPresets sets the "presets" field.
func (_u *WLEDSettingUpdate) SetPresets(v string) *WLEDSettingUpdate {
	_u.mutation.SetPresets(v)
	return _u
}

// SetNillablePresets sets the "presets" field if the given value is not nil.
func (_u *WLEDSettingUpdate) SetNillablePresets(v *string) *WLEDSettingUpdate {
	if v != nil {
		_u.SetPresets(*v)
	}
	return _u
}

// ClearPresets clears the value of the "presets" field.
func (_u *WLEDSettingUpdate) ClearPresets() *WLEDSettingUpdate {
	_u.mutation.ClearPresets()
	return _u
}

// Mutation returns the WLEDSettingMutation object of the builder.
func (_u *WLEDSettingUpdate) Mutation() *WLEDSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WLEDSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WLEDSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WLEDSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WLEDSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WLEDSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wledsetting.Table, wledsetting.Columns, sqlgraph.NewFieldSpec(wledsetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(wledsetting.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(wledsetting.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(wledsetting.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnabled(); ok {
		_spec.AddField(wledsetting.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Presets(); ok {
		_spec.SetField(wledsetting.FieldPresets, field.TypeString, value)
	}
	if _u.mutation.PresetsCleared() {
		_spec.ClearField(wledsetting.FieldPresets, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wledsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WLEDSettingUpdateOne is the builder for updating a single WLEDSetting entity.
type WLEDSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WLEDSettingMutation
}

// SetURL sets the "url" field.
func (_u *WLEDSettingUpdateOne) SetURL(v string) *WLEDSettingUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *WLEDSettingUpdateOne) SetNillableURL(v *string) *WLEDSettingUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *WLEDSettingUpdateOne) ClearURL() *WLEDSettingUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WLEDSettingUpdateOne) SetEnabled(v int) *WLEDSettingUpdateOne {
	_u.mutation.ResetEnabled()
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WLEDSettingUpdateOne) SetNillableEnabled(v *int) *WLEDSettingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddEnabled adds value to the "enabled" field.
func (_u *WLEDSettingUpdateOne) AddEnabled(v int) *WLEDSettingUpdateOne {
	_u.mutation.AddEnabled(v)
	return _u
}

// SetPresets sets the "presets" field.
func (_u *WLEDSettingUpdateOne) SetPresets(v string) *WLEDSettingUpdateOne {
	_u.mutation.SetPresets(v)
	return _u
}

// SetNillablePresets sets the "presets" field if the given value is not nil.
func (_u *WLEDSettingUpdateOne) SetNillablePresets(v *string) *WLEDSettingUpdateOne {
	if v != nil {
		_u.SetPresets(*v)
	}
	return _u
}

// ClearPresets clears the value of the "presets" field.
func (_u *WLEDSettingUpdateOne) ClearPresets() *WLEDSettingUpdateOne {
	_u.mutation.ClearPresets()
	return _u
}

// Mutation returns the WLEDSettingMutation object of the builder.
func (_u *WLEDSettingUpdateOne) Mutation() *WLEDSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the WLEDSettingUpdate builder.
func (_u *WLEDSettingUpdateOne) Where(ps ...predicate.WLEDSetting) *WLEDSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WLEDSettingUpdateOne) Select(field string, fields ...string) *WLEDSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WLEDSetting entity.
func (_u *WLEDSettingUpdateOne) Save(ctx context.Context) (*WLEDSetting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WLEDSettingUpdateOne) SaveX(ctx context.Context) *WLEDSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WLEDSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WLEDSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WLEDSettingUpdateOne) sqlSave(ctx context.Context) (_node *WLEDSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(wledsetting.Table, wledsetting.Columns, sqlgraph.NewFieldSpec(wledsetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WLEDSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wledsetting.FieldID)
		for _, f := range fields {
			if !wledsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wledsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(wledsetting.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(wledsetting.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(wledsetting.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnabled(); ok {
		_spec.AddField(wledsetting.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Presets(); ok {
		_spec.SetField(wledsetting.FieldPresets, field.TypeString, value)
	}
	if _u.mutation.PresetsCleared() {
		_spec.ClearField(wledsetting.FieldPresets, field.TypeString)
	}
	_node = &WLEDSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wledsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
