// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"heat/ent/wledsetting"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WLEDSettingCreate is the builder for creating a WLEDSetting entity.
type WLEDSettingCreate struct {
	config
	mutation *WLEDSettingMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (_c *WLEDSettingCreate) SetURL(v string) *WLEDSettingCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *WLEDSettingCreate) SetNillableURL(v *string) *WLEDSettingCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *WLEDSettingCreate) SetEnabled(v int) *WLEDSettingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *WLEDSettingCreate) SetNillableEnabled(v *int) *WLEDSettingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPresets sets the "presets" field.
func (_c *WLEDSettingCreate) SetPresets(v string) *WLEDSettingCreate {
	_c.mutation.SetPresets(v)
	return _c
}

// SetNillablePresets sets the "presets" field if the given value is not nil.
func (_c *WLEDSettingCreate) SetNillablePresets(v *string) *WLEDSettingCreate {
	if v != nil {
		_c.SetPresets(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WLEDSettingCreate) SetID(v int) *WLEDSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the WLEDSettingMutation object of the builder.
func (_c *WLEDSettingCreate) Mutation() *WLEDSettingMutation {
	return _c.mutation
}

// Save creates the WLEDSetting in the database.
func (_c *WLEDSettingCreate) Save(ctx context.Context) (*WLEDSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WLEDSettingCreate) SaveX(ctx context.Context) *WLEDSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WLEDSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WLEDSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WLEDSettingCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := wledsetting.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WLEDSettingCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "WLEDSetting.enabled"`)}
	}
	return nil
}

func (_c *WLEDSettingCreate) sqlSave(ctx context.Context) (*WLEDSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WLEDSettingCreate) createSpec() (*WLEDSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &WLEDSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wledsetting.Table, sqlgraph.NewFieldSpec(wledsetting.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(wledsetting.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(wledsetting.FieldEnabled, field.TypeInt, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Presets(); ok {
		_spec.SetField(wledsetting.FieldPresets, field.TypeString, value)
		_node.Presets = value
	}
	return _node, _spec
}

// WLEDSettingCreateBulk is the builder for creating many WLEDSetting entities in bulk.
type WLEDSettingCreateBulk struct {
	config
	err      error
	builders []*WLEDSettingCreate
}

// Save creates the WLEDSetting entities in the database.
func (_c *WLEDSettingCreateBulk) Save(ctx context.Context) ([]*WLEDSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WLEDSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WLEDSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WLEDSettingCreateBulk) SaveX(ctx context.Context) []*WLEDSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WLEDSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WLEDSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
