// Code generated by ent, DO NOT EDIT.

package notificationsetting

import (
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldID, id))
}

// GotifyURL applies equality check predicate on the "gotify_url" field. It's identical to GotifyURLEQ.
func GotifyURL(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldGotifyURL, v))
}

// GotifyToken applies equality check predicate on the "gotify_token" field. It's identical to GotifyTokenEQ.
func GotifyToken(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldGotifyToken, v))
}

// NotifyWinner applies equality check predicate on the "notify_winner" field. It's identical to NotifyWinnerEQ.
func NotifyWinner(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyWinner, v))
}

// NotifyRaceStart applies equality check predicate on the "notify_race_start" field. It's identical to NotifyRaceStartEQ.
func NotifyRaceStart(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyRaceStart, v))
}

// NotifyPodium applies equality check predicate on the "notify_podium" field. It's identical to NotifyPodiumEQ.
func NotifyPodium(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyPodium, v))
}

// GotifyURLEQ applies the EQ predicate on the "gotify_url" field.
func GotifyURLEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldGotifyURL, v))
}

// GotifyURLNEQ applies the NEQ predicate on the "gotify_url" field.
func GotifyURLNEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldGotifyURL, v))
}

// GotifyURLIn applies the In predicate on the "gotify_url" field.
func GotifyURLIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldGotifyURL, vs...))
}

// GotifyURLNotIn applies the NotIn predicate on the "gotify_url" field.
func GotifyURLNotIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldGotifyURL, vs...))
}

// GotifyURLGT applies the GT predicate on the "gotify_url" field.
func GotifyURLGT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldGotifyURL, v))
}

// GotifyURLGTE applies the GTE predicate on the "gotify_url" field.
func GotifyURLGTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldGotifyURL, v))
}

// GotifyURLLT applies the LT predicate on the "gotify_url" field.
func GotifyURLLT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldGotifyURL, v))
}

// GotifyURLLTE applies the LTE predicate on the "gotify_url" field.
func GotifyURLLTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldGotifyURL, v))
}

// GotifyURLContains applies the Contains predicate on the "gotify_url" field.
func GotifyURLContains(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContains(FieldGotifyURL, v))
}

// GotifyURLHasPrefix applies the HasPrefix predicate on the "gotify_url" field.
func GotifyURLHasPrefix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasPrefix(FieldGotifyURL, v))
}

// GotifyURLHasSuffix applies the HasSuffix predicate on the "gotify_url" field.
func GotifyURLHasSuffix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasSuffix(FieldGotifyURL, v))
}

// GotifyURLIsNil applies the IsNil predicate on the "gotify_url" field.
func GotifyURLIsNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIsNull(FieldGotifyURL))
}

// GotifyURLNotNil applies the NotNil predicate on the "gotify_url" field.
func GotifyURLNotNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotNull(FieldGotifyURL))
}

// GotifyURLEqualFold applies the EqualFold predicate on the "gotify_url" field.
func GotifyURLEqualFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEqualFold(FieldGotifyURL, v))
}

// GotifyURLContainsFold applies the ContainsFold predicate on the "gotify_url" field.
func GotifyURLContainsFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContainsFold(FieldGotifyURL, v))
}

// GotifyTokenEQ applies the EQ predicate on the "gotify_token" field.
func GotifyTokenEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldGotifyToken, v))
}

// GotifyTokenNEQ applies the NEQ predicate on the "gotify_token" field.
func GotifyTokenNEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldGotifyToken, v))
}

// GotifyTokenIn applies the In predicate on the "gotify_token" field.
func GotifyTokenIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldGotifyToken, vs...))
}

// GotifyTokenNotIn applies the NotIn predicate on the "gotify_token" field.
func GotifyTokenNotIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldGotifyToken, vs...))
}

// GotifyTokenGT applies the GT predicate on the "gotify_token" field.
func GotifyTokenGT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldGotifyToken, v))
}

// GotifyTokenGTE applies the GTE predicate on the "gotify_token" field.
func GotifyTokenGTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldGotifyToken, v))
}

// GotifyTokenLT applies the LT predicate on the "gotify_token" field.
func GotifyTokenLT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldGotifyToken, v))
}

// GotifyTokenLTE applies the LTE predicate on the "gotify_token" field.
func GotifyTokenLTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldGotifyToken, v))
}

// GotifyTokenContains applies the Contains predicate on the "gotify_token" field.
func GotifyTokenContains(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContains(FieldGotifyToken, v))
}

// GotifyTokenHasPrefix applies the HasPrefix predicate on the "gotify_token" field.
func GotifyTokenHasPrefix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasPrefix(FieldGotifyToken, v))
}

// GotifyTokenHasSuffix applies the HasSuffix predicate on the "gotify_token" field.
func GotifyTokenHasSuffix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasSuffix(FieldGotifyToken, v))
}

// GotifyTokenIsNil applies the IsNil predicate on the "gotify_token" field.
func GotifyTokenIsNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIsNull(FieldGotifyToken))
}

// GotifyTokenNotNil applies the NotNil predicate on the "gotify_token" field.
func GotifyTokenNotNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotNull(FieldGotifyToken))
}

// GotifyTokenEqualFold applies the EqualFold predicate on the "gotify_token" field.
func GotifyTokenEqualFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEqualFold(FieldGotifyToken, v))
}

// GotifyTokenContainsFold applies the ContainsFold predicate on the "gotify_token" field.
func GotifyTokenContainsFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContainsFold(FieldGotifyToken, v))
}

// NotifyWinnerEQ applies the EQ predicate on the "notify_winner" field.
func NotifyWinnerEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyWinner, v))
}

// NotifyWinnerNEQ applies the NEQ predicate on the "notify_winner" field.
func NotifyWinnerNEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldNotifyWinner, v))
}

// NotifyWinnerIn applies the In predicate on the "notify_winner" field.
func NotifyWinnerIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldNotifyWinner, vs...))
}

// NotifyWinnerNotIn applies the NotIn predicate on the "notify_winner" field.
func NotifyWinnerNotIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldNotifyWinner, vs...))
}

// NotifyWinnerGT applies the GT predicate on the "notify_winner" field.
func NotifyWinnerGT(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldNotifyWinner, v))
}

// NotifyWinnerGTE applies the GTE predicate on the "notify_winner" field.
func NotifyWinnerGTE(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldNotifyWinner, v))
}

// NotifyWinnerLT applies the LT predicate on the "notify_winner" field.
func NotifyWinnerLT(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldNotifyWinner, v))
}

// NotifyWinnerLTE applies the LTE predicate on the "notify_winner" field.
func NotifyWinnerLTE(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldNotifyWinner, v))
}

// NotifyRaceStartEQ applies the EQ predicate on the "notify_race_start" field.
func NotifyRaceStartEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyRaceStart, v))
}

// NotifyRaceStartNEQ applies the NEQ predicate on the "notify_race_start" field.
func NotifyRaceStartNEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldNotifyRaceStart, v))
}

// NotifyRaceStartIn applies the In predicate on the "notify_race_start" field.
func NotifyRaceStartIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldNotifyRaceStart, vs...))
}

// NotifyRaceStartNotIn applies the NotIn predicate on the "notify_race_start" field.
func NotifyRaceStartNotIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldNotifyRaceStart, vs...))
}

// NotifyRaceStartGT applies the GT predicate on the "notify_race_start" field.
func NotifyRaceStartGT(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldNotifyRaceStart, v))
}

// NotifyRaceStartGTE applies the GTE predicate on the "notify_race_start" field.
func NotifyRaceStartGTE(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldNotifyRaceStart, v))
}

// NotifyRaceStartLT applies the LT predicate on the "notify_race_start" field.
func NotifyRaceStartLT(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldNotifyRaceStart, v))
}

// NotifyRaceStartLTE applies the LTE predicate on the "notify_race_start" field.
func NotifyRaceStartLTE(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldNotifyRaceStart, v))
}

// NotifyPodiumEQ applies the EQ predicate on the "notify_podium" field.
func NotifyPodiumEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyPodium, v))
}

// NotifyPodiumNEQ applies the NEQ predicate on the "notify_podium" field.
func NotifyPodiumNEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldNotifyPodium, v))
}

// NotifyPodiumIn applies the In predicate on the "notify_podium" field.
func NotifyPodiumIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldNotifyPodium, vs...))
}

// NotifyPodiumNotIn applies the NotIn predicate on the "notify_podium" field.
func NotifyPodiumNotIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldNotifyPodium, vs...))
}

// NotifyPodiumGT applies the GT predicate on the "notify_podium" field.
func NotifyPodiumGT(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldNotifyPodium, v))
}

// NotifyPodiumGTE applies the GTE predicate on the "notify_podium" field.
func NotifyPodiumGTE(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldNotifyPodium, v))
}

// NotifyPodiumLT applies the LT predicate on the "notify_podium" field.
func NotifyPodiumLT(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldNotifyPodium, v))
}

// NotifyPodiumLTE applies the LTE predicate on the "notify_podium" field.
func NotifyPodiumLTE(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldNotifyPodium, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.NotPredicates(p))
}
