name: CI checks

on:
  workflow_call:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'

      - name: Download dependencies
        run: go mod download

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Run Tests
        run: go test -v ./...

      - name: Build
        run: go build -o heat-server .

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag heat:$(git rev-parse --short HEAD)