name: CI checks

on:
  workflow_call:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -o heat .

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag heat:$(git rev-parse --short HEAD)

      - name: Push Docker image
        if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
        run: |
          docker tag heat:$(git rev-parse --short HEAD) heat:latest
          docker push heat:latest