// Code generated by ent, DO NOT EDIT.

package adminuser

import (
	"heat/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldPassword, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldEmail, v))
}

// OidcSub applies equality check predicate on the "oidc_sub" field. It's identical to OidcSubEQ.
func OidcSub(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldOidcSub, v))
}

// AuthMethod applies equality check predicate on the "auth_method" field. It's identical to AuthMethodEQ.
func AuthMethod(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldAuthMethod, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContainsFold(FieldPassword, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContainsFold(FieldEmail, v))
}

// OidcSubEQ applies the EQ predicate on the "oidc_sub" field.
func OidcSubEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldOidcSub, v))
}

// OidcSubNEQ applies the NEQ predicate on the "oidc_sub" field.
func OidcSubNEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNEQ(FieldOidcSub, v))
}

// OidcSubIn applies the In predicate on the "oidc_sub" field.
func OidcSubIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIn(FieldOidcSub, vs...))
}

// OidcSubNotIn applies the NotIn predicate on the "oidc_sub" field.
func OidcSubNotIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotIn(FieldOidcSub, vs...))
}

// OidcSubGT applies the GT predicate on the "oidc_sub" field.
func OidcSubGT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGT(FieldOidcSub, v))
}

// OidcSubGTE applies the GTE predicate on the "oidc_sub" field.
func OidcSubGTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGTE(FieldOidcSub, v))
}

// OidcSubLT applies the LT predicate on the "oidc_sub" field.
func OidcSubLT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLT(FieldOidcSub, v))
}

// OidcSubLTE applies the LTE predicate on the "oidc_sub" field.
func OidcSubLTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLTE(FieldOidcSub, v))
}

// OidcSubContains applies the Contains predicate on the "oidc_sub" field.
func OidcSubContains(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContains(FieldOidcSub, v))
}

// OidcSubHasPrefix applies the HasPrefix predicate on the "oidc_sub" field.
func OidcSubHasPrefix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasPrefix(FieldOidcSub, v))
}

// OidcSubHasSuffix applies the HasSuffix predicate on the "oidc_sub" field.
func OidcSubHasSuffix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasSuffix(FieldOidcSub, v))
}

// OidcSubIsNil applies the IsNil predicate on the "oidc_sub" field.
func OidcSubIsNil() predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIsNull(FieldOidcSub))
}

// OidcSubNotNil applies the NotNil predicate on the "oidc_sub" field.
func OidcSubNotNil() predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotNull(FieldOidcSub))
}

// OidcSubEqualFold applies the EqualFold predicate on the "oidc_sub" field.
func OidcSubEqualFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEqualFold(FieldOidcSub, v))
}

// OidcSubContainsFold applies the ContainsFold predicate on the "oidc_sub" field.
func OidcSubContainsFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContainsFold(FieldOidcSub, v))
}

// AuthMethodEQ applies the EQ predicate on the "auth_method" field.
func AuthMethodEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEQ(FieldAuthMethod, v))
}

// AuthMethodNEQ applies the NEQ predicate on the "auth_method" field.
func AuthMethodNEQ(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNEQ(FieldAuthMethod, v))
}

// AuthMethodIn applies the In predicate on the "auth_method" field.
func AuthMethodIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIn(FieldAuthMethod, vs...))
}

// AuthMethodNotIn applies the NotIn predicate on the "auth_method" field.
func AuthMethodNotIn(vs ...string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotIn(FieldAuthMethod, vs...))
}

// AuthMethodGT applies the GT predicate on the "auth_method" field.
func AuthMethodGT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGT(FieldAuthMethod, v))
}

// AuthMethodGTE applies the GTE predicate on the "auth_method" field.
func AuthMethodGTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldGTE(FieldAuthMethod, v))
}

// AuthMethodLT applies the LT predicate on the "auth_method" field.
func AuthMethodLT(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLT(FieldAuthMethod, v))
}

// AuthMethodLTE applies the LTE predicate on the "auth_method" field.
func AuthMethodLTE(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldLTE(FieldAuthMethod, v))
}

// AuthMethodContains applies the Contains predicate on the "auth_method" field.
func AuthMethodContains(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContains(FieldAuthMethod, v))
}

// AuthMethodHasPrefix applies the HasPrefix predicate on the "auth_method" field.
func AuthMethodHasPrefix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasPrefix(FieldAuthMethod, v))
}

// AuthMethodHasSuffix applies the HasSuffix predicate on the "auth_method" field.
func AuthMethodHasSuffix(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldHasSuffix(FieldAuthMethod, v))
}

// AuthMethodIsNil applies the IsNil predicate on the "auth_method" field.
func AuthMethodIsNil() predicate.AdminUser {
	return predicate.AdminUser(sql.FieldIsNull(FieldAuthMethod))
}

// AuthMethodNotNil applies the NotNil predicate on the "auth_method" field.
func AuthMethodNotNil() predicate.AdminUser {
	return predicate.AdminUser(sql.FieldNotNull(FieldAuthMethod))
}

// AuthMethodEqualFold applies the EqualFold predicate on the "auth_method" field.
func AuthMethodEqualFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldEqualFold(FieldAuthMethod, v))
}

// AuthMethodContainsFold applies the ContainsFold predicate on the "auth_method" field.
func AuthMethodContainsFold(v string) predicate.AdminUser {
	return predicate.AdminUser(sql.FieldContainsFold(FieldAuthMethod, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminUser) predicate.AdminUser {
	return predicate.AdminUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminUser) predicate.AdminUser {
	return predicate.AdminUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminUser) predicate.AdminUser {
	return predicate.AdminUser(sql.NotPredicates(p))
}
